### ISSUE TITLE
{{ form:set }} tag issue since upgrading to v5

### ISSUE THREAD

**Issue by atomicjam** [statamic/cms#10091]
### Bug description

since upgrading to statamic v5 {{ form:set is="" }} doesn't appear to work when passing in handle from user defined field, rolling back to v4 everything works fine.

which_form is form selector from in cms. i.e.

{{ form:set is="{ which_form:handle }" }}

throws 

ERROR: A form handle is required on Form tags. Please refer to the docs for more information. {"userId":"718fefb8-3710-42b5-accd-e3e3d00daffe","exception":"[object] (Exception(code: 0): A form handle is required on Form tags. Please refer to the docs for more information. at /data/Flourish/vendor/statamic/cms/src/Forms/Tags.php:205)

### How to reproduce

repo example available at: https://github.com/atomicjam/flourish-debug
form example: https://github.com/atomicjam/flourish-debug/blob/main/resources/views/partials/sets/form.antlers.html

### Logs

```shell
[2024-05-15 19:17:48] production.ERROR: A form handle is required on Form tags. Please refer to the docs for more information. {"userId":"718fefb8-3710-42b5-accd-e3e3d00daffe","exception":"[object] (Exception(code: 0): A form handle is required on Form tags. Please refer to the docs for more information. at /data/Flourish/vendor/statamic/cms/src/Forms/Tags.php:205)
[stacktrace]
#0 /data/Flourish/vendor/statamic/cms/src/Forms/Tags.php(343): Statamic\\Forms\\Tags->getForm()
#1 /data/Flourish/vendor/statamic/cms/src/Forms/Tags.php(157): Statamic\\Forms\\Tags->sessionHandle()
#2 [internal function]: Statamic\\Forms\\Tags->success()
#3 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func()
#4 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#5 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/ConditionProcessor.php(87): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#6 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1305): Statamic\\View\\Antlers\\Language\\Runtime\\ConditionProcessor->process()
#7 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#8 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#9 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(718): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#10 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Antlers.php(31): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parse()
#11 /data/Flourish/vendor/statamic/cms/src/Tags/Tags.php(173): Statamic\\View\\Antlers\\Antlers->parse()
#12 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Antlers.php(22): Statamic\\Tags\\Tags->Statamic\\Tags\\{closure}()
#13 /data/Flourish/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Statamic\\View\\Antlers\\Antlers->usingParser()
#14 /data/Flourish/vendor/statamic/cms/src/Tags/Tags.php(171): Illuminate\\Support\\Facades\\Facade::__callStatic()
#15 /data/Flourish/vendor/statamic/cms/src/Tags/Tags.php(219): Statamic\\Tags\\Tags->parse()
#16 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1749): Statamic\\Tags\\Tags->parseNoResults()
#17 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#18 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#19 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#20 /data/Flourish/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#21 /data/Flourish/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\\View\\Antlers\\Engine->get()
#22 /data/Flourish/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\\View\\View->getContents()
#23 /data/Flourish/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#24 /data/Flourish/vendor/statamic/cms/src/StaticCaching/NoCache/StringFragment.php(34): Illuminate\\View\\View->render()
#25 /data/Flourish/vendor/statamic/cms/src/StaticCaching/NoCache/StringRegion.php(31): Statamic\\StaticCaching\\NoCache\\StringFragment->render()
#26 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Replacers/NoCacheReplacer.php(66): Statamic\\StaticCaching\\NoCache\\StringRegion->render()
#27 [internal function]: Statamic\\StaticCaching\\Replacers\\NoCacheReplacer->Statamic\\StaticCaching\\Replacers\\{closure}()
#28 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Replacers/NoCacheReplacer.php(61): preg_replace_callback()
#29 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Replacers/NoCacheReplacer.php(53): Statamic\\StaticCaching\\Replacers\\NoCacheReplacer->performReplacement()
#30 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Replacers/NoCacheReplacer.php(47): Statamic\\StaticCaching\\Replacers\\NoCacheReplacer->replace()
#31 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Replacers/NoCacheReplacer.php(25): Statamic\\StaticCaching\\Replacers\\NoCacheReplacer->replaceInResponse()
#32 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(93): Statamic\\StaticCaching\\Replacers\\NoCacheReplacer->prepareResponseToCache()
#33 /data/Flourish/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Statamic\\StaticCaching\\Middleware\\Cache->Statamic\\StaticCaching\\Middleware\\{closure}()
#34 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(93): Illuminate\\Support\\Collection->each()
#35 /data/Flourish/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(66): Statamic\\StaticCaching\\Middleware\\Cache->makeReplacementsAndCacheResponse()
#36 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#37 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AuthGuard->handle()
#39 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#41 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\Localize->handle()
#43 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\HandleToken->handle()
#45 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StacheLock->handle()
#47 /data/Flourish/vendor/spatie/laravel-csp/src/AddCspHeaders.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Spatie\\Csp\\AddCspHeaders->handle()
#49 /data/Flourish/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#51 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#53 /data/Flourish/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#55 /data/Flourish/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /data/Flourish/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#57 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#58 /data/Flourish/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#60 /data/Flourish/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#62 /data/Flourish/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->handle()
#64 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /data/Flourish/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#66 /data/Flourish/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#67 /data/Flourish/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#68 /data/Flourish/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#69 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#70 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#71 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#73 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#75 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#77 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#79 /data/Flourish/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#81 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#83 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#84 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#86 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#87 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#89 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#91 /data/Flourish/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#93 /data/Flourish/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#95 /data/Flourish/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#96 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#97 /data/Flourish/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#98 /data/Flourish/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#99 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Flourish
Laravel Version: 10.48.10
PHP Version: 8.3.4
Composer Version: 2.3.10
Environment: production
Debug Mode: OFF
URL: flourish.cheltladiescollege.org
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.2.0 PRO

Statamic Addons
mitydigital/feedamic: 2.3.2
mitydigital/sitemapamic: 3.0.1
rias/statamic-redirect: 3.7.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by espenlg** [comment]
Not sure if it's the same thing, but I had this problem too. The which_form you refer to is returned as an multi-dimension array even though it's only one form connected yes? I did which_form:0:handle and that worked. Is it the same problem?

**Comment by atomicjam** [comment]
Thanks Espen, probably should have figured that out myself figured it was something way more complex.

in v4 was it returning multi-dimensional array? or has the array being returned changed in v5?  I might need to check other places we have the user select things in the CMS.

**Comment by espenlg** [comment]
I was under the impression the form fieldtype worked the same way as assets. If maxitem = 1 it returned the object, but if more items it returns an array. It is a new problem, and it does not work the way it should according to the documentation so it will probably be looked at.

**Comment by atomicjam** [comment]
Thanks for your help

**Comment by jasonvarga** [comment]
I don't think anything about this should have changed. We'll try and replicate this and let you know.

**Comment by duncanmcclean** [comment]
I think this is happening due to another issue, which was removing `max_items: 1` from the Form field in your blueprint. This caused `which_form` to be an array of forms, instead of a single form which is expected by the `{{ form:set }}` tag.

If you upgrade to the latest version (currently 5.2.0), open the relevant blueprint or fieldset, and re-save the Form field, it should fix the issue.

You can also manually add back `max_items: 1` to the field config manually:

```yaml
-
  handle: which_form
  field:
    max_items: 1
    display: 'Which Form'
    type: form
    icon: form
    listable: hidden
    instructions_position: above
    visibility: visible
```

**Comment by atomicjam** [comment]
Ive removed the which_form:0:handle set it back and resaved the blueprints, and max_items: 1 was re-added on save.

Everything working correctly again, thanks for help. 

im assuming on older repos ive not upgraded to v5 yet won't have this issue since they will upgrade to a version greater than 5.2.0 when I come to do them. or will I need to open and resave all the blueprints?

**Comment by duncanmcclean** [comment]
> im assuming on older repos ive not upgraded to v5 yet won't have this issue since they will upgrade to a version greater than 5.2.0 when I come to do them. or will I need to open and resave all the blueprints?

Correct, it was just an issue between `5.0.0` and `5.1.0`.
