### ISSUE TITLE
Error creating user in database

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1068]
I followed instructions on how to store users in db, the tried to add my first user by `php please make:user` after this I entered mail of user but next step gave me this error:

```
[2019-12-05 08:01:58] local.ERROR: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object {"exception":"[object] (ErrorException(code: 0): call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object at /private/var/www/st/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php:62)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'call_user_func_...', '/private/var/ww...', 62, Array)
#1 /private/var/www/st/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php(62): call_user_func_array(Array, Array)
#2 /private/var/www/st/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php(28): Statamic\\Auth\\Eloquent\\UserRepository->model('all')
#3 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(245): Statamic\\Auth\\Eloquent\\UserRepository->all()
#4 /private/var/www/st/vendor/statamic/cms/src/Rules/EmailAvailable.php(19): Illuminate\\Support\\Facades\\Facade::__callStatic('all', Array)
#5 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(572): Statamic\\Rules\\EmailAvailable->passes('input', 'email@...')
#6 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(392): Illuminate\\Validation\\Validator->validateUsingCustomRule('input', 'email@...', Object(Statamic\\Rules\\EmailAvailable))
#7 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(277): Illuminate\\Validation\\Validator->validateAttribute('input', Object(Statamic\\Rules\\EmailAvailable))
#8 /private/var/www/st/vendor/statamic/cms/src/Console/ValidatesInput.php(20): Illuminate\\Validation\\Validator->passes()
#9 /private/var/www/st/vendor/statamic/cms/src/Console/Commands/MakeUser.php(161): Statamic\\Console\\Commands\\MakeUser->validationFails('email@...', Array)
#10 /private/var/www/st/vendor/statamic/cms/src/Console/Commands/MakeUser.php(76): Statamic\\Console\\Commands\\MakeUser->emailValidationFails()
#11 /private/var/www/st/vendor/statamic/cms/src/Console/Commands/MakeUser.php(60): Statamic\\Console\\Commands\\MakeUser->promptEmail()
#12 [internal function]: Statamic\\Console\\Commands\\MakeUser->handle()
#13 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#14 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Container/Util.php(34): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#19 /private/var/www/st/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /private/var/www/st/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /private/var/www/st/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Statamic\\Console\\Commands\\MakeUser), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /private/var/www/st/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /private/var/www/st/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /private/var/www/st/please(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
```

**Comment by pttrnco** [comment]
If you are using the Eloquent driver, you'll need to specify which model you are using.

In `config.auth`:

```
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => \App\User::class
    ],
],
```

**Comment by jasonvarga** [comment]
Closing this, the comment above is the answer.

In statamic/statamic, auth.php was missing that.

Brought back in https://github.com/statamic/statamic/commit/48f59fdb9f52eca008adc014265a1210c3c059b2#diff-3fc9d8e570780c4eb337c6f860b1e8e0

The docs have also since been updated.
