### ISSUE TITLE
Call to a member function bordersInterpolationRegion() on null

### ISSUE THREAD

**Issue by beliven-fabrizio-gortani** [statamic/cms#10816]
### Bug description

This error just appear in our production environment. 

```
Call to a member function bordersInterpolationRegion() on null
```

### How to reproduce

I don't have idea to reproduce this behavior

### Logs

```shell
[2024-09-18 16:25:50] production.ERROR: Call to a member function bordersInterpolationRegion() on null {"userId":"5efda472-6739-49bf-806e-a7968fb4b533","exception":"[object] (Error(code: 0): Call to a member function bordersInterpolationRegion() on null at /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Lexer/AntlersLexer.php:173)
[stacktrace]
#0 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Lexer/AntlersLexer.php(711): Statamic\\View\\Antlers\\Language\\Lexer\\AntlersLexer->isRightOfInterpolationRegion()
#1 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(859): Statamic\\View\\Antlers\\Language\\Lexer\\AntlersLexer->tokenize()
#2 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Nodes/AntlersNode.php(437): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->getVariable()
#3 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Nodes/AntlersNode.php(363): Statamic\\View\\Antlers\\Language\\Nodes\\AntlersNode->getSingleParameterValue()
#4 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1507): Statamic\\View\\Antlers\\Language\\Nodes\\AntlersNode->getParameterValues()
#5 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#6 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#7 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(715): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#8 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Antlers.php(31): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parse()
#9 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Tags/Tags.php(173): Statamic\\View\\Antlers\\Antlers->parse()
#10 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Antlers.php(22): Statamic\\Tags\\Tags->Statamic\\Tags\\{closure}()
#11 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Statamic\\View\\Antlers\\Antlers->usingParser()
#12 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Tags/Tags.php(171): Illuminate\\Support\\Facades\\Facade::__callStatic()
#13 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Tags/Partial.php(24): Statamic\\Tags\\Tags->parse()
#14 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render()
#15 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Tags/Tags.php(152): Statamic\\Tags\\Partial->wildcard()
#16 [internal function]: Statamic\\Tags\\Tags->__call()
#17 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func()
#18 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#19 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#20 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#21 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#22 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\\View\\Antlers\\Engine->get()
#23 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\\View\\View->getContents()
#24 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#25 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/View/View.php(104): Illuminate\\View\\View->render()
#26 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Responses/DataResponse.php(146): Statamic\\View\\View->render()
#27 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Responses/DataResponse.php(42): Statamic\\Http\\Responses\\DataResponse->contents()
#28 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Structures/Page.php(420): Statamic\\Http\\Responses\\DataResponse->toResponse()
#29 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(900): Statamic\\Structures\\Page->toResponse()
#30 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse()
#31 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse()
#32 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#33 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#35 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AuthGuard->handle()
#37 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#39 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\Localize->handle()
#41 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\HandleToken->handle()
#43 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StacheLock->handle()
#45 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#47 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#49 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#51 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#53 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#54 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#56 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#58 /home/my-user/www.my-domain.com/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->handle()
#60 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#62 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#63 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#64 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#65 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#66 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#67 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#69 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#71 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#73 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#75 /home/my-user/www.my-domain.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#77 /home/my-user/www.my-domain.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#79 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#81 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#82 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#84 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#85 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#87 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#89 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#91 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#93 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#95 /home/my-user/www.my-domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#96 /home/my-user/www.my-domain.com/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#97 {main}
"}
```

### Environment

```yaml
Environment
Application Name: My-App
Laravel Version: 10.48.15
PHP Version: 8.2.19
Composer Version: 2.7.9
Environment: production
Debug Mode: OFF
URL: www.my-domain.com
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single, stderr, mezmo
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 11 (....)
Stache Watcher: Disabled
Static Caching: half
Version: 5.12.0 PRO

Statamic Addons
aerni/social-links: 3.2.0
aryehraber/statamic-captcha: 1.12.0
rias/statamic-redirect: 3.7.1
ryanmitchell/statamic-translation-manager: 1.6.0
tv2regionerne/statamic-image-cropper: 1.7.0
xndbogdan/statamic-bard-text-color: 5.1.1
```

### Installation

Existing Laravel app

**Comment by duncanmcclean** [comment]
Unfortunatley, that doesn't give us much information to go on. 

Are you able to try and narrow down which template or partial in your project is causing the error?

**Comment by beliven-fabrizio-gortani** [comment]
I've fixed the error right now.. My page title contains a string like:

```
Sales Manager - paesi europei dell' est (Balcani esclusi)
```

If i transform the title removing the apostrophe 

```
Sales Manager - paesi europei dell est (Balcani esclusi)
```

now it works.

Do you have any idea why it's happend?

**Comment by duncanmcclean** [comment]
Glad to hear it's fixed now!

What did you change to fix it?

**Comment by beliven-fabrizio-gortani** [comment]
For now, I've fixed it by modifying the title and removing the apostrophe from it. Later today, the team will try changing the function that generates the breadcrumb to figure out how to handle characters that might break the string concatenation.
