### ISSUE TITLE
Collections section of CP broken after activating multisite

### ISSUE THREAD

**Issue by leewillis77** [statamic/cms#11087]
### Bug description

Enabling multisite makes all access to the Collections area of the control panel inaccessible, failing with the following backtrace:
```
Undefined array key 1 {"userId":"e4e5193a-4258-4b06-9ad4-dea7928198ed","exception":"[object] (ErrorExceptio
n(code: 0): Undefined array key 1 at /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:43)
[stacktrace]
#0 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Boots
trap\\HandleExceptions->handleError(2, 'Undefined array...', '/Users/lee/Herd...', 43)
#1 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(43): Illuminate\\Foundation\\Bootstrap\\HandleExcept
ions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/Users/lee/Herd...', 43)
#2 [internal function]: Statamic\\Stache\\Stores\\CollectionEntriesStore->getItemFilter(Object(Symfony\\Component\\Finder\\SplFileInfo), 0)
#3 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(926): array_filter(Array, Array, 1)
#4 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(391): Illuminate\\Support\\Arr::where(Array, Array
)
#5 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Traverser.php(33): Illuminate\\Support\\Collection->filter(Array)
#6 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Stores/Store.php(186): Statamic\\Stache\\Traverser->traverse(Object(Statamic\\Stache\\
Stores\\CollectionEntriesStore))
#7 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Stores/Store.php(45): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#8 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/Builder.php(115): Statamic\\Stache\\Stores\\Store->index('site')
#9 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(96): Statamic\\Stache\\Query\\Builder->getWhereColumnKeysF
romStore('pages', Array)
#10 [internal function]: Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}('pages', 0)
#11 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map(Object(Closure), Array, Array)
#12 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map(Array, Object
(Closure))
#13 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(427): Illuminate\\Support\\Collectio
n->map(Object(Closure))
#14 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(95): Illuminate\\Support\\Collection->flatMap(Object(Clos
ure))
#15 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(87): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysF
romCollectionsWithWhere(Array, Array)
#16 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(818): Statamic\\Stache\\Query\\Entry
QueryBuilder->Statamic\\Stache\\Query\\{closure}(NULL, Array, 0)
#17 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(84): Illuminate\\Support\\Collection->reduce(Object(Closu
re))
#18 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(68): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysF
romCollectionsWithWheres(Array, Array)
#19 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/Builder.php(60): Statamic\\Stache\\Query\\EntryQueryBuilder->getFilteredKeys()
#20 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Stache/Query/Builder.php(22): Statamic\\Stache\\Query\\Builder->getFilteredAndLimitedKeys()
#21 /Users/lee/Herd/msbug/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionsController.php(59): Statamic\\Stache\\Query\\Buil
der->count()
#22 [internal function]: Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController->Statamic\\Http\\Controllers\\CP\\Collections\\{c
losure}(Object(Statamic\\Entries\\Collection), 0)
#23 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map(Object(Closure), Array, Array)
#24 /Users/lee/Herd/msbug/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map(Array, Object
(Closure))
```

### How to reproduce

- Create a new Statamic site with `statamic new msbug`
- Answer the install questions as follows (I don't believe these settings - beyond choosing Pro - are particularly relevant, but the bug can be reproduced with these option):
  - Would you like to install a starter kit? -  No, start with a blank site.
  - Where do you want to store your content and data? - Flat files
  - Do you want to enable Statamic Pro?  - Yes
  - Do you plan to generate a static site? - No
  - Create a super user? - Yes
- Log into the Control Panel and confirm that the Collections section, including "Pages" is accessible
- Activate multisite by running `php please multisite`
- Try and access the Collections area in the control panel and notice that an error is thrown

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.30.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: msbug.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.37.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Confirmed. 

![CleanShot 2024-11-07 at 10 29 50](https://github.com/user-attachments/assets/6e48f4ab-126f-401f-942b-2b4a6b300694)

The `Updating collection [pages]` bit is supposed to move the entries into a subdirectory. It doesn't.

**Comment by fpolli** [comment]
Just adding comment to say that this just happened to me now. Exactly as described in the OP.

**Comment by ryanmitchell** [comment]
@fpolli theres a fix here - it just hasnt made it to a release yet: https://github.com/statamic/cms/pull/11105

**Comment by torbentschechne** [comment]
I believe that I migrated to multisite on an older version, before this fix was merged. I still get this error when I want to save a collection item:

```
local.ERROR: Method Illuminate\Validation\Validator::validateUniqueEntryValue does not exist. {"userId":"fe8a906a-90d6-4695-836a-d04bda092cea","exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Validation\\Validator::validateUniqueEntryValue does not exist. at vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1680)
[stacktrace]
```

What puzzles me is that my sites.yaml introduces to handle `default` and `english`. All the *.md files in `content` are located under `default` or `english`. Does anybody have a tip on where this issue can be coming from now?

**Comment by duncanmcclean** [comment]
You likely need to make the changes mentioned in the v4 -> v5 upgrade guide: https://statamic.dev/upgrade-guide/4-to-5#validation-rule-changes

**Comment by torbentschechne** [comment]
> You likely need to make the changes mentioned in the v4 -> v5 upgrade guide: https://statamic.dev/upgrade-guide/4-to-5#validation-rule-changes

@duncanmcclean Thank you so much for your quick answer. That was the reason! ✅
