### ISSUE TITLE
Custom widgets does not load on Statamic v5.42

### ISSUE THREAD

**Issue by david-windsock** [statamic/cms#11241]
### Bug description

We have multiple custom widgets added to the dashboard, created with the `php please make:widget` command. After upgrade from v5.41 to v5.42 the dashboard fails to load with a `Statamic\Widgets\WidgetNotFoundException` exception.

This is the v5.41 output for `app('statamic.widgets')`:

```
$ artisan tinker
Psy Shell v0.12.7 (PHP 8.2.24 — cli) by Justin Hileman
> app('statamic.widgets')
= Illuminate\Support\Collection {#321
    all: [
      "collection" => "Statamic\Widgets\Collection",
      "getting_started" => "Statamic\Widgets\GettingStarted",
      "header" => "Statamic\Widgets\Header",
      "template" => "Statamic\Widgets\Template",
      "updater" => "Statamic\Widgets\Updater",
      "form" => "Statamic\Forms\Widget",
      "example" => "App\Widgets\Example",
    ],
  }
```

And this is the v5.42 output for `app('statamic.widgets')`:

```
$ artisan tinker
Psy Shell v0.12.7 (PHP 8.2.24 — cli) by Justin Hileman
> app('statamic.widgets')
= Illuminate\Support\Collection {#321
    all: [
      "collection" => "Statamic\Widgets\Collection",
      "getting_started" => "Statamic\Widgets\GettingStarted",
      "header" => "Statamic\Widgets\Header",
      "template" => "Statamic\Widgets\Template",
      "updater" => "Statamic\Widgets\Updater",
      "form" => "Statamic\Forms\Widget",
    ],
  }
```

### How to reproduce

1. Install Laravel with `composer create-project laravel/laravel statamic-widgets && cd statamic-widgets`
2. Install (Statamic into Laravel)[https://statamic.dev/installing/laravel] but forcing v5.41 with `composer require statamic/cms:5.41 --with-dependencies`
3. Add and run migrations with `php please auth:migration && php artisan migrate`
4. Create an user with `php please make:user` and login into de control panel
5. [Create a widget](https://statamic.dev/extending/widgets) with `php please make:widget Example` 
6. Add the to the dashboard on `/config/statamic/cp.php`: `'widgets' => [['type' => 'example', 'width' => 50]],`
7. Verify the widget on the dashboard seeing _I'm the Example widget!_
8. Update Statamic to v5.42 with `composer require statamic/cms:5.41`
9. Load the dashboard again to see the exception with the message `Widget [example] not found`

### Logs

```shell
[2024-12-10 13:08:59] local.ERROR: Widget [example] not found {"userId":1,"exception":"[object] (Statamic\\Widgets\\WidgetNotFoundException(code: 0): Widget [example] not found at C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Widgets\\Loader.php:10)
[stacktrace]
#0 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Controllers\\CP\\DashboardController.php(55): Statamic\\Widgets\\Loader->load('example', Array)
#1 [internal function]: Statamic\\Http\\Controllers\\CP\\DashboardController->Statamic\\Http\\Controllers\\CP\\{closure}(Array, 0)
#2 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(609): array_map(Object(Closure), Array, Array)
#3 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(795): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#4 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Controllers\\CP\\DashboardController.php(53): Illuminate\\Support\\Collection->map(Object(Closure))
#5 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Controllers\\CP\\DashboardController.php(21): Statamic\\Http\\Controllers\\CP\\DashboardController->getDisplayableWidgets(Object(Statamic\\Widgets\\Loader))
#6 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): Statamic\\Http\\Controllers\\CP\\DashboardController->index(Object(Statamic\\Widgets\\Loader))
#7 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('index', Array)
#8 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(265): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\DashboardController), 'index')
#9 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(211): Illuminate\\Routing\\Route->runController()
#10 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(808): Illuminate\\Routing\\Route->run()
#11 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\AddVaryHeaderToResponse.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AddVaryHeaderToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\SelectedSite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\SelectedSite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#48 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#58 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#59 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#60 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#61 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#62 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\statamic\\cms\\src\\Http\\Middleware\\PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenane.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#89 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#90 C:\\Develop\\htdocs\\testing\\statamic-widgets\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#91 C:\\Develop\\htdocs\\testing\\statamic-widgets\\public\\index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#92 {main}
"}
```

### Environment

```yaml
Application Name: Laravel
Laravel Version: 11.34.2
PHP Version: 8.2.24
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: sqlite
Logs: stack / single
Mail: log
Queue: database
Session: database

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.0 Solo
```

### Installation

Existing Laravel app

**Comment by duncanmcclean** [comment]
Yes, this is the same issue as #11231. Closing in favour of that one.
