### ISSUE TITLE
Tests don't pass when users are in DB

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1232]
With users in the DB, the Example tests that are installed with the statamic project throw an error:

```
[2020-01-19 04:46:24] testing.ERROR: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object {"exception":"[object] (ErrorException(code: 0): call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object at /Users/erin/Sites/charge4/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php:62)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'call_user_func_...', '/Users/erin/Sit...', 62, Array)
#1 /Users/erin/Sites/charge4/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php(62): call_user_func_array(Array, Array)
#2 /Users/erin/Sites/charge4/vendor/statamic/cms/src/Auth/Eloquent/UserRepository.php(37): Statamic\\Auth\\Eloquent\\UserRepository->model('find', NULL)
```

**Comment by jasonvarga** [comment]
Ah missing a step in the docs.

In `config/auth.php`, change `providers.users` to

```
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
```

**Comment by danielreales7** [comment]
Same happens to me in v 4.45 statamic

**Comment by duncanmcclean** [comment]
This issue is over 4 years old - please open a new issue if you're still having issues.

**Comment by danielreales7** [comment]
@duncanmcclean I write in discord: https://discord.com/channels/489818810157891584/1214120244608761866
