### ISSUE TITLE
User id error: array_key_exists(): The first argument should be either a string or an integer

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1489]
Received this error when migrating a user account from V2 to V3. I've since deleted all users and now I receive this error when creating a user in the CP, and when viewing their profiles.

```
[2020-03-09 23:26:03] staging.ERROR: array_key_exists(): The first argument should be either a string or an integer {"userId":"bf1b3343-ece9-442b-b4a6-104c0e54313a","exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1279)
```

**Comment by jasonvarga** [comment]
If there is a stack trace to go along with that error please provide it.

**Comment by mikemartin** [comment]
Here's the error log:

```
[2020-03-09 23:31:55] staging.ERROR: array_key_exists(): The first argument should be either a string or an integer {"userId":"fcefbdba-b5ff-40cc-9ddf-1e1b2624e3aa","exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1279)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', '/home/forge/sta...', 1279, Array)
#1 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1279): array_key_exists(Object(Statamic\\Auth\\File\\User), Array)
#2 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(415): Illuminate\\Support\\Collection->offsetExists(Object(Statamic\\Auth\\File\\User))
#3 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(75): Illuminate\\Support\\Collection->get(Object(Statamic\\Auth\\File\\User))
#4 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(27): Statamic\\Stache\\Stores\\BasicStore->getPath(Object(Statamic\\Auth\\File\\User))
#5 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Stache/Repositories/UserRepository.php(43): Statamic\\Stache\\Stores\\BasicStore->getItem(Object(Statamic\\Auth\\File\\User))
#6 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\UserRepository->find(Object(Statamic\\Auth\\File\\User))
#7 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Controllers/CP/Users/UsersController.php(150): Illuminate\\Support\\Facades\\Facade::__callStatic('find', Array)
#8 [internal function]: Statamic\\Http\\Controllers\\CP\\Users\\UsersController->edit(Object(Illuminate\\Http\\Request), Object(Statamic\\Auth\\File\\User))
#9 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('edit', Array)
#11 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Users\\UsersController), 'edit')
#12 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#13 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#14 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\StaticCaching\\Middleware\\Retrieve->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/forge/staging.aurorainsight.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/forge/staging.aurorainsight.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /home/forge/staging.aurorainsight.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 {main}
"}
[2020-03-09 23:33:59] staging.ERROR: array_key_exists(): The first argument should be either a string or an integer {"userId":"3982470a-4f25-4c39-a401-cf6c32a5012b","exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1279)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', '/home/forge/sta...', 1279, Array)
#1 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1279): array_key_exists(Object(Statamic\\Auth\\File\\User), Array)
#2 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(415): Illuminate\\Support\\Collection->offsetExists(Object(Statamic\\Auth\\File\\User))
#3 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(75): Illuminate\\Support\\Collection->get(Object(Statamic\\Auth\\File\\User))
#4 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(27): Statamic\\Stache\\Stores\\BasicStore->getPath(Object(Statamic\\Auth\\File\\User))
#5 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Stache/Repositories/UserRepository.php(43): Statamic\\Stache\\Stores\\BasicStore->getItem(Object(Statamic\\Auth\\File\\User))
#6 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\UserRepository->find(Object(Statamic\\Auth\\File\\User))
#7 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Controllers/CP/Users/UsersController.php(150): Illuminate\\Support\\Facades\\Facade::__callStatic('find', Array)
#8 [internal function]: Statamic\\Http\\Controllers\\CP\\Users\\UsersController->edit(Object(Illuminate\\Http\\Request), Object(Statamic\\Auth\\File\\User))
#9 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('edit', Array)
#11 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Users\\UsersController), 'edit')
#12 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#13 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#14 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\StaticCaching\\Middleware\\Retrieve->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/forge/staging.aurorainsight.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/forge/staging.aurorainsight.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/forge/staging.aurorainsight.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /home/forge/staging.aurorainsight.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /home/forge/staging.aurorainsight.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 {main}
"}
```

**Comment by Pfeifakopf** [comment]
I have the same error, when changing the password via cp.

**Comment by jamie-brown** [comment]
I am having the same issue with trying to change a password. It just hangs on 'saving' and I get this in my debugbar:

`[15:14:52] LOG.error: array_key_exists(): The first argument should be either a string or an integer {"userId":"****","exception":{}}`

**Comment by mkoterle** [comment]
It seems like a Statamic issue, I've "fixed" it by changing this file `src/Http/Controllers/CP/Users/PasswordController.php`

comment out line 13
```
// $user = User::find($user);
```

I don't know if in any case this adds problems as I didn't have the time to inspect it further.

**Comment by mikemartin** [comment]
Can confirm that fixed the issues. Has this fix been released yet? I'm on the latest Beta 22 and it doesn't appear to be there.

**Comment by jasonvarga** [comment]
No not yet. We’ll tag a release tomorrow.
