### ISSUE TITLE
Requesting a Password Reset Link is broken

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1587]
**Describe the bug**
When you're on the login screen and request a password reset, Statamic will throw an error. I think it must be looking for a password resets database table or something.

```
[2020-03-31 21:11:40] production.ERROR: Call to a member function table() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function table() on null at /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php:234)
[stacktrace]
#0 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php(160): Illuminate\\Auth\\Passwords\\DatabaseTokenRepository->getTable()
#1 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(59): Illuminate\\Auth\\Passwords\\DatabaseTokenRepository->recentlyCreatedToken()
#2 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php(34): Illuminate\\Auth\\Passwords\\PasswordBroker->sendResetLink()
#3 /home/forge/mccleanpodiatry.co.uk/vendor/statamic/cms/src/Http/Controllers/ForgotPasswordController.php(33): Statamic\\Http\\Controllers\\ForgotPasswordController->traitSendResetLinkEmail()
#4 /home/forge/mccleanpodiatry.co.uk/vendor/statamic/cms/src/Http/Controllers/CP/Auth/ForgotPasswordController.php(21): Statamic\\Http\\Controllers\\ForgotPasswordController->sendResetLinkEmail()
#5 [internal function]: Statamic\\Http\\Controllers\\CP\\Auth\\ForgotPasswordController->sendResetLinkEmail()
#6 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#7 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#8 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#10 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#11 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /home/forge/mccleanpodiatry.co.uk/vendor/statamic/cms/src/Http/Middleware/CP/RedirectIfAuthorized.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\RedirectIfAuthorized->handle()
#14 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#16 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#20 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /home/forge/mccleanpodiatry.co.uk/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\StaticCaching\\Middleware\\Retrieve->handle()
#28 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#30 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#32 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#34 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /home/forge/mccleanpodiatry.co.uk/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#37 /home/forge/mccleanpodiatry.co.uk/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#39 /home/forge/mccleanpodiatry.co.uk/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#41 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#47 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#49 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#51 /home/forge/mccleanpodiatry.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /home/forge/mccleanpodiatry.co.uk/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"} 
```

**To Reproduce**
1. Go to https://yoursite.com/cp
2. Click on 'Forgot Password?'
3. Type in your email address

**Expected behavior**
It should email me a password reset link and return a message saying it has done so.

**Screenshots**
![image](https://user-images.githubusercontent.com/19637309/78076259-f8d52780-739d-11ea-8b12-8d957808c1c6.png)
[See screencast](https://d.pr/free/i/v4CurG)

**Environment (please complete the following information):**
 - Statamic version: `Statamic 3.0.0-beta.22`
 - Install method: `statamic/statamic`
 - PHP version: PHP 7.4.4
 - Operating System: Linux
 - Browser: Google Chrome

**Additional context**
Email is setup for the site (and works) and all users are stored in files

**Comment by jackmcdade** [comment]
Confirmed.
