### ISSUE TITLE
ErrorException: `renderException()` is deprecated

### ISSUE THREAD

**Issue by psren** [statamic/cms#1588]
```
PHP Fatal error:  Uncaught ErrorException: The "Symfony\Component\Console\Application::renderException()" method is deprecated since Symfony 4.4, use "renderThrowable()" instead. i
n C:\Users\HellPat\repo\statamicv3\vendor\symfony\console\Application.php:796
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'The "Symfony\\Co...', 'C:\\Users\\HellPa...', 796, Array)
#1 C:\Users\HellPat\repo\statamicv3\vendor\symfony\console\Application.php(796): trigger_error('The "Symfony\\Co...', 16384)
#2 C:\Users\HellPat\repo\statamicv3\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(507): Symfony\Component\Console\Application->renderException(Object(Er
rorException), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Environment (please complete the following information):**

```json
"statamic/cms": "3.0.*@beta"
```

```json
v3.0.0-beta.22
```

```json
"name": "laravel/framework",
"version": "v6.18.3",
```

**Comment by jasonvarga** [comment]
Please don’t remove parts from the issue template.

How did you run into this error?

**Comment by psren** [comment]
Oh, sorry for that.
I just typed `composer create-project statamic/statamic my-site --prefer-dist --stability=dev` like mentioned in the docs.

**Comment by jasonvarga** [comment]
And what are you doing when you see this error? Is it in the console? In the browser?

**Comment by psren** [comment]
It's in the console, right after typing this command.
Did not do any further action.

I removed parts of the issue template because I first tried to append my `composer.lock` but it was too long.

This is the complete message:

```php
PHP Fatal error:  Uncaught ErrorException: The "Symfony\Component\Console\Application::renderException()" method is deprecated since Symfony 4.4, use "renderThrowable()" instead. i
n C:\Users\HellPat\repo\my-site\vendor\symfony\console\Application.php:796
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'The "Symfony\\Co...', 'C:\\Users\\HellPa...', 796, Array)
#1 C:\Users\HellPat\repo\my-site\vendor\symfony\console\Application.php(796): trigger_error('The "Symfony\\Co...', 16384)
#2 C:\Users\HellPat\repo\my-site\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(507): Symfony\Component\Console\Application->renderException(Object(Error
Exception), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Users\HellPat\repo\my-site\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(112): Illuminate\Foundation\Exceptions\Handler->renderForConsole(
Object(Symfony\Component\Console\Output\ConsoleOutput), Object(ErrorExce in C:\Users\HellPat\repo\my-site\vendor\symfony\console\Application.php on line 796
PHP Fatal error:  Uncaught ErrorException: The "Symfony\Component\Debug\Exception\FatalErrorException" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\Er
ror\FatalError" instead. in C:\Users\HellPat\repo\my-site\vendor\symfony\debug\Exception\FatalErrorException.php:14
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'The "Symfony\\Co...', 'C:\\Users\\HellPa...', 14, Array)
#1 C:\Users\HellPat\repo\my-site\vendor\symfony\debug\Exception\FatalErrorException.php(14): trigger_error('The "Symfony\\Co...', 16384)
#2 C:\Users\HellPat\repo\my-site\vendor\composer\ClassLoader.php(444): include('C:\\Users\\HellPa...')
#3 C:\Users\HellPat\repo\my-site\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\Users\\HellPa...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 C:\Users\HellPat\repo\my-site\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(147): spl_auto in C:\Users\HellPat\repo\my-site\vendor\symfony\de
bug\Exception\FatalErrorException.php on line 14
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

**Comment by psren** [comment]
Ah sorry, this problem was not related with laravel, but with some dependency-problems with an old php-version installed on my system.
