### ISSUE TITLE
Manually registering routes in addon causes composer error

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1758]
## Bug Description

I have this code in my addon's service provider:
```
        $this->registerWebRoutes(function () {
            collect(config('feeds.types', []))->each(function ($feed, $key) {
                Route::get($feed['route'], Str::title($key));
            });
        });
```

When you try to composer install, during the dump-autoload phase you get the following:
```
[2020-04-29 15:59:59] local.ERROR: Call to a member function namespace() on null {"exception":"[object] (Error(code: 0): Call to a member function namespace() on null at /Users/erin/Sites/v3/vendor/statamic/cms/src/Providers/AddonServiceProvider.php:323)
[stacktrace]
#0 /Users/erin/Sites/v3/vendor/statamic/cms/src/Providers/AddonServiceProvider.php(201): Statamic\\Providers\\AddonServiceProvider->namespace()
#1 /Users/erin/Sites/v3/vendor/statamic/cms/src/Statamic.php(97): Statamic\\Providers\\AddonServiceProvider->Statamic\\Providers\\{closure}()
#2 /Users/erin/Sites/v3/vendor/statamic/cms/routes/web.php(43): Statamic\\Statamic::additionalWebRoutes()
#3 /Users/erin/Sites/v3/vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php(35): require('/Users/erin/Sit...')
#4 /Users/erin/Sites/v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(417): Illuminate\\Routing\\RouteFileRegistrar->register('/Users/erin/Sit...')
#5 /Users/erin/Sites/v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(374): Illuminate\\Routing\\Router->loadRoutes('/Users/erin/Sit...')
#6 /Users/erin/Sites/v3/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(134): Illuminate\\Routing\\Router->group(Array, '/Users/erin/Sit...')
#7 /Users/erin/Sites/v3/vendor/statamic/cms/routes/routes.php(30): Illuminate\\Routing\\RouteRegistrar->group('/Users/erin/Sit...')
#8 /Users/erin/Sites/v3/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(81): require('/Users/erin/Sit...')
#9 /Users/erin/Sites/v3/vendor/statamic/cms/src/Providers/AppServiceProvider.php(30): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('/Users/erin/Sit...')
```

## How to Reproduce

With version beta-27, run `composer install edalzell/feeds`.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
I don't think Statamic does detect the namespace automatically.

Personally I had to define my namespace manually in my routes:
https://github.com/jonassiewertsen/statamic-butik/blob/master/routes/web.php#L3

**Comment by edalzell** [comment]
Current workaround:

```
        Statamic::booted(function () {
             $this->registerWebRoutes(function () {
                 collect(config('feeds.types', []))->each(function ($feed, $key) {
                     Route::namespace('\Edalzell\Feeds\Http\Controllers')
                         ->get($feed['route'], Str::title($key));
                 });
```

@jasonvarga is this something that should be updated in core (I can do a PR), or it's as planned (I have a docs PR in the works)?

**Comment by jasonvarga** [comment]
What's the problem?

**Comment by edalzell** [comment]
Like above, I have an Add-on that is alphabetically before Statamic and I'm registering Web routes in my Service Provider.

If I don't do the `booted` bit above, you get the above error during composer's autoload step.

**Comment by edalzell** [comment]
Fixed in docs.
