### ISSUE TITLE
Error choosing a blueprint on a new Form

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1896]
## Bug Description

When creating a form, on the screen after you create the handle I get the spinning wheel.

## How to Reproduce

1. Create a form
2. Give it a handle
3. Click Next
4. Choose a blueprint from existing
5. See spinning wheel

## Extra Detail
```
[2020-06-05 00:04:29] local.ERROR: Trying to access array offset on value of type bool {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type bool at /Users/erin/Sites/addons/vendor/statamic/cms/src/Facades/Endpoint/URL.php:177)
[stacktrace]
#0 /Users/erin/Sites/addons/vendor/statamic/cms/src/Facades/Endpoint/URL.php(177): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', '/Users/erin/Sit...', 177, Array)
#1 /Users/erin/Sites/addons/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Facades\\Endpoint\\URL->makeRelative('http://:/')
#2 /Users/erin/Sites/addons/vendor/statamic/cms/src/Routing/Routable.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic('makeRelative', Array)
#3 /Users/erin/Sites/addons/vendor/statamic/cms/src/Data/AbstractAugmented.php(53): Statamic\\Entries\\Entry->url()
#4 /Users/erin/Sites/addons/vendor/statamic/cms/src/Data/AbstractAugmented.php(36): Statamic\\Data\\AbstractAugmented->get('url')
#5 /Users/erin/Sites/addons/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(16): Statamic\\Data\\AbstractAugmented->select(Array)
#6 /Users/erin/Sites/addons/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(21): Statamic\\Structures\\Page->toAugmentedCollection(NULL)
#7 /Users/erin/Sites/addons/vendor/statamic/cms/src/View/Cascade.php(134): Statamic\\Structures\\Page->toAugmentedArray()
#8 /Users/erin/Sites/addons/vendor/statamic/cms/src/View/Cascade.php(76): Statamic\\View\\Cascade->hydrateContent()
#9 /Users/erin/Sites/addons/vendor/statamic/cms/src/View/View.php(87): Statamic\\View\\Cascade->hydrate()
#10 /Users/erin/Sites/addons/vendor/statamic/cms/src/View/View.php(38): Statamic\\View\\View->cascade()
#11 /Users/erin/Sites/addons/vendor/statamic/cms/src/View/View.php(65): Statamic\\View\\View->gatherData()
#12 /Users/erin/Sites/addons/vendor/statamic/cms/src/Http/Responses/DataResponse.php(144): Statamic\\View\\View->render()
#13 /Users/erin/Sites/addons/vendor/statamic/cms/src/Http/Responses/DataResponse.php(45): Statamic\\Http\\Responses\\DataResponse->contents()
#14 /Users/erin/Sites/addons/vendor/statamic/cms/src/Structures/Page.php(289): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#15 /Users/erin/Sites/addons/vendor/laravel/framework/src/Illuminate/Routing/Router.php(744): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#16 /Users/erin/Sites/addons/vendor/laravel/framework/src/Illuminate/Routing/Router.php(731): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#17 /Users/erin/Sites/addons/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#18 /Users/erin/Sites/addons/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
```

## Environment

**Statamic version:** 3.0.0-beta-29

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Full stack trace please

**Comment by jesseleite** [comment]
> 1. Create a form
> 2. Give it a handle
> 3. Click Next

Can't reproduce any error when doing this on latest beta 🤔

**Comment by edalzell** [comment]
@jesseleite found the step that failed, choosing a blueprint

**Comment by edalzell** [comment]
@jasonvarga added more of the stack

**Comment by Konafets** [comment]
I am able to reproduce this as well.

**Comment by edalzell** [comment]
I think this is related to https://github.com/statamic/cms/issues/1903 and https://github.com/statamic/cms/issues/1914
