### ISSUE TITLE
Addon install results in 500 internal server error

### ISSUE THREAD

**Issue by jreviews** [statamic/cms#2179]
## Bug Description

When installing any addon through CP a dialog appears showing a 500 internal server error occurred while at the same time a green notification states the operation was completed successfully, and the addon is not installed.

## How to Reproduce

Localhost install, go to Addons page, select any addon for installation 

## Extra Detail

![image](https://user-images.githubusercontent.com/31069418/89432373-08c79400-d70f-11ea-9919-9b90e9c9ddb0.png)

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4

**Install method (choose one):**
- Updated from a previous fresh install of a beta from `statamic/statamic`

**Comment by damcclean** [comment]
Is there anything in your log files regarding the error? They're located in `storage/logs`

**Comment by jreviews** [comment]
@damcclean thanks for looking into this. This is what gets added to the log. 

```
[2020-08-16 12:10:05] local.ERROR: Argument 1 passed to Statamic\Extend\AddonInstaller::install() must be of the type string, null given, called in /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261 {"userId":"xxxxxxx-e2fc-49b6-a5cb-xxxxxxxxxx","exception":"[object] (TypeError(code: 0): Argument 1 passed to Statamic\\Extend\\AddonInstaller::install() must be of the type string, null given, called in /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261 at /vendor/statamic/cms/src/Extend/AddonInstaller.php:31)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Extend\\AddonInstaller->install(NULL)
#1 /vendor/statamic/cms/src/Http/Controllers/CP/AddonsController.php(26): Illuminate\\Support\\Facades\\Facade::__callStatic('install', Array)
#2 [internal function]: Statamic\\Http\\Controllers\\CP\\AddonsController->install(Object(Illuminate\\Http\\Request))
#3 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('install', Array)
#5 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\AddonsController), 'install')
#6 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#7 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'configure addon...')
#11 /vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#62 /public/docs/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 {main}
"} 
```

**Comment by jasonvarga** [comment]
Does this still happen for you?

**Comment by jreviews** [comment]
@jasonvarga Yes, same issue on `3.0.0`. I can't install any addons.

**Comment by jreviews** [comment]
Just wanted to add that for me this issue is not limited to addon installations. I also cannot use the CP update feature.

![image](https://user-images.githubusercontent.com/31069418/91316784-3be9ca00-e787-11ea-9cc3-80aec94eed95.png)

The logged error is similar:

> [2020-08-26 14:31:37] local.ERROR: Argument 1 passed to Statamic\Updater\Updater::install() must be of the type string, null given, called in /vendor/statamic/cms/src/Http/Controllers/CP/Updater/UpdateProductController.php on line 70 {"userId":"71e2fc01-e2fc-49b6-a5cb-ad1f5d871ea3","exception":"[object] (TypeError(code: 0): Argument 1 passed to Statamic\\Updater\\Updater::install() must be of the type string, null given, called in /vendor/statamic/cms/src/Http/Controllers/CP/Updater/UpdateProductController.php on line 70 at /vendor/statamic/cms/src/Updater/Updater.php:40)

**Comment by hmalaud** [comment]
Sorry to comment on a closed issue, but I have the same problem for updates. This happens on a web server that used to work. Update through ssh works fine.

**Comment by jasonmckinney66** [comment]
Reporting the same issue. On live server, when performing an update or plugin installation through CP, error is: 
`sh: line 0: exec: : not found`
Local version on MAMP, error is:
`Updater::install() must be of the type string, null given...`

PHP 7.3.24
composer 2.0.8
Updating Statamic to 3.0.36

**Comment by damcclean** [comment]
> Reporting the same issue. On live server, when performing an update or plugin installation through CP, error is:
> `sh: line 0: exec: : not found`
> Local version on MAMP, error is:
> `Updater::install() must be of the type string, null given...`
> 
> PHP 7.3.24
> composer 2.0.8
> Updating Statamic to 3.0.36

Which operating system is your live server?

**Comment by jasonmckinney66** [comment]
Thanks for the quick reply. We are running Apache with an Nginx reverse proxy in front of it.

**Comment by damcclean** [comment]
> Thanks for the quick reply. We are running Apache with an Nginx reverse proxy in front of it.

Are you using Linux, Mac or Windows on that live server?

**Comment by jasonmckinney66** [comment]
Linux. Thanks.

**Comment by jasonvarga** [comment]
This is obviously not a solution but merely a suggestion. You probably don't want to be installing or updating things directly on your production sites.

**Comment by duncanmcclean** [comment]
Hmm, I've just setup a test on a Ubuntu box and it worked fine! Is there any more information you can provide maybe about your setup? Do you have composer on the boxes, if so what version?

**Comment by peterkelm** [comment]
We have the same issue with our hosting environment too. Updating from the cp fails with the same error 500. Fortunately the command line updater via composer worked ok... after adjusting the command line php-cli version to match the version used by the web server. (Before, the web server used 7.3 already but the command line was still on 7.2...)

**Comment by wm-simon** [comment]
> > Reporting the same issue. On live server, when performing an update or plugin installation through CP, error is:
> > `sh: line 0: exec: : not found`
> > Local version on MAMP, error is:
> > `Updater::install() must be of the type string, null given...`
> > PHP 7.3.24
> > composer 2.0.8
> > Updating Statamic to 3.0.36
> 
> Which operating system is your live server?

Same issue here.
Ubuntu
Apache
PHP 7.4
Hosting system is [Plesk](https://www.plesk.com/)
Composer update works without problems.
