### ISSUE TITLE
S3 disk config URL defaulting to amazon URL

### ISSUE THREAD

**Issue by jimmerk** [statamic/cms#2202]
Hi. Trying to get Linode S3 storage working...

I'm using the following in .env:

```
AWS_ACCESS_KEY_ID=(myKey)
AWS_SECRET_ACCESS_KEY=(mySecret)
AWS_DEFAULT_REGION=US
AWS_BUCKET=my-bucket
AWS_URL=http://us-west-6.linodeobjects.com/
```

but I'm getting this error on uploads which shows the Linode URL isn't being used...

```
Error executing "ListObjects" on "https://my-bucket.s3.us.amazonaws.com/?prefix=image.jpg%2F&max-keys=1&encoding-type=url"; AWS HTTP error: cURL error 6: Could not resolve host: my-bucket.s3.us.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

not sure why it's trying to use the aws url.

I have installed the prerequisites mentioned here...https://laravel.com/docs/6.x/filesystem#driver-prerequisites

## Environment

**Statamic version:** 3.0.0.-beta-43
**PHP version:** 7.3.15-3
**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Whats in the yaml file for your container?

**Comment by jimmerk** [comment]
Is this what you're asking about? I'm new to Statamic.

media.yaml
```
title: Media
disk: linodeS3
allow_uploads: true
allow_downloading: true
allow_renaming: true
allow_moving: true
create_folders: true
```

**Comment by jasonvarga** [comment]
Yeah that's it. What about config/filesystems.php?

**Comment by jimmerk** [comment]
I added the linodeS3 object (with the same params as S3)...

```

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application. Just store away!
    |
    */

    'default' => env('FILESYSTEM_DRIVER', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => env('FILESYSTEM_CLOUD', 's3'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "s3", "rackspace"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

	'linodeS3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
	],
        'assets' => [
            'driver' => 'local',
            'root' => public_path('assets'),
            'url' => '/assets',
            'visibility' => 'public',
        ],

    ],

];
```

**Comment by jasonvarga** [comment]
Looks fine - perhaps your config is cached? Does it improve if you run `php artisan cache:clear`?

**Comment by jimmerk** [comment]
I tried `php artisan cache:clear` and clearing browser cache (not that it should help anyway). In my dev environment, I'm running Windows/WSL2/nginx rather than Homestead or Valet (couldn't get this working in WSL2), and the site is being served from nginx. There's no caching (that I'm aware of) being done in nginx. I've disabled caching with this in the server block...

```
        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
```

**Comment by jasonvarga** [comment]
Do you only have one asset container?

**Comment by jimmerk** [comment]
Two. One is local. The other, called "Media", is S3.

**Comment by jimmerk** [comment]
I've also disabled nginx and served this with `php artisan serve`. Still getting the error.

**Comment by jimmerk** [comment]
Wonder if it's permissions related? This is literally my first install, so I wouldn't doubt I've done something wonky.

**Comment by jasonvarga** [comment]
I don't think you've done anything wrong. What you've posted looks fine. What version of Laravel are you running? Run `php artisan -V`

**Comment by jimmerk** [comment]
Laravel Framework 6.18.35

**Comment by jimmerk** [comment]
Would the fact that I'm using guzzle 6.5.5 affect anything? I couldn't get 7.0 to load. That was the only 'tweak' I had to make in the composer config to get Statamic to load.

**Comment by jimmerk** [comment]
Here's the full trace in my laravel.log.

```
[2020-08-11 14:56:48] local.ERROR: Error executing "ListObjects" on "https://my-bucket.s3.us.amazonaws.com/?prefix=&encoding-type=url"; AWS HTTP error: cURL error 6: Could not resolve host: my-bucket.s3.us.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"userId":"(MY_ID)","exception":"[object] (Aws\\S3\\Exception\\S3Exception(code: 0): Error executing \"ListObjects\" on \"https://my-bucket.s3.us.amazonaws.com/?prefix=&encoding-type=url\"; AWS HTTP error: cURL error 6: Could not resolve host: my-bucket.s3.us.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home/jim/sites/s3/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)
#0 /home/jim/sites/s3/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\\Psr7\\Request), Object(Aws\\Command), Array)
#14 /home/jim/sites/s3/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()
#15 /home/jim/sites/s3/vendor/aws/aws-sdk-php/src/ResultPaginator.php(127): Aws\\AwsClient->execute(Object(Aws\\Command))
#16 /home/jim/sites/s3/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(294): Aws\\ResultPaginator->valid()
#17 /home/jim/sites/s3/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(277): League\\Flysystem\\AwsS3v3\\AwsS3Adapter->retrievePaginatedListing(Array)
[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: Could not resolve host: my-bucket.s3.us.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home/jim/sites/s3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200)
#12 /home/jim/sites/s3/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()
#13 /home/jim/sites/s3/vendor/aws/aws-sdk-php/src/ResultPaginator.php(127): Aws\\AwsClient->execute(Object(Aws\\Command))
#14 /home/jim/sites/s3/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(294): Aws\\ResultPaginator->valid()
#15 /home/jim/sites/s3/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(277): League\\Flysystem\\AwsS3v3\\AwsS3Adapter->retrievePaginatedListing(Array)
```

**Comment by jimmerk** [comment]
Thank you for your help Jason. I found a solution. Looks like the driver accepts an "endpoint" value, so this small change to filesystems.php made it work...

Instead of 'url' ...

` 'endpoint' => env('AWS_ENDPOINT'),`

and replaced AWS_URL with AWS_ENDPOINT in .env.
