### ISSUE TITLE
Error creating new entries on Multisite

### ISSUE THREAD

**Issue by tao** [statamic/cms#3031]
## Bug Description
When creating a new entry on a multisite, the entry file is saved correctly but the CMS returns an error.

The error pop-up in the bottom left corner just says "Server Error" while the Javascript console says:

```
// network request
{
    "message": "Server Error"
}

// console
Failed to load resource: the server responded with a status of 500 ()
```

The CMS tries to fetch the url `/cp/collections/news/entries/en` after saving, which doesn't exist. A url that does exist is `/cp/collections/news/entries` and this correctly returns JSON data the frontend is looking for?

## Environment
Statamic 3.0.35 Pro
Laravel 8.19.0
PHP 7.4.12

**Comment by damcclean** [comment]
Is there any more information inside your log file? 'storage/logs'

**Comment by tao** [comment]
Interesting idea, yes there was something:

```
[2020-12-18 07:54:51] local.ERROR: Operations quota exceeded. Change plan to get more Operations. {"userId":"689ae2aa-7236-4264-8ebd-7209424a4863","exception":"[object] (Algolia\\AlgoliaSearch\\Exceptions\\BadRequestException(code: 403): Operations quota exceeded. Change plan to get more Operations. at /Users/daniel/Code/www.statamic/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:219)
[stacktrace]
#0 /Users/daniel/Code/www.statamic/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(167): Algolia\\AlgoliaSearch\\RetryStrategy\\ApiWrapper->handleResponse(Object(GuzzleHttp\\Psr7\\Response), Object(Algolia\\AlgoliaSearch\\Http\\Psr7\\Request))
#1 /Users/daniel/Code/www.statamic/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(87): Algolia\\AlgoliaSearch\\RetryStrategy\\ApiWrapper->request('GET', '/1/indexes/', Object(Algolia\\AlgoliaSearch\\RequestOptions\\RequestOptions), Array, 5)
#2 /Users/daniel/Code/www.statamic/vendor/algolia/algoliasearch-client-php/src/SearchClient.php(200): Algolia\\AlgoliaSearch\\RetryStrategy\\ApiWrapper->read('GET', '/1/indexes/', Object(Algolia\\AlgoliaSearch\\RequestOptions\\RequestOptions))
#3 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Search/Algolia/Index.php(91): Algolia\\AlgoliaSearch\\SearchClient->listIndices()
#4 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Search/UpdateItemIndexes.php(22): Statamic\\Search\\Algolia\\Index->exists()
#5 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Search\\UpdateItemIndexes->Statamic\\Search\\{closure}(Object(Statamic\\Search\\Algolia\\Index), 'content')
#6 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Search/UpdateItemIndexes.php(23): Illuminate\\Support\\Collection->each(Object(Closure))
#7 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(411): Statamic\\Search\\UpdateItemIndexes->update(Object(Statamic\\Events\\EntrySaved))
#8 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(236): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Statamic\\\\Events...', Array)
#9 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(432): Illuminate\\Events\\Dispatcher->dispatch('Statamic\\\\Events...')
#10 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event(Object(Statamic\\Events\\EntrySaved))
#11 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Entries/Entry.php(290): Statamic\\Events\\Event::dispatch(Object(Statamic\\Entries\\Entry))
#12 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(304): Statamic\\Entries\\Entry->save()
#13 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->store(Object(Illuminate\\Http\\Request), Object(Statamic\\Entries\\Collection), Object(Statamic\\Sites\\Site))
#14 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#15 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController), 'store')
#16 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#17 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#18 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/daniel/Code/www.statamic/vendor/statamic/cms/src/Http/Middleware/CP/ControlPanel.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ControlPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/daniel/Code/www.statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
```

That's strange, it might be related? Perhaps Algolia was causing the issue--I'll double check but in that case we might need a better error message here... although I don't see why Algolia should interfere with saving entries.

**Comment by tao** [comment]
Switching to the default search index fixed this error:

```
    'default' => env('STATAMIC_DEFAULT_SEARCH_INDEX', 'default'),

    'indexes' => [
        'default' => [
            'driver' => 'local',
            'searchables' => 'all',
            'fields' => ['title'],
        ],
        
        ...
     ],
```

**Comment by damcclean** [comment]
Looks like you were sending too much information to Algolia (over the allowed usage for your plan) and it threw an exception which caused that server error.
