### ISSUE TITLE
Collection filtering on one taxonomy fails

### ISSUE THREAD

**Issue by FrankPeters** [statamic/cms#3034]
## Bug Description
I have a collection item which shows a list of news articles related to it. This relationship is defined by use of a taxonomy. 

My template:
```
{{ if onderneming }}
    {{ collection
       from="artikelen"
       sort="publish_date:desc"
       :taxonomy:onderneming="onderneming"
       as="articles"
    }}
     Show article here
    {{ /collection }}
{{ /if }}
```

When I load the page I get the following error:
```
TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, Statamic\\Taxonomies\\LocalizedTerm given at /[...]/vendor/statamic/cms/src/Tags/Collection/Entries.php:312
```

I should get three results as there are three articles with this taxonomy.

## How to Reproduce
See bug description

## Extra Detail
```
[stacktrace]
#0 /vendor/statamic/cms/src/Tags/Collection/Entries.php(312): count(Object(Statamic\\Taxonomies\\LocalizedTerm))
#1 /vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Statamic\\Tags\\Collection\\Entries->Statamic\\Tags\\Collection\\{closure}(Object(Statamic\\Taxonomies\\LocalizedTerm), 'taxonomy:ondern...')
#2 /vendor/statamic/cms/src/Tags/Collection/Entries.php(335): Illuminate\\Support\\Collection->each(Object(Closure))
#3 /vendor/statamic/cms/src/Tags/Collection/Entries.php(151): Statamic\\Tags\\Collection\\Entries->queryTaxonomies(Object(Statamic\\Stache\\Query\\EntryQueryBuilder))
#4 /vendor/statamic/cms/src/Tags/Collection/Entries.php(46): Statamic\\Tags\\Collection\\Entries->query()
#5 /vendor/statamic/cms/src/Tags/Collection/Collection.php(37): Statamic\\Tags\\Collection\\Entries->get()
#6 [internal function]: Statamic\\Tags\\Collection\\Collection->index()
```
## Environment

**Statamic version:** 3.0.35

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Migrated from v2

**Comment by jasonvarga** [comment]
Thanks!

**Comment by 1stevengrant** [comment]
I've had to work around this by creating a query scope

```
{{ collection:posts
        query_scope="category"
        category="news"
        limit="10"
        paginate="true"
        as="posts"
      }}
```

with 

```php
<?php

namespace App\Scopes;

use Statamic\Query\Scopes\Scope;

class Category extends Scope
{
    public function apply($query, $values)
    {
        $query->where('category', $values['category']);
    }
}
```

rather than doing

```
{{ collection:posts taxonomy:category="news" limit="10" paginate="true" as="posts" }}
```
