### ISSUE TITLE
Error upgrading to v3.0.37

### ISSUE THREAD

**Issue by DrTrills** [statamic/cms#3079]
## Bug Description
on my local machine I used the CP updater. It hung on the CP update screen. After a while I refreshed the page and got errors

## How to Reproduce
Update via CP
## Environment
`php please support:details`

```
Warning: require(/Users/user/laravel/maxima/vendor/composer/../statamic/cms/src/helpers.php): Failed to open stream: No such file or directory in /Users/user/laravel/maxima/vendor/composer/autoload_real.php on line 71

Fatal error: Uncaught Error: Failed opening required '/Users/user/laravel/maxima/vendor/composer/../statamic/cms/src/helpers.php' (include_path='.:/usr/local/Cellar/php/8.0.0_1/share/php/pear') in /Users/user/laravel/maxima/vendor/composer/autoload_real.php:71
Stack trace:
#0 /Users/user/laravel/maxima/vendor/composer/autoload_real.php(61): composerRequirea230c71f6de14cafd213e7b8949a0bec('8e144857f0908e7...', '/Users/patrickj...')
#1 /Users/user/laravel/maxima/vendor/autoload.php(7): ComposerAutoloaderInita230c71f6de14cafd213e7b8949a0bec::getLoader()
#2 /Users/user/laravel/maxima/please(18): require('/Users/patrickj...')
#3 {main}
  thrown in /Users/user/laravel/maxima/vendor/composer/autoload_real.php on line 71
<!-- You can copy/paste the output of `php please support:details` here -->
```

**Statamic version:** 3.0.{?}

**PHP version:** 7.{?}
8.0
**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Try deleting the `vendor` directory and running `composer install`. Does it come back to life?

**Comment by DrTrills** [comment]
@jasonvarga You are good! worked like a charm! Thanks

**Comment by vmitchell85** [comment]
I just had a similar issue and removing the `vendor` folder and running `composer install` got me back to 3.0.36

```
Warning: require(/home/forge/redacted/vendor/composer/../symfony/polyfill-php80/bootstrap.php): failed to open stream: No such file or directory in /home/forge/redacted/vendor/composer/autoload_real.php on line 71

Fatal error: require(): Failed opening required '/home/forge/redacted/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/usr/share/php') in /home/forge/redacted/vendor/composer/autoload_real.php on line 71
```

**Comment by vmitchell85** [comment]
Okay... tried it on the command line and got a different message:

Basically composer is hitting up against GitHub's API limit so you need to provide it a token. If you just go to the URL it provides you can put in a token and all is well.

Would be nice if Statamic detected and showed that error.

```
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/industrious-agency/statamic-svg. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.

Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+redacted+2021-01-08+0458
to retrieve a token. It will be stored in "/home/forge/.config/composer/auth.json" for future use by Composer.
Token (hidden):
```
