### ISSUE TITLE
Class 'Facades\Statamic\Marketplace\Marketplace' not found

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3187]
## Bug Description

In laravel.log, I found this error that randomly appears so I can not reproduce it easily. I also get the notification/banner that Statamic couldn't phone home. Maybe related?

```
[2021-02-02 19:46:52] local.ERROR: Class 'Facades\Statamic\Marketplace\Marketplace' not found {"userId":"02cf3ae8-1f9a-43fc-b9fc-5f4d79e60167","exception":"[object] (Error(code: 0): Class 'Facades\\Statamic\\Marketplace\\Marketplace' not found at /home/vagrant/dev-project/vendor/statamic/cms/src/Updater/UpdatesOverview.php:100)
[stacktrace]
#0 /home/vagrant/dev-project/vendor/statamic/cms/src/Updater/UpdatesOverview.php(76): Statamic\\Updater\\UpdatesOverview->checkForStatamicUpdates()
#1 /home/vagrant/dev-project/vendor/statamic/cms/src/Updater/UpdatesOverview.php(61): Statamic\\Updater\\UpdatesOverview->checkAndCache()
#2 /home/vagrant/dev-project/vendor/statamic/cms/src/Updater/UpdatesOverview.php(26): Statamic\\Updater\\UpdatesOverview->getCached()
#3 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Updater\\UpdatesOverview->count()
#4 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Controllers/CP/Updater/UpdaterController.php(43): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Updater\\UpdaterController->count()
#6 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#9 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#10 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#13 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#15 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#17 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#19 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/CP/ControlPanel.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ControlPanel->handle()
#21 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#27 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#29 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#30 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#36 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then()
#38 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute()
#40 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#42 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#45 /home/vagrant/dev-project/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#47 /home/vagrant/dev-project/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#49 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#51 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#55 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#57 /home/vagrant/dev-project/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#59 /home/vagrant/dev-project/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#61 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#63 /home/vagrant/dev-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#64 /home/vagrant/dev-project/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#65 {main}
"} 
```

## Environment
Statamic 3.0.40 Solo
Laravel 8.21.0
PHP 7.4.11

**Comment by damcclean** [comment]
It'll probably be related to that issue, yeah.

Does this file exist for you? `vendor/statamic/cms/src/Marketplace/Marketplace.php`

**Comment by felixstoessel** [comment]
Yeah, exists and here is the content:

```
<?php

namespace Statamic\Marketplace;

use Facades\Statamic\Marketplace\Client;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Support\Facades\Cache;
use Statamic\Facades\Addon;
use Statamic\Marketplace\Addon as AddonProduct;
use Statamic\Statamic;

class Marketplace
{
    public function package($package, $version = null)
    {
        $uri = "packages/$package/$version";

        return Cache::rememberWithExpiration("marketplace-$uri", function () use ($uri) {
            try {
                return [60 => Client::get($uri)['data']];
            } catch (RequestException $e) {
                return [5 => null];
            }
        });
    }

    public function releases($package)
    {
        $uri = "packages/$package/releases";

        return Cache::rememberWithExpiration("marketplace-$uri", function () use ($uri) {
            try {
                return [60 => collect(Client::get($uri)['data'])];
            } catch (RequestException $e) {
                return [5 => collect()];
            }
        });
    }

    public function product($slug)
    {
        if ($slug === Statamic::CORE_SLUG) {
            return $this->statamic();
        }

        $addon = Addon::all()->first(function ($addon) use ($slug) {
            return $addon->slug() === $slug;
        });

        if ($addon) {
            return new AddonProduct($addon);
        }
    }

    public function statamic()
    {
        return new Core;
    }
}
```

**Comment by damcclean** [comment]
Okay cool! Sounds like it could be something to do with [real-time facades](https://laravel.com/docs/8.x/facades#real-time-facades) not working properly. 🤔

I'm guessing running `composer dump-autoload` doesn't help?

**Comment by felixstoessel** [comment]
Nope, does not help.

**Comment by duncanmcclean** [comment]
Could you try deleting all of the files in `storage/framework/cache`, apart from the `.gitignore` file and let me know if that rectifies the problem?

That seemed to resolve a similar issue someone had a couple of months ago, #2917.

**Comment by jackmcdade** [comment]
Haven't heard back in a month — will close this one for now. Feel free to comment/reopen if you still have the issue and @duncanmcclean's suggestion didn't work for you!
