### ISSUE TITLE
Call to a member function routeData() on null

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#3418]
## Bug Description

I've updated one of my sites to Statamic 3.1. However, when I go to the Nav in the CP or I goto a page with a custom route/controller (which returns a Statamic `View`), I get this exception:

```
[2021-03-24 17:15:59] local.ERROR: Call to a member function routeData() on null at /Users/duncan/Sites/sc-docs/resources/views/layout.antlers.html:0)
[stacktrace]
#0 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Structures/Page.php(305): ()
#1 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Routing/UrlBuilder.php(79): Statamic\\Structures\\Page->routeData()
#2 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Routing/UrlBuilder.php(51): Statamic\\Routing\\UrlBuilder->routeData()
#3 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Structures/Page.php(182): Statamic\\Routing\\UrlBuilder->build('{{ parent_uri }...')
#4 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Structures/Page.php(177): Statamic\\Structures\\Page->uri()
#5 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Support/Optional.php(128): Statamic\\Structures\\Page->uri()
#6 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Structures/CollectionStructure.php(38): Illuminate\\Support\\Optional->__call('uri', Array)
#7 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Entries/Entry.php(661): Statamic\\Structures\\CollectionStructure->entryUri(Object(Statamic\\Entries\\Entry))
#8 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Routing/Routable.php(50): Statamic\\Entries\\Entry->uri()
#9 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Data/AbstractAugmented.php(53): Statamic\\Entries\\Entry->absoluteUrl()
#10 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Entries/AugmentedEntry.php(60): Statamic\\Data\\AbstractAugmented->get('absolute_url')
#11 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Data/AbstractAugmented.php(49): Statamic\\Entries\\AugmentedEntry->permalink()
#12 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Data/AbstractAugmented.php(36): Statamic\\Data\\AbstractAugmented->get('permalink')
#13 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(16): Statamic\\Data\\AbstractAugmented->select(Array)
#14 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(21): Statamic\\Structures\\Page->toAugmentedCollection(NULL)
#15 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Structure.php(50): Statamic\\Structures\\Page->toAugmentedArray()
#16 [internal function]: Statamic\\Tags\\Structure->Statamic\\Tags\\{closure}(Array, 0)
#17 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map(Object(Closure), Array, Array)
#18 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Structure.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#19 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Structure.php(51): Statamic\\Tags\\Structure->toArray(Array, Array, 2)
#20 [internal function]: Statamic\\Tags\\Structure->Statamic\\Tags\\{closure}(Array, 6)
#21 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map(Object(Closure), Array, Array)
#22 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Structure.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#23 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Structure.php(43): Statamic\\Tags\\Structure->toArray(Array)
#24 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Structure.php(21): Statamic\\Tags\\Structure->structure('pages')
#25 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Tags/Tags.php(131): Statamic\\Tags\\Structure->wildcard('pages')
#26 [internal function]: Statamic\\Tags\\Tags->__call('pages', Array)
#27 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#28 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'nav', Array, '\
              ...', Array)
#29 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/View/Antlers/Parser.php(576): call_user_func_array(Array, Array)
#30 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<!DOCTYPE html>...', Array)
#31 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<!DOCTYPE html>...', Array)
#32 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView('/Users/duncan/S...', '<!DOCTYPE html>...', Array)
#33 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/duncan/S...', Array)
#34 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#35 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#36 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/View/View.php(82): Illuminate\\View\\View->render()
#37 /Users/duncan/Sites/sc-docs/app/Http/Controllers/ChangelogController.php(55): Statamic\\View\\View->render()
#38 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\ChangelogController->show(Object(Illuminate\\Http\\Request))
#39 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#40 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ChangelogController), 'show')
#41 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#42 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Routing\\Route->run()
#43 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#47 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#48 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#49 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#50 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/duncan/Sites/sc-docs/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/duncan/Sites/sc-docs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/duncan/Sites/sc-docs/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/duncan/Sites/sc-docs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#73 /Users/duncan/Sites/sc-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#74 /Users/duncan/Sites/sc-docs/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#75 /Users/duncan/.composer/vendor/laravel/valet/server.php(219): require('/Users/duncan/S...')
#76 {main}
```

I've managed to track the issues down to two specific entries in my tree. I've commented them out for now, [see commit](https://github.com/doublethreedigital/sc-docs.doublethree.digital/commit/7e8a9034b0666695dc2fa43fc3592f4d30701d83).

And here are files for the two entries:

* [3cbcad0c-d018-4bc6-95da-d4bf72428858](https://github.com/doublethreedigital/sc-docs.doublethree.digital/blob/master/content/collections/pages/v2.2/version-control-strategies.md)
* [c008b020-67fd-4f23-82c3-bb01e7b13b96](https://github.com/doublethreedigital/sc-docs.doublethree.digital/blob/master/content/collections/pages/v2.2/extending.md)

## How to Reproduce

1. Clone the repo `doublethreedigital/sc-docs.doublethree.digital`
2. Uncomment the lines mentioned above in the navigation tree
3. Go to `/v2.2/changelog`
4. See exception
5. Comment the lines back in
6. Reload `/v2.2/changelog`
7. The exception has gone

## Environment

```
Statamic 3.1.0-beta.3 Pro
Laravel 8.34.0
PHP 7.4.15
No addons installed
```

**Comment by duncanmcclean** [comment]
Upgraded to Statamic 3.1.2 but still an issue. I tried to figure it out but I'm not entirely sure where the `entry` is being set/not-set.

**Comment by duncanmcclean** [comment]
Closing as I've not run into this issue again and have moved past it.
