### ISSUE TITLE
Can't view users in CP

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3508]
## Bug Description
I get a `Call to undefined method Statamic\Auth\File\User::collectionHandle()` error when trying to look at the users in the CP.

## How to Reproduce
Just navigate to the users in the CP.

## Extra Detail
<img width="1594" alt="Bildschirmfoto 2021-04-09 um 2 46 32 PM" src="https://user-images.githubusercontent.com/23167701/114181909-61a49780-9942-11eb-8033-4f75dc382b64.png">

## Environment
Statamic 3.1.5 Pro
Laravel 8.36.2
PHP 7.4.16
jonassiewertsen/statamic-livewire 2.5.0

**Comment by duncanmcclean** [comment]
I'm unable to reproduce this. Would you be able to provide the full stack trace? Thanks.

**Comment by aerni** [comment]
Here you go:

```log
[2021-04-09 12:56:23] local.ERROR: Call to undefined method Statamic\Auth\File\User::collectionHandle() {"userId":"d66657ba-0b95-4005-91be-52d15a0bb36a","exception":"[object] (Error(code: 0): Call to undefined method Statamic\\Auth\\File\\User::collectionHandle() at /Users/michael/Code/siloam-crowdfunding/app/Actions/Statamic/ExportOrders.php:30)
[stacktrace]
#0 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): App\\Actions\\Statamic\\ExportOrders->visibleTo(Object(Statamic\\Auth\\File\\User))
#1 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(App\\Actions\\Statamic\\ExportOrders), 7)
#2 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(664): array_filter(Array, Object(Closure), 1)
#3 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(344): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#4 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->filter(Object(Closure))
#5 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Actions/ActionRepository.php(27): Illuminate\\Support\\HigherOrderCollectionProxy->__call('visibleTo', Array)
#6 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Actions\\ActionRepository->for(Object(Statamic\\Auth\\File\\User))
#7 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Resources/CP/Users/ListedUser.php(40): Illuminate\\Support\\Facades\\Facade::__callStatic('for', Array)
#8 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): Statamic\\Http\\Resources\\CP\\Users\\ListedUser->toArray(Object(Illuminate\\Http\\Request))
#9 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(231): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#10 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(846): Illuminate\\Http\\Resources\\Json\\JsonResource->jsonSerialize()
#11 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}(Object(Statamic\\Http\\Resources\\CP\\Users\\ListedUser))
#12 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(854): array_map(Object(Closure), Array)
#13 [internal function]: Illuminate\\Support\\Collection->jsonSerialize()
#14 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(71): json_encode(Array, 0)
#15 /Users/michael/Code/siloam-crowdfunding/vendor/symfony/http-foundation/JsonResponse.php(54): Illuminate\\Http\\JsonResponse->setData(Array)
#16 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array)
#17 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(99): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)
#18 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(26): Illuminate\\Routing\\ResponseFactory->json(Array, 200)
#19 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(132): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#20 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(112): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse(Object(Illuminate\\Http\\Request))
#21 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(774): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#22 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(761): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Users\\Users))
#23 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Users\\Users))
#24 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#43 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#53 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#54 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#55 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#56 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/michael/Code/siloam-crowdfunding/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/michael/Code/siloam-crowdfunding/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/michael/Code/siloam-crowdfunding/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/michael/Code/siloam-crowdfunding/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#81 /Users/michael/Code/siloam-crowdfunding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#82 /Users/michael/Code/siloam-crowdfunding/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#83 /Users/michael/.composer/vendor/laravel/valet/server.php(219): require('/Users/michael/...')
#84 {main}
"} 

```

**Comment by aerni** [comment]
Hmm, it looks like it's a problem with an Action. Have to dig deeper.

**Comment by aerni** [comment]
Ah ok. I've got this in one of my Actions, which causes issues on the users in the CP.

```php
public function visibleTo($item): bool
{
    return $item->collectionHandle() === 'orders';
}
```

**Comment by aerni** [comment]
Ok, I fixed it. Had to check for an entry first.

```php
public function visibleTo($item): bool
{
    return $item instanceof Entry
        && $item->collectionHandle() === 'orders';
}
```

**Comment by duncanmcclean** [comment]
Ah, that'll be it! Actions are visible everywhere.
