### ISSUE TITLE
Error when deleting entries (call to a member function routeData() on null)

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#3600]
## Bug Description
When deleting an entry in a collection, the error "call to a member function routeData() on null" is shown (see screenshot bellow). When reloading the page, the entry is gone.

I found out, that this only happens, when the collection is configured to have a Max Depth of 1.

Edit: I just had this same error on two collections that had no Max Depth. So it might be even more complicated to track down. But you can still reproduce the error as explained below.

## How to Reproduce
1. Install Statamic
2. Log into the CP
3. Go to "Collections" -> "Pages", click on the menu icon and choose "edit collection"
4. Set a value of `1` for "Max Depth" and save
5. Add an entry and then delete that entry -> error message appears

## Extra Detail
<img width="901" alt="grafik" src="https://user-images.githubusercontent.com/8578668/116265352-57283180-a77b-11eb-9ec7-58b690dbaf4d.png">

## Environment

**Statamic version:** 3.1.10

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Related to #3418.

**Comment by FlorianMoser** [comment]
@duncanmcclean I also checked your issue before. Not sure it is related. Your tree is not limited to one level.

But it seems the error appears, when there are no entries in a tree yaml file.

**Comment by duncanmcclean** [comment]
Sorry, updated it to 'Possibly related'. Just in case the exception is thrown from the same code or something but has a different cause.

Would you be able to provide the stack trace for the error? You should be able to get it from your `storage/logs/laravel.log` file. Thanks!

**Comment by FlorianMoser** [comment]
Here's the stack trace:

```
[2021-04-28 15:33:20] local.ERROR: Call to a member function routeData() on null {"userId":"94dabf85-b85b-49f4-a336-5e106f2d2405","exception":"[object] (Error(code: 0): Call to a member function routeData() on null at /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Structures/Page.php:302)
[stacktrace]
#0 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Routing/UrlBuilder.php(79): Statamic\\Structures\\Page->routeData()
#1 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Routing/UrlBuilder.php(51): Statamic\\Routing\\UrlBuilder->routeData()
#2 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Structures/Page.php(181): Statamic\\Routing\\UrlBuilder->build('{{ parent_uri }...')
#3 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Support/Optional.php(128): Statamic\\Structures\\Page->uri()
#4 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Structures/CollectionStructure.php(38): Illuminate\\Support\\Optional->__call('uri', Array)
#5 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Entries/Entry.php(672): Statamic\\Structures\\CollectionStructure->entryUri(Object(Statamic\\Entries\\Entry))
#6 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Routing/Routable.php(60): Statamic\\Entries\\Entry->uri()
#7 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Routing/Routable.php(44): Statamic\\Entries\\Entry->absoluteUrlWithoutRedirect()
#8 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Routing/Routable.php(39): Statamic\\Entries\\Entry->urlWithoutRedirect()
#9 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/StaticCaching/DefaultInvalidator.php(41): Statamic\\Entries\\Entry->url()
#10 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/StaticCaching/DefaultInvalidator.php(29): Statamic\\StaticCaching\\DefaultInvalidator->invalidateEntryUrls(Object(Statamic\\Entries\\Entry))
#11 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/StaticCaching/Invalidate.php(44): Statamic\\StaticCaching\\DefaultInvalidator->invalidate(Object(Statamic\\Entries\\Entry))
#12 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): Statamic\\StaticCaching\\Invalidate->invalidateEntry(Object(Statamic\\Events\\EntryDeleted))
#13 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle(Object(Illuminate\\Foundation\\Application))
#14 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#19 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#20 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#21 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(118): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Events\\CallQueuedListener), false)
#23 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#24 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#25 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Illuminate\\Events\\CallQueuedListener))
#27 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#28 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#29 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Events\\CallQueuedListener), '', NULL)
#30 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(562): Illuminate\\Queue\\Queue->pushOn(NULL, Object(Illuminate\\Events\\CallQueuedListener))
#31 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(486): Illuminate\\Events\\Dispatcher->queueHandler('Statamic\\\\Static...', 'invalidateEntry', Array)
#32 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(Statamic\\Events\\EntryDeleted))
#33 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Statamic\\\\Events...', Array)
#34 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch('Statamic\\\\Events...')
#35 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event(Object(Statamic\\Events\\EntryDeleted))
#36 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Entries/Entry.php(174): Statamic\\Events\\Event::dispatch(Object(Statamic\\Entries\\Entry))
#37 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Statamic\\Entries\\Entry->delete()
#38 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Statamic\\Entries\\Entry), 0)
#39 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->each(Object(Closure))
#40 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Actions/Delete.php(54): Illuminate\\Support\\HigherOrderCollectionProxy->__call('delete', Array)
#41 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Controllers/CP/ActionController.php(36): Statamic\\Actions\\Delete->run(Object(Illuminate\\Support\\Collection), Array)
#42 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\ActionController->run(Object(Illuminate\\Http\\Request), Object(Statamic\\Entries\\Collection))
#43 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('run', Array)
#44 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Collections\\EntryActionController), 'run')
#45 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#46 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#47 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#66 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#75 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#76 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#77 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#78 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#79 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/florian/Workspace/aaa/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/florian/Workspace/aaa/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /Users/florian/Workspace/aaa/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#102 /Users/florian/Workspace/aaa/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#103 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#106 /Users/florian/Workspace/aaa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#107 /Users/florian/Workspace/aaa/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#108 /Users/florian/.composer/vendor/laravel/valet/server.php(219): require('/Users/florian/...')
#109 {main}
"}
```

**Comment by duncanmcclean** [comment]
Yeah, I think it's caused from the same place as the other issue. The first 10 lines or so of the stack trace are pretty much the same (bar the line numbers, they're slightly different, likely due to updates between this issue and that issue).

I believe it happens when it attempts to get the `uri` of an entry but it seems to fail. I tried to dig in when I ran into the issue but I couldn't figure it out.

```
[2021-04-28 15:33:20] local.ERROR: Call to a member function routeData() on null {"userId":"94dabf85-b85b-49f4-a336-5e106f2d2405","exception":"[object] (Error(code: 0): Call to a member function routeData() on null at .../vendor/statamic/cms/src/Structures/Page.php:302)
[stacktrace]
#0 .../vendor/statamic/cms/src/Routing/UrlBuilder.php(79): Statamic\\Structures\\Page->routeData()
#1 .../vendor/statamic/cms/src/Routing/UrlBuilder.php(51): Statamic\\Routing\\UrlBuilder->routeData()
#2 .../vendor/statamic/cms/src/Structures/Page.php(181): Statamic\\Routing\\UrlBuilder->build('{{ parent_uri }...')
#3 .../vendor/laravel/framework/src/Illuminate/Support/Optional.php(128): Statamic\\Structures\\Page->uri()
#4 .../vendor/statamic/cms/src/Structures/CollectionStructure.php(38): Illuminate\\Support\\Optional->__call('uri', Array)
#5 .../vendor/statamic/cms/src/Entries/Entry.php(672): Statamic\\Structures\\CollectionStructure->entryUri(Object(Statamic\\Entries\\Entry))
#6 .../vendor/statamic/cms/src/Routing/Routable.php(60): Statamic\\Entries\\Entry->uri()
#7 .../vendor/statamic/cms/src/Routing/Routable.php(44): Statamic\\Entries\\Entry->absoluteUrlWithoutRedirect()
```

**Comment by FlorianMoser** [comment]
I think I found what causes the issue:

When Max Depth is set to 1 and you create a new entry, Statamic doesn't create an entry in `/content/trees/collections/pages.yaml`. Then, when you delete that entry, an error is thrown. You can try this:

1. Create a new Statamic installation
2. Add a pages entry -> a new entry is created in `/content/trees/collections/pages.yaml`
3. Edit the pages collection and set Max Depth to `1`
4. Again, create a new pages entry -> no entry is created in `/content/trees/collections/pages.yaml`
5. Now delete the two pages, one after the other. The one with an entry in the trees gets deleted without problems. The other one throws the `Call to a member function routeData() on null` error

So the issue seems to appear when you handle entries that have no entry in the trees yaml file. Maybe you can confirm this, @duncanmcclean
