### ISSUE TITLE
`Undefined array key 1` with taxonomy terms

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#3739]
## Bug Description

I add a new term to an entry then on save I get an error saying `Undefined array key 1`. See video:

https://user-images.githubusercontent.com/3776888/118814597-39e11180-b8a8-11eb-9106-7e2f4e19487a.mp4

## How to Reproduce

I have created a repo to clone here: https://github.com/johncarter-/statamic-term-stache-issue

Basically:
 - Create a collection called "Products"
 - Create taxonomies "Categories" and/or "Tags"
 - Assign those taxonomies to the Products collection
 - Go to create a new Products entry
 - Add a new term via the entry sidebar taxonomies dropdown
 - Save the entry

## Extra Detail

https://flareapp.io/share/W7zlB88m

## Environment

Statamic 3.1.14 Solo
Laravel 8.42.0
PHP 8.0.0
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- ~Starter kit~
- ~Existing Laravel app~
- ~Other (please explain this magic!)~

**Comment by edalzell** [comment]
I am getting as well. Stack trace when visiting the front end:

```
[2021-05-19 18:32:44] local.ERROR: Undefined offset: 1 {"userId":"cba0aed3-26f9-4ca9-a67f-8261a605d37b","exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php:83)
[stacktrace]
#0 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(83): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/Users/erin/Sit...', 83, Array)
#1 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/AggregateStore.php(65): Statamic\\Stache\\Stores\\TaxonomyTermsStore->getItem('ar::water')
#2 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/AggregateStore.php(57): Statamic\\Stache\\Stores\\AggregateStore->getItem('programs::ar::w...')
#3 [internal function]: Statamic\\Stache\\Stores\\AggregateStore->Statamic\\Stache\\Stores\\{closure}('programs::ar::w...', 0)
#4 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#5 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/AggregateStore.php(58): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Query/Builder.php(104): Statamic\\Stache\\Stores\\AggregateStore->getItems(Object(Illuminate\\Support\\Collection))
#7 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Query/Builder.php(32): Statamic\\Stache\\Query\\Builder->getItems(Object(Illuminate\\Support\\Collection))
#8 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Query/TermQueryBuilder.php(135): Statamic\\Stache\\Query\\Builder->get(Array)
#9 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Query/Builder.php(139): Statamic\\Stache\\Query\\TermQueryBuilder->get()
#10 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Repositories/TermRepository.php(42): Statamic\\Query\\Builder->first()
#11 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\TermRepository->find('programs::water')
#12 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Fieldtypes/Terms.php(210): Illuminate\\Support\\Facades\\Facade::__callStatic('find', Array)
#13 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Fieldtypes/Relationship.php(211): Statamic\\Fieldtypes\\Terms->toItemArray('programs::water')
#14 [internal function]: Statamic\\Fieldtypes\\Relationship->Statamic\\Fieldtypes\\{closure}('programs::water', 0)
#15 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#16 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Fieldtypes/Relationship.php(212): Illuminate\\Support\\Collection->map(Object(Closure))
#17 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Fieldtypes/Relationship.php(111): Statamic\\Fieldtypes\\Relationship->getItemData(Array)
#18 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Fields/Field.php(322): Statamic\\Fieldtypes\\Relationship->preload()
```

Stack trace when visiting the CP:

```
[2021-05-19 18:38:13] local.ERROR: Undefined offset: 1 {"userId":"cba0aed3-26f9-4ca9-a67f-8261a605d37b","exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php:83)
[stacktrace]
#0 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(83): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/Users/erin/Sit...', 83, Array)
#1 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(160): Statamic\\Stache\\Stores\\TaxonomyTermsStore->getItem('ar::water')
#2 [internal function]: Statamic\\Stache\\Stores\\TaxonomyTermsStore->Statamic\\Stache\\Stores\\{closure}('ar::water', 0)
#3 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#4 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(161): Illuminate\\Support\\Collection->map(Object(Closure))
#5 [internal function]: Statamic\\Stache\\Stores\\TaxonomyTermsStore->Statamic\\Stache\\Stores\\{closure}(1614826730, '/Users/erin/Sit...')
#6 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#7 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(343): Illuminate\\Support\\Collection->map(Object(Closure))
#8 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(162): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#9 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Indexes/Value.php(11): Statamic\\Stache\\Stores\\TaxonomyTermsStore->getItemsFromFiles()
#10 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Indexes/Terms/Value.php(23): Statamic\\Stache\\Indexes\\Value->getItems()
#11 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Indexes/Index.php(90): Statamic\\Stache\\Indexes\\Terms\\Value->getItems()
#12 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Indexes/Index.php(74): Statamic\\Stache\\Indexes\\Index->update()
#13 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/Store.php(44): Statamic\\Stache\\Indexes\\Index->load()
#14 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Query/TermQueryBuilder.php(73): Statamic\\Stache\\Stores\\Store->index('title')
#15 [internal function]: Statamic\\Stache\\Query\\TermQueryBuilder->Statamic\\Stache\\Query\\{closure}('programs', 0)
```

We have a multi-site (`default`, `ar`), w/ 2 languages. Term is defined: 
<img width="232" alt="CleanShot 2021-05-19 at 11 46 42@2x" src="https://user-images.githubusercontent.com/6069653/118867420-ebc41200-b897-11eb-8781-1870b1f75493.png">

Each entry has this in it:

```yaml
            filter_by:
              - 'programs::water'
```

Template code that triggers it:

```
{{ collection :from="collection" :limit="limit" :paginate="paginate" :taxonomy="filter_by" as="articles" }}
```

To get the error to occur I do:

```
art cache:clear
plz stache:warm
plz static:clear
```

To make it work I need to do a `stache:clear`. Then when I revisit either the page or the CP, it all works fine.
