### ISSUE TITLE
Locales in 3.1.15

### ISSUE THREAD

**Issue by vlasscontreras** [statamic/cms#3752]
## Bug Description

Started after upgrading to `3.1.15` (and continues in `3.1.16`). It happens when you use `{{ locales }}` in a custom route (defined with `Route::statamic()`). Potentially related to #3689.

## How to Reproduce

1. Create a custom route (for example `Route::statamic('test', 'home')` in a fresh install, though also happens in existing apps)
2. Use the `{{ locales }}` tag pair in the template

## Extra Detail

Stacktrace:

```
Facade\Ignition\Exceptions\ViewException: Argument 1 passed to Statamic\Assets\AssetRepository::find() must be of the type string, null given, called in /test/vendor/statamic/cms/src/Data/DataRepository.php on line 45 in file /test/resources/views/home.antlers.html on line 0

#0 /test/vendor/statamic/cms/src/Assets/AssetRepository.php(33): ()
#1 /test/vendor/statamic/cms/src/Data/DataRepository.php(45): Statamic\Assets\AssetRepository-&gt;find(NULL)
#2 /test/vendor/statamic/cms/src/Data/DataRepository.php(23): Statamic\Data\DataRepository-&gt;attemptAllRepositories('find', NULL)
#3 /test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\Data\DataRepository-&gt;find(NULL)
#4 /test/vendor/statamic/cms/src/Tags/Locales.php(146): Illuminate\Support\Facades\Facade::__callStatic('find', Array)
#5 /test/vendor/statamic/cms/src/Tags/Locales.php(22): Statamic\Tags\Locales-&gt;getData()
#6 [internal function]: Statamic\Tags\Locales-&gt;index()
#7 /test/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#8 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'locales', Array, '\n{{ handle }}\n', Array)
#9 /test/vendor/statamic/cms/src/View/Antlers/Parser.php(576): call_user_func_array(Array, Array)
#10 /test/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\View\Antlers\Parser-&gt;parseCallbackTags('&lt;div class=&quot;pb-...', Array)
#11 /test/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\View\Antlers\Parser-&gt;parse('&lt;div class=&quot;pb-...', Array)
#12 /test/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\View\Antlers\Parser-&gt;parseView('/Users/vladimir...', '&lt;div class=&quot;pb-...', Array)
#13 /test/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\View\Antlers\Engine-&gt;get('/Users/vladimir...', Array)
#14 /test/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View-&gt;getContents()
#15 /test/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View-&gt;renderContents()
#16 /test/vendor/statamic/cms/src/View/View.php(77): Illuminate\View\View-&gt;render()
#17 /test/vendor/statamic/cms/src/Http/Controllers/FrontendController.php(67): Statamic\View\View-&gt;render()
#18 /test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\Http\Controllers\FrontendController-&gt;route(Object(Illuminate\Http\Request), 'home', Array)
#19 /test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('route', Array)
#20 /test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(Statamic\Http\Controllers\FrontendController), 'route')
#21 /test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route-&gt;runController()
#22 /test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Route-&gt;run()
#23 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /test/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\StaticCaching\Middleware\Cache-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /test/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\AuthGuard-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /test/vendor/statamic/cms/src/Http/Middleware/Localize.php(22): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\Localize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /test/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\StacheLock-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#40 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#47 /test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#48 /test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#49 /test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#50 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#51 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#52 /test/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\DisableFloc-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /test/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\CheckMultisite-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /test/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\CheckComposerJsonScripts-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /test/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\Http\Middleware\PoweredByHeader-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /test/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /test/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /test/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#78 /test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#79 /test/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#80 /test/server.php(21): require_once('/Users/vladimir...')
#81 {main}
```

## Environment

**Statamic version:** `3.1.15` and `3.1.16`

**PHP version:** `7.4.16`

**Install method (choose one):**
- Existing Laravel app & fresh install

**Comment by duncanmcclean** [comment]
Add the Localize middleware to your route and the locales tag should work:

https://github.com/statamic/cms/blob/3.1/src/Http/Middleware/Localize.php

**Comment by aerni** [comment]
I ran into the same issue. But it's not limited to custom routes. It happens on a regular `404` page too.

I've got an `_seo.antlers.html` partial that is included in my error layout. In that partial I do the following which is causing the issue:

```html
{{ locales }}
    <link rel="alternate" hreflang="{{ locale:full replace="_|-" }}" href="{{ permalink }}">
{{ /locales }}
```

**Comment by aerni** [comment]
I can confirm that this issue is because of PR https://github.com/statamic/cms/pull/3689. If you revert the changes of that PR, everything works fine.

**Comment by jasonvarga** [comment]
On it.
