### ISSUE TITLE
Error on asset find if two disks have similar url

### ISSUE THREAD

**Issue by Lampone** [statamic/cms#3836]
## Bug Description
If you have 2 asset containers that both begin with the same url, `Asset::findByUrl` will fail and will not get the correct asset. 

I don't know why but the following code sorts the containers from shortest url to longest. I think it should be the other way around:
https://github.com/statamic/cms/blob/d00e9ede1d11d2e55774ee6fffeea85efbb4cfbb/src/Assets/AssetRepository.php#L63-L71

Changing `sortBy` to `sortByDesc`  worked for me. 

## How to Reproduce
Create 2 disks and a asset-container for each. 
Set the url of the disk to start with the same string. `foo_test` and `foo_test2`.
It will now always try to get file from the disk with the shorter string (foo_test).

## Extra Detail
I hope this test explains it better: https://github.com/Lampone/cms/commit/3d008ba15d46744fa14a00c390841bdea2c61413

## Environment

Statamic 3.1.13 Pro
Laravel 7.30.4
PHP 7.4.16
pecotamic/sitemap 1.2.2
statamic/eloquent-driver 0.1.1

**Comment by jasonvarga** [comment]
Does one container live inside another? I would suggest you don't do that.

**Comment by Lampone** [comment]
No, they dont. The 2 conflicting container urls for me are:

- public/standorte/muenchen
- public/standorte/muenchen-ost

Multiple containers  are grouped in one folder, but they are not inside each other.

**Comment by jasonvarga** [comment]
That looks fine. Thanks for following up.

**Comment by duncanmcclean** [comment]
Just trying to reproduce this myself but I'm unable to see the issue, here's the steps I followed:

* Created two filesystem disks (`foo_test` and `foo_test2`) - the paths were `public/test/foo_test` and ``public/test/foo_test2`
* Created asset containers for both of them
* Added a bunch of test assets to each disk
* Added an 'Assets' field to a blueprint
* In an entry, selected an asset from the `foo_test2` container and saved the entry
* Refreshed the entry and the asset was showing fine

Maybe I'm doing something wrong?

**Comment by Lampone** [comment]
In the control panel it workes fine. I only noticed the issue on a slider/gallery:
```
{{ header }}
    <div  class="swiper-slide" >
        <picture>
            {{ glide:id width="1920" height="700" format="webp"  }}
                <source data-srcset="{{ url }}" type="image/webp">
            {{ /glide:id }}
            {{glide:id width="1920" height="700" }}
                <img class="swiper-lazy"  width="1920" height="700" data-src="{{ url }}" alt="{{ alt }}">
            {{ /glide:id }}
        </picture>
        <div class="swiper-lazy-preloader"></div>
    </div>
{{ /header }}
```
_header is the asset field_

It somehow retrieves the files by url, maybe because of the cache. It is a modified asset field, so maybe I did something wrong on that part. 

**See the Test which failed for me**: https://github.com/Lampone/cms/commit/3d008ba15d46744fa14a00c390841bdea2c61413

**Comment by duncanmcclean** [comment]
Hmm, weird. If I try in one of my templates with/without Glide, it's working perfectly, here's the stripped down code I'm using (`images` is my assets field)

```
{{ images }}
    <img src="{{ glide:id }}">
{{ /images }}
```

Are you able to reproduce the issue in a fresh Statamic install?

**Comment by Lampone** [comment]
Yeah I am. Funny though your code works, what doesnt work is: 

```
{{ image-second }}

    {{ glide:id }}

        <img src="{{ url  }}">

    {{ /glide:id }}

{{ /image-second }}
```

I somehow can't share via flare, here is the stacktrace:
```
[previous exception] [object] (Error(code: 0): Call to a member function disk() on null at /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Imaging/ImageGenerator.php:111)
[stacktrace]
#0 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Tags/Glide.php(136): Statamic\\Imaging\\ImageGenerator->generateByAsset()
#1 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Tags/Glide.php(103): Statamic\\Tags\\Glide->generateImage()
#2 [internal function]: Statamic\\Tags\\Glide->Statamic\\Tags\\{closure}()
#3 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map()
#4 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Tags/Glide.php(116): Illuminate\\Support\\Collection->map()
#5 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Tags/Glide.php(33): Statamic\\Tags\\Glide->generate()
#6 [internal function]: Statamic\\Tags\\Glide->__call()
#7 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func()
#8 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag()
#9 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array()
#10 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(341): Statamic\\View\\Antlers\\Parser->parseCallbackTags()
#11 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(288): Statamic\\View\\Antlers\\Parser->parseLoopInstance()
#12 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}()
#13 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map()
#14 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(289): Illuminate\\Support\\Collection->map()
#15 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(223): Statamic\\View\\Antlers\\Parser->parseLoopVariables()
#16 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(175): Statamic\\View\\Antlers\\Parser->parseVariables()
#17 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse()
#18 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView()
#19 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get()
#20 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#21 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#22 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/View/View.php(77): Illuminate\\View\\View->render()
#23 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Responses/DataResponse.php(151): Statamic\\View\\View->render()
#24 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Responses/DataResponse.php(46): Statamic\\Http\\Responses\\DataResponse->contents()
#25 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Structures/Page.php(289): Statamic\\Http\\Responses\\DataResponse->toResponse()
#26 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Statamic\\Structures\\Page->toResponse()
#27 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse()
#28 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse()
#29 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#30 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#32 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle()
#34 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/Localize.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle()
#36 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle()
#38 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#40 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#42 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#44 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#46 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#47 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#49 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#51 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#53 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#54 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#55 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#56 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#57 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#58 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle()
#60 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#62 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#64 /home/stefan/webserver/statamic-3836/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#66 /home/stefan/webserver/statamic-3836/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#68 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#70 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#71 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#73 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#74 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#76 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#78 /home/stefan/webserver/statamic-3836/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#80 /home/stefan/webserver/statamic-3836/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#82 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#84 /home/stefan/webserver/statamic-3836/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#85 /home/stefan/webserver/statamic-3836/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#86 {main}
"} 

```

**Comment by Lampone** [comment]
Are you able to recreate the issue now or do you need more information?

**Comment by duncanmcclean** [comment]
I'm fairly sure `{{ glide:id }}` itself should return a URL, you can do this:

```
{{ image-second }}
        <img src="{{ glide:id  }}">
{{ /image-second }}
```

**Comment by Lampone** [comment]
How could I get a alt-text this way?

**Comment by duncanmcclean** [comment]
Does this work? I've not tested it.

```
{{ image-second }}
        <img src="{{ glide:id  }}" alt="{{ alt }}">
{{ /image-second }}
```
