### ISSUE TITLE
Asset upload broken

### ISSUE THREAD

**Issue by marcusand** [statamic/cms#4048]
## Bug Description

Since updating from 3.0.26 to 3.0.29 the asset upload is broken for us. 

## How to Reproduce

1. Upload any asset through the control panel
2. Asset size is always 0B, last modified is 51 years ago and thumbnail is broken although file is places correctly in the file system. 

## Extra Detail
<img width="1373" alt="Screenshot 2021-07-26 at 11 25 27" src="https://user-images.githubusercontent.com/28539818/126966765-d43e27bd-b52a-4268-93bf-67f0ae3a413f.png">

the asset container is a local filesytem. config looks like: 
```php
        'public_folder' => [
            'driver' => 'local',
            'root' => public_path('assets'),
            'url' => env('APP_URL') . '/assets',
            'visibility' => 'public',
        ],
```

No output in the browser console or laravel log...

## Environment
Statamic 3.1.29 Pro
Laravel 7.30.4
PHP 8.0.8
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by tbruckmaier** [comment]
Same here, broken in 3.1.29, working in 3.1.26.

I tried to backtrace the error starting from `Statamic\Http\Controllers\CP\Assets\AssetController@store`, and it seems that the metadata array becomes empty while passing it through the various classes. The pull request https://github.com/statamic/cms/pull/3964 happened between the two releases, and touches that part of the code. Probably someone with a better understanding of the internals can see whats wrong here?

**Comment by marcusand** [comment]
Oh, yeah I mean 3.1.26/3.1.29

**Comment by jasonvarga** [comment]
Can you try to open the URL of the broken thumbnail there in its own tab and see if there's an error?

**Comment by andrew-ireland** [comment]
I've also been experiencing this issue.

Seems to happen to me when using Redis for queue management, if the stache watcher is set to false (which it would be on production). If I set the Stache watcher to true, this resolves the issue for me.

**Comment by marcusand** [comment]
@jasonvarga just tested it again and now the thumbnail creation works...not sure what is different...

<img width="1355" alt="Screenshot 2021-07-27 at 10 47 25" src="https://user-images.githubusercontent.com/28539818/127125189-8d5b4b67-67cf-45b6-9e1c-976e6b8c4c04.png">

But when I click on the asset, the asset editor only shows the loading screen and an error is thrown:
````
[2021-07-27 08:47:39] local.ERROR: Call to a member function id() on null {"userId":"f34a82ae-5501-4519-9e18-418131f2be95","exception":"[object] (Error(code: 0): Call to a member function id() on null at /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23)
[stacktrace]
#0 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php(148): Illuminate\\Http\\Resources\\Json\\JsonResource->forwardCallTo(NULL, 'id', Array)
#1 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Resources/CP/Assets/Asset.php(14): Illuminate\\Http\\Resources\\Json\\JsonResource->__call('id', Array)
#2 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(96): Statamic\\Http\\Resources\\CP\\Assets\\Asset->toArray(Object(Illuminate\\Http\\Request))
#3 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceResponse.php(39): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#4 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(222): Illuminate\\Http\\Resources\\Json\\ResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#5 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Http\\Resources\\Json\\JsonResource->toResponse(Object(Illuminate\\Http\\Request))
#6 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Assets\\Asset))
#7 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Assets\\Asset))
#8 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#27 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#68 /Users/marcus/projekte/arbeit/meso/drm/statamic-v3/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#69 /Users/marcus/.composer/vendor/laravel/valet/server.php(219): require('/Users/marcus/p...')
#70 {main}
"}
```

**Comment by tbruckmaier** [comment]
As @andrew-ireland reported, I can also resolve the error by enabling stache watcher. Still reproducable with `STATAMIC_STACHE_WATCHER=false` though:

The initial post request "succeeds" with code 200, though it already returns ` "lastModified": "1970-01-01"`, `"size": "0 B"`, `"width": null`

Full response:
```json
HTTP/2 200 OK
server: nginx/1.21.1
date: Tue, 27 Jul 2021 20:00:27 GMT
content-type: application/json
content-length: 7061
x-powered-by: PHP/7.4.16
cache-control: no-cache, private
permissions-policy: interest-cohort=()
set-cookie: XSRF-TOKEN=eyJpdiI6IjNFOUhOYWFzSCtzclZxeDVpcHhneHc9PSIsInZhbHVlIjoidmJvMFYzcjAvOWRhUmtHblA4dzNEQ05vZkVPWWp0b1VWTExCSklXckE4QTRhMWpINFhQL1NqWGdZVi91ajVwcTZOMFluUzRLM25Wd3ZWV015S0xJckhlRGhtMkhva1ZPSC9qMWdFZ081YVloeTMwSE9GUjFHSDArbjlCUUhKV0wiLCJtYWMiOiI2MThlZjQ0ZGMyMzBkNGNiZGE5MGY2OTFlNDMyMDcxMjcyYTIxZjQzNWE1ZGE5OTliMDUwNGQ4NmQyMDEwODIyIn0%3D; expires=Tue, 27-Jul-2021 22:00:27 GMT; Max-Age=7200; path=/; secure; samesite=lax
kontext_ausstellung_lokal_session=eyJpdiI6Im92bWJzZE9YU0tTb3RFYjJRV3lYNWc9PSIsInZhbHVlIjoiNHlDL1luWXVhZkcvTU9TSWdzbUlvQ0w1ZElGaU0vV1ZQV2VmaU1KTHIyTEVFQmJUL3JtWU03NTZEaFZIandiQ2VPeC9rS0lGWU5CbnRJZ0poZ1YvdlMraUhKZG5aZDR4aXZCa3BlVEVKTEVJWmpvd2twV3FwLzBMcnZZVjE1OFUiLCJtYWMiOiJhYzA5N2ZmOTczMTNlNDAxYTEwNzc4NmZhODcxYzk0ODBjNWNjOTMyMzZlNTliYjc4MjEyM2JiMmRiOTllYTU2In0%3D; expires=Tue, 27-Jul-2021 22:00:27 GMT; Max-Age=7200; path=/; secure; httponly; samesite=lax
X-Firefox-Spdy: h2

{
    "data": {
        "actionUrl": "https://kontext.localhost/cp/assets/actions", 
        "actions": ..., 
        "allowDownloading": true, 
        "basename": "000pexels-photo-991012.jpeg", 
        "blueprint": ..., 
        "downloadUrl": "https://kontext.localhost/cp/assets/YXNzZXRzOjowMDBwZXhlbHMtcGhvdG8tOTkxMDEyLmpwZWc=/download", 
        "extension": "jpeg", 
        "filename": "000pexels-photo-991012", 
        "height": null, 
        "id": "assets::000pexels-photo-991012.jpeg", 
        "isAudio": false, 
        "isImage": true, 
        "isPreviewable": false, 
        "isSvg": false, 
        "isVideo": false, 
        "lastModified": "1970-01-01", 
        "lastModifiedRelative": "vor 51 Jahren", 
        "meta": {
            "alt": null
        }, 
        "path": "000pexels-photo-991012.jpeg", 
        "permalink": "https://kontext.localhost/assets/000pexels-photo-991012.jpeg", 
        "preview": "/assets/000pexels-photo-991012.jpeg", 
        "size": "0 B", 
        "thumbnail": "https://kontext.localhost/cp/thumbnails/YXNzZXRzOjowMDBwZXhlbHMtcGhvdG8tOTkxMDEyLmpwZWc=/small", 
        "url": "/assets/000pexels-photo-991012.jpeg", 
        "values": {
            "alt": null
        }, 
        "width": null
    }
}
```

The next GET request for the thumbnail to `https://kontext.localhost/cp/thumbnails/YXNzZXRzOjowMDBwZXhlbHMtcGhvdG8tOTkxMDEyLmpwZWc=/small` fails with a 500 (somehow the frontend controller gets hit, since the thumbnail does not exist?)
```
ErrorException
Undefined variable: site (View: /var/www/html/statamic/resources/views/layout.blade.php) 
```

The image is uploaded, but its meta data file is empty:
```bash
$ ls -rthla public/assets/000pexels-photo-991012.jpeg     
-rw-r--r-- 1 docker docker 328K Jul 27 20:00 public/assets/000pexels-photo-991012.jpeg
$ cat public/assets/.meta/000pexels-photo-991012.jpeg.yaml
data: {  }
```

**Comment by notnek** [comment]
I've run into this today when I updated from 3.1.26 to 3.1.30 and pushed it to a staging env. Our staging env is configured with the stache watcher disabled, and uses redis for the queue. The image file and corresponding meta file are created fine, however the meta file has the contents `data: { }` only which seems to be the culprit behind the broken CP/data reads. Downgrading to 3.1.27 which is the released before #3964 fixed it.

**Comment by jasonvarga** [comment]
I'm going to revert #3964 for now.

**Comment by jasonvarga** [comment]
3.1.31 has been tagged now.
