### ISSUE TITLE
500 error while adding asset in bard

### ISSUE THREAD

**Issue by peimann** [statamic/cms#4160]
## Bug Description
I have installed fresh Statmic and ran `php artisan serve` then added a collection named 'Articles' and edited blueprint of it and replaced markdown with Bard fieldtype, saved and returned to add a new entry, I tried to add an image in the bard editor but faced with 500 error. I've uploaded a screenshot below.

## Extra Detail
![image](https://user-images.githubusercontent.com/40042952/130224824-9125a326-99be-4f50-b2bd-c24011f3f6af.png)

## Environment

Statamic 3.1.32 Pro
Laravel 8.54.0
PHP 7.4.20
No addons installed

**Install method (choose one):**
- Existing Laravel app

**Comment by duncanmcclean** [comment]
Anything in the logs? (storage/logs)

**Comment by peimann** [comment]
Here it is:

```
local.ERROR: Argument 1 passed to Statamic\Assets\AssetRepository::find() must be of the type string, null given, called in /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261 {"userId":"f4b1070f-0823-4794-bddc-8c235d1cb79f","exception":"[object] (TypeError(code: 0): Argument 1 passed to Statamic\\Assets\\AssetRepository::find() must be of the type string, null given, called in /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261 at /private/var/www/statamic/test/vendor/statamic/cms/src/Assets/AssetRepository.php:33)
[stacktrace]
#0 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Assets\\AssetRepository->find(NULL)
#1 /private/var/www/statamic/test/vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php(118): Illuminate\\Support\\Facades\\Facade::__callStatic('find', Array)
#2 [internal function]: Statamic\\Fieldtypes\\Assets\\Assets->Statamic\\Fieldtypes\\Assets\\{closure}(NULL, 0)
#3 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#4 /private/var/www/statamic/test/vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php(121): Illuminate\\Support\\Collection->map(Object(Closure))
#5 /private/var/www/statamic/test/vendor/statamic/cms/src/Http/Controllers/CP/Assets/FieldtypeController.php(14): Statamic\\Fieldtypes\\Assets\\Assets->getItemData(Array)
#6 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Assets\\FieldtypeController->index(Object(Illuminate\\Http\\Request))
#7 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#8 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Assets\\FieldtypeController), 'index')
#9 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#10 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#11 /private/var/www/statamic/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
.
.
.
```

**Comment by ParedesCreative** [comment]
Dealing with this one as well, which is preventing me from building my site. Just a heads up! I'm loving everything about Statamic otherwise! Thanks all.

### Environment
Statamic 3.1.34 Pro
Laravel 8.55.0
PHP 8.0
No addons installed

Install method:
Brand new Statamatic/Laravel App

**Comment by jasonvarga** [comment]
Are you using the Grammarly browser extension? Can you try again with it disabled?

**Comment by ParedesCreative** [comment]
> Are you using the Grammarly browser extension? Can you try again with it disabled?

I am not using Grammarly, but this issue resolved itself after I upgraded to the 3.2.0 today! 🎉 I'm very pleased. Thanks!

**Comment by jackmcdade** [comment]
Huzzah!

**Comment by HighLifeHighland** [comment]
Follow up: everything works (no errors) if I use a `public` rather than `local` disk. The latter doesn't make sense anyway, because there's no way of rendering this content.
