### ISSUE TITLE
Moving assets throws an array to string error

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#4227]
## Bug Description
Moving assets in the Assets listing throws an array to string error. See error below.

## How to reproduce
1. Go to Assets listing (/cp/assets/browse/assets)
2. Select image asset
3. Click Move
4. Select folder and click Move Asset
5. See error

## Extra Detail

Video:
https://www.loom.com/share/35d0686ca60d4bd39f9314aac811556e

<details>
<summary>Error log</summary>
```
[2021-09-07 11:05:44] local.ERROR: Array to string conversion {"userId":"dc5c4773-a82f-44d4-99bf-0e2767b80826","exception":"[object] (ErrorException(code: 0): Array to string conversion at /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php:148)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Array to string...', '/Users/mike/Sit...', 148)
#1 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(148): preg_replace_callback('/([(\"]statamic:...', Object(Closure), Array)
#2 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(83): Statamic\\Assets\\AssetReferenceUpdater->updateStatamicUrlsInStringValue(Object(Statamic\\Fields\\Field), NULL)
#3 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Assets\\AssetReferenceUpdater->Statamic\\Assets\\{closure}(Object(Statamic\\Fields\\Field), 'content')
#4 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(85): Illuminate\\Support\\Collection->each(Object(Closure))
#5 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(39): Statamic\\Assets\\AssetReferenceUpdater->updateBardFieldValues(Object(Illuminate\\Support\\Collection), NULL)
#6 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Data/DataReferenceUpdater.php(62): Statamic\\Assets\\AssetReferenceUpdater->recursivelyUpdateFields(Object(Illuminate\\Support\\Collection))
#7 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(43): Statamic\\Data\\DataReferenceUpdater->updateReferences('Staff-documents...', 'careers/Staff-d...')
#8 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Listeners\\UpdateAssetReferences->Statamic\\Listeners\\{closure}(Object(Statamic\\Entries\\Entry), 103)
#9 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(44): Illuminate\\Support\\Collection->each(Object(Closure))
#10 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): Statamic\\Listeners\\UpdateAssetReferences->handle(Object(Statamic\\Events\\AssetSaved))
#11 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle(Object(Illuminate\\Foundation\\Application))
#12 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#17 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#18 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#19 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#20 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Events\\CallQueuedListener), false)
#21 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#22 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#23 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Illuminate\\Events\\CallQueuedListener))
#25 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#26 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#27 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Events\\CallQueuedListener), '', NULL)
#28 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(574): Illuminate\\Queue\\Queue->pushOn(NULL, Object(Illuminate\\Events\\CallQueuedListener))
#29 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(498): Illuminate\\Events\\Dispatcher->queueHandler('Statamic\\\\Listen...', 'handle', Array)
#30 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(424): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(Statamic\\Events\\AssetSaved))
#31 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Statamic\\\\Events...', Array)
#32 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch('Statamic\\\\Events...')
#33 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event(Object(Statamic\\Events\\AssetSaved))
#34 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/Asset.php(422): Statamic\\Events\\Event::dispatch(Object(Statamic\\Assets\\Asset))
#35 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Assets/Asset.php(527): Statamic\\Assets\\Asset->save()
#36 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Statamic\\Assets\\Asset->move('careers')
#37 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Statamic\\Assets\\Asset), 0)
#38 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->each(Object(Closure))
#39 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Actions/MoveAsset.php(40): Illuminate\\Support\\HigherOrderCollectionProxy->__call('move', Array)
#40 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Controllers/CP/ActionController.php(36): Statamic\\Actions\\MoveAsset->run(Object(Illuminate\\Support\\Collection), Array)
#41 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\ActionController->run(Object(Illuminate\\Http\\Request))
#42 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('run', Array)
#43 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Assets\\ActionController), 'run')
#44 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#45 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#46 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#65 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#74 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#75 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#76 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#77 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#78 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/mike/Sites/new.shiftcare/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/mike/Sites/new.shiftcare/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/mike/Sites/new.shiftcare/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#100 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /Users/mike/Sites/new.shiftcare/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#103 /Users/mike/Sites/new.shiftcare/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#104 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#105 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#106 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#107 /Users/mike/Sites/new.shiftcare/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#108 /Users/mike/Sites/new.shiftcare/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#109 /Users/mike/.composer/vendor/laravel/valet/server.php(235): require('/Users/mike/Sit...')
#110 {main}
"} 
```
</details>

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.22
mikemartin/helpscout-beacon 1.0.2
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.7
spatie/statamic-responsive-images 2.8.0
withcandour/aardvark-seo 2.0.15

**Comment by mikemartin** [comment]
@jasonvarga Turns out this was an issue with the `save_html` option. For some reason it was set to `true` in my bard field but the content was stored in the bard format. See field settings below:

```
-
    handle: content
    field:
      always_show_set_button: false
      sets:
        button:
          display: Button
          fields:
            -
              import: link
              prefix: button_
        video:
          display: Video
          fields:
            -
              handle: video
              field:
                display: Video
                type: video
                icon: video
                listable: hidden
            -
              handle: caption
              field:
                input_type: text
                display: Caption
                type: text
                icon: text
                listable: hidden
        image:
          display: Image
          fields:
            -
              handle: image
              field: common.image
              config:
                folder: blog
            -
              handle: caption
              field:
                input_type: text
                display: Caption
                type: text
                icon: text
                listable: hidden
        call_to_action:
          display: 'Call to Action'
          fields:
            -
              handle: title
              field:
                input_type: text
                display: Title
                type: text
                icon: text
                listable: hidden
            -
              handle: description
              field: common.description
            -
              handle: button
              field: common.button
        review:
          display: Review
          fields:
            -
              handle: review
              field: common.entries
              config:
                display: Review
                max_items: 1
                collections:
                  - reviews
      buttons:
        - h2
        - h3
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - removeformat
        - quote
        - anchor
        - image
        - table
      save_html: true
      container: assets
      toolbar_mode: fixed
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: true
      fullscreen: true
      allow_source: true
      display: Content
      type: bard
      icon: bard
      listable: hidden
      replicator_preview: false
  -
  ```
