### ISSUE TITLE
Error after upgrade from 3.1 to 3.2 (latest)

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#4259]
## Bug Description
This error is shown:
```
Facade\Ignition\Exceptions\ViewException
Call to a member function fields() on null
```
When I remove the nav tag, the error is gone:
```
                {{ nav:collection:pages  }}
                <li class="transition-all duration-500 ease-in-out">
                    <a href="{{ url }}" class="text-pri hover:text-sec block pb-1 uppercase">
                        {{ title }}
                    </a>
                    {{ if children }}
                    <ul class="inner flex-col pl-2 text-lg">
                        {{ children }}
                        <li class="{{ if is_current || is_parent }}active bg-pri bg-opacity-10 px-4 -ml-4 text-white{{ /if }} transition-all duration-500 ease-in-out mr-8">
                            <a href="{{ url }}" class="block py-1 {{ if is_current || is_parent }}text-white{{ /if }}">
                                <i class="fa-icon fas fa-caret-right"></i>
                                {{ title }}
                            </a>
                        </li>
                        {{ /children }}
                    </ul>
                    {{ /if }}

                </li>
                {{ /nav:collection:pages }}
```
## Extra Detail
```
[previous exception] [object] (Error(code: 0): Call to a member function fields() on null at \\vendor\\statamic\\cms\\src\\Structures\\AugmentedPage.php:65)
[stacktrace]
#0 \\vendor\\statamic\\cms\\src\\Entries\\AugmentedEntry.php(15): Statamic\\Structures\\AugmentedPage->blueprintFields()
#1 \\vendor\\statamic\\cms\\src\\Structures\\AugmentedPage.php(28): Statamic\\Entries\\AugmentedEntry->keys()
#2 \\vendor\\statamic\\cms\\src\\Data\\AbstractAugmented.php(33): Statamic\\Structures\\AugmentedPage->keys()
#3 \\vendor\\statamic\\cms\\src\\Data\\HasAugmentedInstance.php(16): Statamic\\Data\\AbstractAugmented->select(NULL)
#4 \\vendor\\statamic\\cms\\src\\Data\\HasAugmentedInstance.php(21): Statamic\\Structures\\Page->toAugmentedCollection(NULL)
#5 \\vendor\\statamic\\cms\\src\\Tags\\Structure.php(51): Statamic\\Structures\\Page->toAugmentedArray()
#6 [internal function]: Statamic\\Tags\\Structure->Statamic\\Tags\\{closure}(Array, 2)
#7 \\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Collection.php(638): array_map(Object(Closure), Array, Array)
#8 \\vendor\\statamic\\cms\\src\\Tags\\Structure.php(66): Illuminate\\Support\\Collection->map(Object(Closure))
#9 \\vendor\\statamic\\cms\\src\\Tags\\Structure.php(44): Statamic\\Tags\\Structure->toArray(Array)
#10 \\vendor\\statamic\\cms\\src\\Tags\\Structure.php(21): Statamic\\Tags\\Structure->structure('collection::pag...')
#11 \\vendor\\statamic\\cms\\src\\Tags\\Tags.php(138): Statamic\\Tags\\Structure->wildcard('collection:page...')
#12 [internal function]: Statamic\\Tags\\Tags->__call('collection:page...', Array)
#13 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Engine.php(159): call_user_func(Array)
#14 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'nav', Array, '\
              ...', Array)
#15 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(578): call_user_func_array(Array, Array)
#16 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<nav class=\"nav...', Array)
#17 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<nav class=\"nav...', Array)
#18 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('D:\\\\Websites\\\\h-s...', '<nav class=\"nav...', Array)
#19 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(139): Statamic\\View\\Antlers\\Engine->get('D:\\\\Websites\\\\h-s...', Array)
#20 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(122): Illuminate\\View\\View->getContents()
#21 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#22 \\vendor\\statamic\\cms\\src\\Tags\\Partial.php(20): Illuminate\\View\\View->render()
#23 \\vendor\\statamic\\cms\\src\\Tags\\Tags.php(138): Statamic\\Tags\\Partial->wildcard('partials.nav.ma...')
#24 [internal function]: Statamic\\Tags\\Tags->__call('partials.nav.ma...', Array)
#25 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Engine.php(159): call_user_func(Array)
#26 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#27 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(578): call_user_func_array(Array, Array)
#28 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<header class=\"...', Array)
#29 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<header class=\"...', Array)
#30 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('D:\\\\Websites\\\\h-s...', '<header class=\"...', Array)
#31 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(139): Statamic\\View\\Antlers\\Engine->get('D:\\\\Websites\\\\h-s...', Array)
#32 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(122): Illuminate\\View\\View->getContents()
#33 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#34 \\vendor\\statamic\\cms\\src\\Tags\\Partial.php(20): Illuminate\\View\\View->render()
#35 \\vendor\\statamic\\cms\\src\\Tags\\Tags.php(138): Statamic\\Tags\\Partial->wildcard('partials.layout...')
#36 [internal function]: Statamic\\Tags\\Tags->__call('partials.layout...', Array)
#37 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Engine.php(159): call_user_func(Array)
#38 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#39 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(578): call_user_func_array(Array, Array)
#40 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<!doctype html>...', Array)
#41 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<!doctype html>...', Array)
#42 \\vendor\\statamic\\cms\\src\\View\\Antlers\\Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('D:\\\\Websites\\\\h-s...', '<!doctype html>...', Array)
#43 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(139): Statamic\\View\\Antlers\\Engine->get('D:\\\\Websites\\\\h-s...', Array)
#44 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(122): Illuminate\\View\\View->getContents()
#45 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#46 \\vendor\\statamic\\cms\\src\\View\\View.php(95): Illuminate\\View\\View->render()
#47 \\vendor\\statamic\\cms\\src\\Http\\Responses\\DataResponse.php(155): Statamic\\View\\View->render()
#48 \\vendor\\statamic\\cms\\src\\Http\\Responses\\DataResponse.php(46): Statamic\\Http\\Responses\\DataResponse->contents()
#49 \\vendor\\statamic\\cms\\src\\Structures\\Page.php(377): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#50 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(744): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#51 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(731): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#52 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#53 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 \\vendor\\statamic\\cms\\src\\StaticCaching\\Middleware\\Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\Localize.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 \\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 \\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 \\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#70 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 \\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 \\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#77 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#78 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#79 \\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#80 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#81 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#82 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 \\vendor\\statamic\\cms\\src\\Http\\Middleware\\PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 \\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#93 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 \\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#102 \\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#103 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 \\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#106 \\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#107 \\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#108 {main}
"} 

```
The cp works normal. I've cleared the cache, downgraded to 3.1, etc. I have no idea what else I can do. 
Can someone help?

## Environment

**Statamic version:** 3.2.4

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The error message needs some love, but do you have any entries in your `pages` collection with

```
blueprint: one_that_doesnt_exist_in_the_pages_directory
```

?

**Comment by wm-simon** [comment]
I had `blueprint: link` on one page and deactivated link option in the collection setting. Don't know, if there something went wrong with the upgrade. After downgrading the site worked again. Weird... 
Thanks for the hint to the right direction.
