### ISSUE TITLE
Page sometimes errors out despite not doing anything between loads

### ISSUE THREAD

**Issue by kaitwalla** [statamic/cms#4626]
### Bug description

I am trying out Statamic for the first time, so I'm well aware I may not be doing things correctly. My ultimate goal is a single-page site that pulls in some Playlists stored in the backend. I have two playlists as Entries. In `routes/web.php`, I'm calling the following:

```
$playlists = Entry::query()->where('collection', 'playlist');
if ($playlists->count() > 0) {
    $playlists = $playlists->get();
} else {
    $playlists = [];
}
ray($playlists);
Route::statamic('/', 'default', [
    'title' => 'miXmas',
    'playlists' => $playlists
]);
```

(The count check is mostly to try to avoid this issue, but it continues to happen. Originally I just had `$playlists =Entry::query()->where('collection', 'playlist')->get();

This is the output of ray() of when I loaded the page, then refreshed it several times:

![Screen Shot 2021-10-30 at 3 29 41 PM](https://user-images.githubusercontent.com/3107030/139560119-30fba8e1-3f73-458f-8340-952b73e0f82e.png)
 
There were no content or code changes between those refreshes. Whenever I make a code change, I get the error message once or twice, then it works again.

Any advice as to what could be causing this?

### How to reproduce

Repo where problem occurs: https://github.com/kaitwalla/mixMas

### Logs

```shell
[2021-10-30 22:26:27] local.ERROR: Call to a member function dated() on null {"exception":"[object] (Error(code: 0): Call to a member function dated() on null at /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:88)
[stacktrace]
#0 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(298): Statamic\\Stache\\Stores\\CollectionEntriesStore->makeItemFromFile('/Users/kait/Sit...', '---\
id: home\
bl...')
#1 [internal function]: Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}(1634503768, '/Users/kait/Sit...')
#2 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(664): array_map(Object(Closure), Array, Array)
#3 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(302): Illuminate\\Support\\Collection->map(Object(Closure))
#4 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(70): Statamic\\Stache\\Stores\\Store->paths()
#5 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(216): Statamic\\Stache\\Stores\\BasicStore->getKeyFromPath('/Users/Kait/Sit...')
#6 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}('/Users/Kait/Sit...', 0)
#7 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(222): Illuminate\\Support\\Collection->each(Object(Closure))
#8 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(43): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#9 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/CollectionsStore.php(82): Statamic\\Stache\\Stores\\Store->index('uri')
#10 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(83): Statamic\\Stache\\Stores\\CollectionsStore->updateEntryUris(Object(Statamic\\Entries\\Collection), NULL)
#11 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\CollectionRepository->updateEntryUris(Object(Statamic\\Entries\\Collection), NULL)
#12 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Entries/Collection.php(392): Illuminate\\Support\\Facades\\Facade::__callStatic('updateEntryUris', Array)
#13 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/CollectionsStore.php(103): Statamic\\Entries\\Collection->updateEntryUris()
#14 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(20): Statamic\\Stache\\Stores\\CollectionsStore->handleFileChanges()
#15 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(36): Statamic\\Stache\\Stores\\BasicStore->getItem('playlist')
#16 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\CollectionRepository->findByHandle('playlist')
#17 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(156): Illuminate\\Support\\Facades\\Facade::__callStatic('findByHandle', Array)
#18 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(129): Statamic\\Stache\\Stores\\CollectionEntriesStore->storeIndexes()
#19 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(149): Statamic\\Stache\\Stores\\Store->indexes(true)
#20 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(219): Statamic\\Stache\\Stores\\Store->resolveIndexes()
#21 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}('626e98a3-e76c-4...', 0)
#22 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(221): Illuminate\\Support\\Collection->each(Object(Closure))
#23 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}('/Users/Kait/Sit...', 1)
#24 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(222): Illuminate\\Support\\Collection->each(Object(Closure))
#25 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Stores/Store.php(284): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#26 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(68): Statamic\\Stache\\Stores\\Store->paths()
#27 [internal function]: Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}('playlist', 0)
#28 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(664): array_map(Object(Closure), Array, Array)
#29 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(351): Illuminate\\Support\\Collection->map(Object(Closure))
#30 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(73): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#31 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(61): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysFromCollections(Array)
#32 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Query/Builder.php(43): Statamic\\Stache\\Query\\EntryQueryBuilder->getFilteredKeys()
#33 /Users/kait/Sites/personal/music/vendor/statamic/cms/src/Stache/Query/Builder.php(21): Statamic\\Stache\\Query\\Builder->getFilteredAndLimitedKeys()
#34 /Users/kait/Sites/personal/music/routes/web.php(18): Statamic\\Stache\\Query\\Builder->count()
#35 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php(35): require('/Users/kait/Sit...')
#36 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Routing/Router.php(425): Illuminate\\Routing\\RouteFileRegistrar->register('/Users/kait/Sit...')
#37 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Routing/Router.php(382): Illuminate\\Routing\\Router->loadRoutes('/Users/kait/Sit...')
#38 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(135): Illuminate\\Routing\\Router->group(Array, '/Users/kait/Sit...')
#39 /Users/kait/Sites/personal/music/app/Providers/RouteServiceProvider.php(48): Illuminate\\Routing\\RouteRegistrar->group('/Users/kait/Sit...')
#40 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\RouteServiceProvider->App\\Providers\\{closure}()
#41 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#43 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#44 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#45 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(120): Illuminate\\Container\\Container->call(Object(Closure))
#46 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(45): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes()
#47 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}()
#48 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#49 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#50 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#51 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#52 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(119): Illuminate\\Container\\Container->call(Object(Closure))
#53 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(917): Illuminate\\Support\\ServiceProvider->callBootedCallbacks()
#54 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\RouteServiceProvider))
#55 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\RouteServiceProvider), 54)
#56 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk(Array, Object(Closure))
#57 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#58 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#59 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#60 /Users/kait/Sites/personal/music/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#61 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#62 {main}
"}
```

### Versions

Statamic 3.2.19 Solo
Laravel 8.68.1
PHP 8.0.11

### Installation

Fresh statamic/statamic site via CLI

**Comment by edalzell** [comment]
By 'stored in the backend' do you mean a collection? If so, why are you defining routes like that? Use the `home` page and `antlers` in the template?

**Comment by kaitwalla** [comment]
Is there a way to do queries in antlers? I couldn't see any immediately obvious way to query or pass the data to the homepage.

**Comment by kaitwalla** [comment]
Thanks! I found helpful examples in, appropriately enough, the example projects. Should have looked there first, sorry!
