### ISSUE TITLE
Call to a member function hasStructure() on null (php please stache:warm)

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4628]
### Bug description

When running `php please stache:warm`, sometimes the following error get logged in `vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:133`

```
Call to a member function hasStructure() on null
```

```
protected function removeEntryFromStructure($collection, $id)
{
    if (! $collection->hasStructure()) {
        return;
    }

    ....
}
```

### How to reproduce

Run `php please stache:warm` with a bunch of entries created, and this error will occasionally pop up in your logs.

### Logs

```shell
[2021-11-01 08:12:58] production.ERROR: Call to a member function hasStructure() on null {"exception":"[object] (Error(code: 0): Call to a member function hasStructure() on null at /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:133)
[stacktrace]
#0 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(128): Statamic\\Stache\\Stores\\CollectionEntriesStore->removeEntryFromStructure()
#1 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(220): Statamic\\Stache\\Stores\\CollectionEntriesStore->handleDeletedItem()
#2 /home/webapps/yyy/releases/20211101071126/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}()
#3 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(221): Illuminate\\Support\\Collection->each()
#4 /home/webapps/yyy/releases/20211101071126/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}()
#5 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(222): Illuminate\\Support\\Collection->each()
#6 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(143): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#7 /home/webapps/yyy/releases/20211101071126/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\TaxonomyTermsStore->Statamic\\Stache\\Stores\\{closure}()
#8 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(144): Illuminate\\Support\\Collection->each()
#9 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(43): Statamic\\Stache\\Stores\\TaxonomyTermsStore->handleFileChanges()
#10 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php(106): Statamic\\Stache\\Stores\\Store->index()
#11 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Repositories/EntryRepository.php(99): Statamic\\Stache\\Stores\\TaxonomyTermsStore->sync()
#12 /home/webapps/yyy/releases/20211101071126/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Repositories\\EntryRepository->Statamic\\Stache\\Repositories\\{closure}()
#13 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Repositories/EntryRepository.php(100): Illuminate\\Support\\Collection->each()
#14 /home/webapps/yyy/releases/20211101071126/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\EntryRepository->taxonomize()
#15 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Entries/Entry.php(347): Illuminate\\Support\\Facades\\Facade::__callStatic()
#16 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(119): Statamic\\Entries\\Entry->taxonomize()
#17 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(254): Statamic\\Stache\\Stores\\CollectionEntriesStore->handleModifiedItem()
#18 /home/webapps/yyy/releases/20211101071126/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}()
#19 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(255): Illuminate\\Support\\Collection->each()
#20 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Stores/Store.php(43): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#21 /home/webapps/yyy/releases/20211101071126/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(82): Statamic\\Stache\\Stores\\Store->index()
```

### Versions

Statamic 3.2.19 Pro
Laravel 8.68.1
PHP 8.0.11
jacksleight/bard-paragraph-style 1.2.2
jonassiewertsen/statamic-livewire 2.7.0
octoper/statamic-blade-components 1.0.1
optimoapps/statamic-bard-text-align 1.0.2

### Installation

Existing Laravel app

**Comment by isarphilipp** [comment]
We're experiencing the same issue on a high traffic website.

The reason as far as I can tell is that Stache is not locking before it's being reset.

So what happens is that after the stache has been `->clear()`ed, it's being regenerated at the same time, once by a current Http Request coming in an by the `->warm()` from `Stache\Stache.php`. This can lead to inconsistencies. We end up seeing either many 500s or some calls to `$entry->url()` simply returning `null`.

We're going to test the following fix in production now and will create a PR if that works:

In `Stache\Stache.php`:

```
    public function refresh()
    {
        Partyline::comment('Refreshing Stache...');

        $lock = tap($this->lock('stache-warming'))->acquire(true);

        $this->startTimer();

        $this->stores()->reverse()->each->clear();

        $this->duplicates()->clear();

        $this->stores()->each->warm();

        $this->stopTimer();

        $lock->release();
    }
```

This will acquire the lock before clearing the stache, essentially blocking any incoming Http request from regenerating the stache.

Would be interesting to hear the opinion from the Gentlemen on this one (@jasonvarga).

**Comment by jasonvarga** [comment]
That sounds reasonable @isarphilipp, good detective work.

**Comment by isarphilipp** [comment]
🎉 That did the trick! I’ll share some results and comparisons soon.

@jasonvarga would you mind if I add a couple of events during the stache clear/warm/refresh lifecycle? I am thinking about something like StacheRefreshing, StacheRefreshed, …

Why: You sometimes want to hook in under the umbrella of the lock. In our case for example it’s important that cache:clear happens while the stache is locked, because all userland caching relies on a fresh and polished stache ;)

**Comment by MrMooky** [comment]
@isarphilipp Have you been able to submit a PR for this yet?

**Comment by helloiamlukas** [comment]
Any updates? @jasonvarga @isarphilipp

**Comment by jesseleite** [comment]
I realize this is a conversation on stache locking, but as an aside... If you are getting these errors because you are using a zero downtime deployment solution (such as Envoyer, Deployer, etc), be sure you aren't sharing cache between your releases. More on this here: https://statamic.dev/tips/zero-downtime-deployments
