### ISSUE TITLE
[Content API - Entry Selecting Fields] Call to a member function cascade() on null

### ISSUE THREAD

**Issue by Buminta** [statamic/cms#4636]
### Bug description

Call to a member function cascade() on null {"exception":"[object] (Error(code: 0): Call to a member function cascade() on null at /var/www/html/vendor/statamic/cms/src/Entries/Entry.php:731)

### How to reproduce

I have calling to API: ```/api/collections/{collection}/entries?fields=id```
However it's not working. And throw ```500|SERVER ERROR```.

I'm showing logs after here!
Please support, Thanks!

### Logs

```shell
laravel.test_1  | [2021-11-02 08:21:06] production.ERROR: Call to a member function cascade() on null {"exception":"[object] (Error(code: 0): Call to a member function cascade() on null at /var/www/html/vendor/statamic/cms/src/Entries/Entry.php:731)
laravel.test_1  | [stacktrace]
laravel.test_1  | #0 /var/www/html/vendor/statamic/cms/src/Entries/AugmentedEntry.php(12): Statamic\\Entries\\Entry->values()
laravel.test_1  | #1 /var/www/html/vendor/statamic/cms/src/Data/AbstractAugmented.php(33): Statamic\\Entries\\AugmentedEntry->keys()
laravel.test_1  | #2 /var/www/html/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(16): Statamic\\Data\\AbstractAugmented->select()
laravel.test_1  | #3 /var/www/html/vendor/statamic/cms/src/Http/Resources/API/EntryResource.php(18): Statamic\\Entries\\Entry->toAugmentedCollection()
laravel.test_1  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Statamic\\Http\\Resources\\API\\EntryResource->toArray()
laravel.test_1  | #5 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
laravel.test_1  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map()
laravel.test_1  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map()
laravel.test_1  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(102): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
laravel.test_1  | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toArray()
laravel.test_1  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(19): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve()
laravel.test_1  | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(134): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse()
laravel.test_1  | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(114): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse()
laravel.test_1  | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse()
laravel.test_1  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse()
laravel.test_1  | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse()
laravel.test_1  | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
laravel.test_1  | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
laravel.test_1  | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
laravel.test_1  | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
laravel.test_1  | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
laravel.test_1  | #23 /var/www/html/vendor/statamic/cms/src/API/Middleware/Cache.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\API\\Middleware\\Cache->handle()
laravel.test_1  | #25 /var/www/html/vendor/statamic/cms/src/Http/Middleware/RequireStatamicPro.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\RequireStatamicPro->handle()
laravel.test_1  | #27 /var/www/html/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
laravel.test_1  | #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
laravel.test_1  | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
laravel.test_1  | #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
laravel.test_1  | #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
laravel.test_1  | #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
laravel.test_1  | #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
laravel.test_1  | #36 /var/www/html/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle()
laravel.test_1  | #38 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
laravel.test_1  | #40 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
laravel.test_1  | #42 /var/www/html/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
laravel.test_1  | #44 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
laravel.test_1  | #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
laravel.test_1  | #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
laravel.test_1  | #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
laravel.test_1  | #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
laravel.test_1  | #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
laravel.test_1  | #54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
laravel.test_1  | #56 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
laravel.test_1  | #58 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
laravel.test_1  | #60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
laravel.test_1  | #61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
laravel.test_1  | #62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
laravel.test_1  | #63 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
laravel.test_1  | #64 /var/www/html/server.php(21): require_once('...')
laravel.test_1  | #65 {main}
laravel.test_1  | "}
```

### Versions

3.2.19

### Installation

Fresh statamic/statamic site via CLI

**Comment by jelleroorda** [comment]
It looks like one of your entries exists in a collection that you've probably deleted. Can you maybe try `php artisan cache:clear` and retry after that?

**Comment by Buminta** [comment]
@jelleroorda It's not working for me!

We're use storage entry in postgres.

**Comment by jasonvarga** [comment]
Are you using https://github.com/statamic/eloquent-driver or something custom?

**Comment by Buminta** [comment]
@jasonvarga I'm using https://github.com/statamic/eloquent-driver

**Comment by jasonvarga** [comment]
Do you have any rows in the `entries` table with a `collection` thats null or doesn't exist?

**Comment by Buminta** [comment]
@jasonvarga Yep i have it!
I think, can you have any question professional more than before this.
I bought two pro license from your team. And i don't want something bad question.

**Comment by ryanmitchell** [comment]
This issue should be fixed by https://github.com/statamic/eloquent-driver/pull/183 which is in eloquent-driver 2.5.1+
