### ISSUE TITLE
Cannot access array variable in the form email template when field options is empty

### ISSUE THREAD

**Issue by simonbedard12** [statamic/cms#4686]
### Bug description

I think this update/pr #4483 broke array variable in email template. 

In the update, you added:  _When a field has a value that isn't in the options, the label is the value, instead of getting an error. Fixes_

### How to reproduce

- Update Statamic to `3.2.17` or above
- Create a form with checkboxes and do not add any options. (I know that sound weird). We will use a collection to fill the input in the front-end. In this exemple I have a collection of e-books. I added a loop to create the input. 
```
{{ collection:e-books }}
<input type="checkbox" id="{{ id }}" name="e-books[]" value="{{ id }}">
{{ /collection:e-books }}
```
- Create a email template for your form submission and try getting the `{{ e-books }}` array variable
```
{{ e-books }}
  {{ value }}
{{ /e-books }
```
- You should get this error when trying to send an email. 
`Argument 1 passed to Illuminate\\Support\\Arr::isAssoc() must be of the type array, null given, called in /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php on line 95`

At first, I thought something was wrong with the submission data. So I completely removed the email, but submission was find:
```
{
"success":true,
"submission_created":true,
"submission":{
  "prenom":"Simon",
  "nom":"B\u00e9dard",
  "courriel":"simon@lesmauvaisgarcons.ca",
  "e-books":["e58bd2bf-db48-4eb1-b269-da7756b82857","d26080f2-87db-40f6-8588-9527175381f5","3dd3f54c-9ebe-4567-9531-457a268105b8"]
  }
} 
```

### Logs

```shell
[2021-11-09 15:58:54] local.ERROR: Argument 1 passed to Illuminate\Support\Arr::isAssoc() must be of the type array, null given, called in /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php on line 95 {"userId":"0e5233db-472c-4749-9822-0aa14d1b0dc8","exception":"[object] (TypeError(code: 0): Argument 1 passed to Illuminate\\Support\\Arr::isAssoc() must be of the type array, null given, called in /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php on line 95 at /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:389)
[stacktrace]
#0 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php(95): Illuminate\\Support\\Arr::isAssoc(NULL)
#1 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php(88): Statamic\\Fieldtypes\\Checkboxes->isOption('e58bd2bf-db48-4...')
#2 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php(70): Statamic\\Fieldtypes\\Checkboxes->getLabel('e58bd2bf-db48-4...')
#3 [internal function]: Statamic\\Fieldtypes\\Checkboxes->Statamic\\Fieldtypes\\{closure}('e58bd2bf-db48-4...', 0)
#4 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map(Object(Closure), Array, Array)
#5 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fieldtypes/HasSelectOptions.php(72): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Fields/Value.php(47): Statamic\\Fieldtypes\\Checkboxes->augment(Array)
#7 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Ignition/Value.php(16): Statamic\\Fields\\Value->value()
#8 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/View/Antlers/Parser.php(1518): Statamic\\Ignition\\Value->__construct(Object(Statamic\\Fields\\Value))
#9 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}(Object(Statamic\\Fields\\Value), 'e-books')
#10 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map(Object(Closure), Array, Array)
#11 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/View/Antlers/Parser.php(1526): Illuminate\\Support\\Collection->map(Object(Closure))
#12 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/View/Antlers/Parser.php(1507): Statamic\\View\\Antlers\\Parser->getViewDataForException(Array)
#13 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/View/Antlers/Parser.php(134): Statamic\\View\\Antlers\\Parser->viewException(Object(TypeError), Array)
#14 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/simonbed...', '<!DOCTYPE html ...', Array)
#15 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/simonbed...', Array)
#16 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#17 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#18 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(382): Illuminate\\View\\View->render()
#19 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(355): Illuminate\\Mail\\Mailer->renderView('email/e-books', Array)
#20 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(273): Illuminate\\Mail\\Mailer->addContent(Object(Illuminate\\Mail\\Message), 'email/e-books', NULL, NULL, Array)
#21 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(187): Illuminate\\Mail\\Mailer->send('email/e-books', Array, Object(Closure))
#22 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(29): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#23 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(188): Illuminate\\Mail\\Mailable->withLocale('fr', Object(Closure))
#24 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(304): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#25 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(258): Illuminate\\Mail\\Mailer->sendMailable(Object(Statamic\\Forms\\Email))
#26 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(550): Illuminate\\Mail\\Mailer->send(Object(Statamic\\Forms\\Email))
#27 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Mail\\MailManager->__call('send', Array)
#28 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Forms/SendEmails.php(36): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#29 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Forms\\SendEmails->Statamic\\Forms\\{closure}(Array, 0)
#30 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Forms/SendEmails.php(37): Illuminate\\Support\\Collection->each(Object(Closure))
#31 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Statamic\\Forms\\SendEmails->handle()
#32 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#34 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#35 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#36 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#37 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Statamic\\Forms\\SendEmails))
#38 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Statamic\\Forms\\SendEmails))
#39 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Statamic\\Forms\\SendEmails), false)
#41 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Statamic\\Forms\\SendEmails))
#42 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Statamic\\Forms\\SendEmails))
#43 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#44 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Statamic\\Forms\\SendEmails))
#45 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#46 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#47 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push(Object(Statamic\\Forms\\SendEmails))
#48 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(Statamic\\Forms\\SendEmails))
#49 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(Statamic\\Forms\\SendEmails))
#50 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(202): Illuminate\\Bus\\Dispatcher->dispatch(Object(Statamic\\Forms\\SendEmails))
#51 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(17): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#52 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Http/Controllers/FormController.php(69): Statamic\\Forms\\SendEmails::dispatch(Object(Statamic\\Forms\\Submission), Object(Statamic\\Sites\\Site))
#53 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\FormController->submit(Object(Illuminate\\Http\\Request), Object(Statamic\\Forms\\Form))
#54 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('submit', Array)
#55 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\FormController), 'submit')
#56 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#57 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#58 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/simonbedard/web/sematos/app/Http/Middleware/ValidateBrowser.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ValidateBrowser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#69 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#76 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#77 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#78 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#79 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#80 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/simonbedard/web/sematos/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/simonbedard/web/sematos/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#100 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /Users/simonbedard/web/sematos/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#103 /Users/simonbedard/web/sematos/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#104 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#105 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#106 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#107 /Users/simonbedard/web/sematos/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#108 /Users/simonbedard/web/sematos/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#109 /Users/simonbedard/.composer/vendor/laravel/valet/server.php(219): require('/Users/simonbed...')
#110 {main}
```

### Versions

Statamic 3.2.17 Pro
Laravel 8.59.0
PHP 7.4.21
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
What are you expecting to happen if the field has no options?

**Comment by simonbedard12** [comment]
@jasonvarga I'm using the field to be able to add validations on my checkbox, but the actual value of the checkboxes comes from a collection. 

I'm not using the `{{ field }}` tag to generate my form input.  

Juste to be clear, i'm using the field to create a form not to create input field in the control panel.

**Comment by jasonvarga** [comment]
Got it thanks.
