### ISSUE TITLE
php 7.4 requirement error after upgrading to statamic 3.2.21

### ISSUE THREAD

**Issue by beckysoll** [statamic/cms#4709]
### Bug description

had this issue on both my local environment and on my server, when running php 7.3. worked fine, upgraded to 3.2.21, got the following error. no addons installed.

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.32`

laravel 8.47.0

contents of composer.json:

```json
{
    "name": "statamic/statamic",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^7.3 || ^8.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "statamic/cms": "3.2.20"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.3.6",
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "pre-update-cmd": [
            "Statamic\\Console\\Composer\\Scripts::preUpdateCmd"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

### How to reproduce

running php 7.3, upgrade from 3.2.20 to 3.2.21 via cp

### Logs

```shell
[2021-11-11 17:24:52] local.ERROR: include(/Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/../statamic/cms/src/Providers/StatamicServiceProvider.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/../statamic/cms/src/Providers/StatamicServiceProvider.php): failed to open stream: No such file or directory at /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/rsoll/Do...', 571, Array)
#1 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(571): include()
#2 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/Users/rsoll/Do...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Statamic\\\\Provid...')
#4 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): spl_autoload_call('Statamic\\\\Provid...')
#5 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider('Statamic\\\\Provid...')
#6 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register('Statamic\\\\Provid...')
#7 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load(Array)
#8 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#9 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#10 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#11 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#12 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#13 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#14 /Users/rsoll/.composer/vendor/laravel/valet/server.php(235): require('/Users/rsoll/Do...')
#15 {main}
"} 
[2021-11-11 17:24:53] local.ERROR: include(/Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/statamic/cms/src/Providers/StatamicServiceProvider.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/statamic/cms/src/Providers/StatamicServiceProvider.php): failed to open stream: No such file or directory at /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/rsoll/Do...', 571, Array)
#1 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(571): include()
#2 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/Users/rsoll/Do...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Statamic\\\\Provid...')
#4 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): spl_autoload_call('Statamic\\\\Provid...')
#5 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider('Statamic\\\\Provid...')
#6 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register('Statamic\\\\Provid...')
#7 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load(Array)
#8 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#9 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#10 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#11 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#12 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#13 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#14 /Users/rsoll/.composer/vendor/laravel/valet/server.php(235): require('/Users/rsoll/Do...')
#15 {main}
"} 
[2021-11-11 17:24:54] local.ERROR: include(/Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/../statamic/cms/src/Providers/StatamicServiceProvider.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/../statamic/cms/src/Providers/StatamicServiceProvider.php): failed to open stream: No such file or directory at /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/rsoll/Do...', 571, Array)
#1 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(571): include()
#2 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/Users/rsoll/Do...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Statamic\\\\Provid...')
#4 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): spl_autoload_call('Statamic\\\\Provid...')
#5 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider('Statamic\\\\Provid...')
#6 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register('Statamic\\\\Provid...')
#7 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load(Array)
#8 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#9 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#10 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#11 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#12 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#13 /Users/rsoll/Documents/Documents - SOLLR-MAC/1 repos/camsys.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#14 /Users/rsoll/.composer/vendor/laravel/valet/server.php(235): require('/Users/rsoll/Do...')
#15 {main}
"} 
[2021-11-11 17:25:08] local.ERROR: Composer Process: ./composer.json has been updated
Running composer update statamic/cms --with-dependencies
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Dependency "guzzlehttp/guzzle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "laravel/framework" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading statamic/cms (v3.2.20 => v3.2.21)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' may remediate them.
- Upgrading statamic/cms (v3.2.20 => v3.2.21): Extracting archive
- Installing statamic/cms (dist): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan statamic:install --ansi
100 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

### Versions

all stated above

### Installation

Fresh statamic/statamic site via CLI

**Comment by jesseleite** [comment]
I just ran a composer install with php 7.3 while using that composer.json and wasn't able to reproduce the error 🤔  What do you get when you run the following in the app root?

```
composer why php | grep 'requires.*php.*7\.4'
```

**Comment by beckysoll** [comment]
i tried running that and i get nothing at all?

**Comment by jasonvarga** [comment]
Did you do the composer update or did someone else on your team do it?

**Comment by beckysoll** [comment]
i am a 1 person team for this...

Sorry it took me a while to follow up, some other projects had my
attention. I then was having an issue running updates at all, getting a
''sh: line 0: exec: : not found" error in the cp when trying to update. I
recently switched computers, so i realized had to update the path, was then
able to run the update (this time in the CLI not in the CP)... and now i'm
not having the error. i pushed the update to my server and it's working
there as well... honestly i have no idea what has changed other than i
updated in the CLI instead and a couple of updates have been released
since. But hey, it's working! so...thanks for the help.
