### ISSUE TITLE
On search TAG: Object of class Statamic\Entries\Entry could not be converted to string

### ISSUE THREAD

**Issue by jdivins** [statamic/cms#4981]
### Bug description

I have upgraded Statamic from 3.2.26 to 3.2.27
Now when I run this code:
`{{ search:results as="results" }}            
{{ /search:results }}`
This error appears:
`Object of class Statamic\Entries\Entry could not be converted to string
`
I have this content on storage/statamic/search/default.json:
`{"entry::6a7fd96d-c0f4-4429-bc1a-edfddef2a336":{"title":"DISPLAY"}}`

### How to reproduce

- Install [Peak](https://peak.studio1902.nl/)
- Install 3.2.26 statamic version
- Create a page
- Use search on the frontend and you will see the result
- Upgrade Statamic to 3.2.27 o 3.2.28
- Update cache and search
- Search again on frontend
- The error **Object of class Statamic\Entries\Entry could not be converted to string** will appear

### Logs

```"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Object of class Statamic\\Entries\\Entry could not be converted to string at /Users/jordidivins/feines/revo-statamic/resources/views/search.antlers.html:0)
[stacktrace]
#0 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(567): ()
#1 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(567): array_intersect(Array, Array)
#2 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Query/IteratorBuilder.php(88): Illuminate\\Support\\Collection->intersect(Object(Statamic\\Data\\DataCollection))
#3 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Query/IteratorBuilder.php(65): Statamic\\Query\\IteratorBuilder->intersectFromWhereClause(Object(Statamic\\Data\\DataCollection), Object(Statamic\\Data\\DataCollection), Array)
#4 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(749): Statamic\\Query\\IteratorBuilder->Statamic\\Query\\{closure}(Object(Statamic\\Data\\DataCollection), Array, 1)
#5 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Query/IteratorBuilder.php(66): Illuminate\\Support\\Collection->reduce(Object(Closure))
#6 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Query/IteratorBuilder.php(37): Statamic\\Query\\IteratorBuilder->filterWheres(Object(Statamic\\Data\\DataCollection))
#7 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Query/IteratorBuilder.php(21): Statamic\\Query\\IteratorBuilder->getFilteredItems()
#8 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Tags/Concerns/GetsQueryResults.php(25): Statamic\\Query\\IteratorBuilder->get()
#9 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Search/Tags.php(43): Statamic\\Search\\Tags->getQueryResults(Object(Statamic\\Search\\Comb\\Query))
#10 [internal function]: Statamic\\Search\\Tags->results()
#11 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/View/Antlers/Engine.php(159): call_user_func(Array)
#12 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'search', Array, '\
            {{...', Array)
#13 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array(Array, Array)
#14 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('\
\
\
\
<main class...', Array)
#15 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('\
\
{{ section:se...', Array)
#16 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jordidiv...', '{{#\
\\t@name Sear...', Array)
#17 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jordidiv...', Array)
#18 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#19 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#20 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/View/View.php(94): Illuminate\\View\\View->render()
#21 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Controllers/FrontendController.php(73): Statamic\\View\\View->render()
#22 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\FrontendController->route(Object(Illuminate\\Http\\Request), 'search', Array)
#23 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('route', Array)
#24 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\FrontendController), 'route')
#25 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#26 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#27 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#44 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#52 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#53 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#54 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#55 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/jordidivins/feines/revo-statamic/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/jordidivins/feines/revo-statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/jordidivins/feines/revo-statamic/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/jordidivins/feines/revo-statamic/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#82 /Users/jordidivins/feines/revo-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#83 /Users/jordidivins/feines/revo-statamic/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#84 /Users/jordidivins/.composer/vendor/laravel/valet/server.php(235): require('/Users/jordidiv...')
#85 {main}
```

### Versions

When the error happens:

Statamic 3.2.28 Pro
Laravel 8.77.1
PHP 8.0.12
revo/bard-extensions dev-main

When not:
Statamic 3.2.26 Pro
Laravel 8.77.1
PHP 8.0.12
revo/bard-extensions dev-main

### Installation

Starter Kit using via CLI

**Comment by ryanmitchell** [comment]
I came across this issue too and fixed in it a PR on the query builder. See if this works for you:
https://github.com/statamic/cms/blob/26577983e41948b573acc91d2b74b7f6328d9091/src/Query/IteratorBuilder.php#L85-L95

**Comment by jdivins** [comment]
Yes It solves the problem. Thank you @ryanmitchell

**Comment by duncanmcclean** [comment]
@ryanmitchell Which pull request fixes this? If you add `Fixes #4981` to the PR, it will close this issue when the PR is merged 😃

**Comment by ryanmitchell** [comment]
@duncanmcclean looks like @jdivins beat me to it

**Comment by ryanmitchell** [comment]
@duncanmcclean this can be closed as it was merged yesterday - https://github.com/statamic/cms/commit/34550e17ad20eb7893f21cf26509d7c303ac595b

**Comment by duncanmcclean** [comment]
Done - I think the 'Fixes #XYZ' bit needs to be in the PR description instead of in a comment for it to close the related issue.
