### ISSUE TITLE
Updating after a while gives error editing any blueprint and any collection item that has a taxonomy

### ISSUE THREAD

**Issue by rustypaul** [statamic/cms#5067]
### Bug description

We're running 3.0.27 currently, and I'm trying to update our site to the latest version. Upon doing that though, everything looks ok until I try to edit a blueprint. This can be any of our existing blueprints or a newly created one. We get the following error

`array_merge(): Argument #2 must be of type array, null given`

We also get the following error when we try to edit any collection item whose blueprint / fieldset uses a taxonomy! All the others work ok, if I remove the taxonomy manually from the blueprint it lets me in again (using vscode as I can't edit in the control panel).

`count(): Argument #1 ($value) must be of type Countable|array, string given`

I feel like I'm probably missing something as part of the update but It looks like it's done the relevant changes listed in the 3.1 and 3.2 updates.

### How to reproduce

**Updating from: support details**
Statamic 3.0.27 Pro
Laravel 6.20.3
PHP 7.3.30
pecotamic/bard-hr 0.9.2
spatie/statamic-responsive-images 1.3.0

We updated using 

```
npm update
composer install && composer update
```

**After update: support details**
Statamic 3.2.30 Pro
Laravel 6.20.44
PHP 7.3.30
pecotamic/bard-hr 0.9.2
spatie/statamic-responsive-images 1.8.0

### Logs

```shell
[2022-01-13 17:54:49] local.ERROR: array_merge(): Argument #2 must be of type array, null given {"userId":"1b8041a0-b445-4c05-b7d5-96438b2fa9b2","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): array_merge(): Argument #2 must be of type array, null given at /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fields/FieldTransformer.php:72)
[stacktrace]
#0 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fields/FieldTransformer.php(72): array_merge(Array, NULL)
#1 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fields/FieldTransformer.php(62): Statamic\\Fields\\FieldTransformer::referenceFieldToVue(Array)
#2 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/View/Composers/FieldComposer.php(33): Statamic\\Fields\\FieldTransformer::toVue(Array)
#3 [internal function]: Statamic\\Http\\View\\Composers\\FieldComposer->Statamic\\Http\\View\\Composers\\{closure}(Array, 5)
#4 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#5 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/View/Composers/FieldComposer.php(34): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(685): Statamic\\Http\\View\\Composers\\FieldComposer->Statamic\\Http\\View\\Composers\\{closure}(Object(Statamic\\Fields\\Fieldset), 'content_-_lates...')
#7 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/View/Composers/FieldComposer.php(36): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#8 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/View/Composers/FieldComposer.php(22): Statamic\\Http\\View\\Composers\\FieldComposer->fieldsets()
#9 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(124): Statamic\\Http\\View\\Composers\\FieldComposer->compose(Object(Illuminate\\View\\View))
#10 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(162): Illuminate\\View\\Factory->Illuminate\\View\\Concerns\\{closure}(Object(Illuminate\\View\\View))
#11 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(366): Illuminate\\View\\Factory->Illuminate\\View\\Concerns\\{closure}('composing: stat...', Array)
#12 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('composing: stat...', Array)
#13 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(177): Illuminate\\Events\\Dispatcher->dispatch('composing: stat...', Array)
#14 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(124): Illuminate\\View\\Factory->callComposer(Object(Illuminate\\View\\View))
#15 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#16 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#17 /Users/paul/Documents/Sites/bunch2/vendor/symfony/http-foundation/Response.php(205): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#18 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#19 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#20 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#21 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'configure field...')
#24 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#53 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#54 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#55 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#56 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/paul/Documents/Sites/bunch2/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/paul/Documents/Sites/bunch2/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#79 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#80 /Users/paul/Documents/Sites/bunch2/public_html/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#81 /Users/paul/.composer/vendor/laravel/valet/server.php(235): require('/Users/paulmani...')
#82 {main}
"} 
[2022-01-13 17:55:50] local.ERROR: count(): Argument #1 ($value) must be of type Countable|array, string given {"userId":"1b8041a0-b445-4c05-b7d5-96438b2fa9b2","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, string given at /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fieldtypes/Terms.php:259)
[stacktrace]
#0 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fieldtypes/Terms.php(259): count('topics')
#1 [internal function]: Statamic\\Fieldtypes\\Terms->Statamic\\Fieldtypes\\{closure}(Object(Statamic\\Fields\\Blueprint), 0)
#2 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#3 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fieldtypes/Terms.php(262): Illuminate\\Support\\Collection->map(Object(Closure))
#4 [internal function]: Statamic\\Fieldtypes\\Terms->Statamic\\Fieldtypes\\{closure}('topics', 0)
#5 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#6 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(285): Illuminate\\Support\\Collection->map(Object(Closure))
#7 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fieldtypes/Terms.php(263): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#8 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fieldtypes/Relationship.php(122): Statamic\\Fieldtypes\\Terms->getCreatables()
#9 /Users/paul/Documents/Sites/bunch2/vendor/statamic/cms/src/Fields/Field.php(325): Statamic\\Fieldtypes\\Relationship->preload()
#10 /Users/paul/Documents/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Statamic\\Fields\\Field->meta()
#11 [internal functi
```

### Versions

**Updating from:**
Statamic 3.0.27 Pro
Laravel 6.20.3
PHP 7.3.30
pecotamic/bard-hr 0.9.2
spatie/statamic-responsive-images 1.3.0

**After update:**
Statamic 3.2.30 Pro
Laravel 6.20.44
PHP 7.3.30
pecotamic/bard-hr 0.9.2
spatie/statamic-responsive-images 1.8.0

### Installation

Starter Kit using via CLI

### Additional details

I'm trying to update this on my local machine using laravel prior to running it on our test server.

**composer.json**
```
{
    "name": "statamic/statamic-starter-bunch2",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "starter", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^1.0",
        "pecotamic/bard-hr": "^0.9.2",
        "spatie/laravel-sitemap": "^5.8",
        "spatie/statamic-responsive-images": "^1.2",
        "statamic/cms": "^3.0.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.1",
        "facade/ignition": "^1.3",
        "filp/whoops": "^2.0",
        "nunomaduro/collision": "^3.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "pre-update-cmd": [
            "Statamic\\Console\\Composer\\Scripts::preUpdateCmd"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ]
    }
}

```

**composer.lock**
[composer.lock.txt](https://github.com/statamic/cms/files/7865120/composer.lock.txt)

**Comment by rustypaul** [comment]
This also happens with php7.4 installed

**Comment by rustypaul** [comment]
I've closed this as it's probably not an issue, didn't realise I could raise it as a discussion in troubleshooting. Sorry!
