### ISSUE TITLE
starts_with doesn't accept £ param strings

### ISSUE THREAD

**Issue by mynetx** [statamic/cms#5128]
### Bug description

I'm trying to set some CSS classes on a box if the contained string starts with a Pound sign.
However, I'm seeing an error when trying to do so:

```
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected token ":" on line 5 of: <td class=" px-1 py-3 border-b-2 border-gray-200 text-center align-middle <?php if (true:£): ?> font-semibold text-water-500 <?php endif; ?> " >
```

### How to reproduce

1. Store a text field starting with an “£”.
2. Try to call the `starts_with` modifier.

```html
<td class="
        px-1 py-3
        border-b-2 border-gray-200
        text-center align-middle
        {{ if text|starts_with:£ }}
            font-semibold text-water-500
        {{ /if }}
    "
>
```

Using this block, however, works just fine – using an “A”:
```html
        {{ if text|starts_with:A }}
            font-semibold text-water-500
        {{ /if }}
```

### Logs

```shell
[previous exception] [object] (Statamic\\View\\Antlers\\SyntaxError(code: 0): syntax error, unexpected token \":\" on line 5 of:

<td class=\"
        px-1 py-3
        border-b-2 border-gray-200
        text-center align-middle
        <?php if (true:£): ?>
            font-semibold text-water-500
        <?php endif; ?>
    \"
>
    <?php if ('YES' === 'YES'): ?>
        {{ svg:checkmark class=\"text-green-500 inline-block w-6 h-6\" }}

    <?php elseif ('YES' === 'NO'): ?>
        {{ svg:crossmark class=\"text-green-500 inline-block w-6 h-6\" }}

    <?php else: ?>
        {{ text }}
    <?php endif; ?>
</td>
 at /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php:1342)
[stacktrace]
#0 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(716): Statamic\\View\\Antlers\\Parser->parsePhp('<td class=\"\
   ...')
#1 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(172): Statamic\\View\\Antlers\\Parser->parseConditionPairs('<td class=\"\
   ...', Array)
#2 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<td class=\"\
   ...', Array)
#3 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jm/Web/s...', '<td class=\"\
   ...', Array)
#4 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jm/Web/s...', Array)
#5 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#6 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#8 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('page.item.featu...')
#9 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('page.item.featu...')
#10 [internal function]: Statamic\\Tags\\Tags->__call('page.item.featu...', Array)
#11 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(159): call_user_func(Array)
#12 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#13 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array(Array, Array)
#14 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(341): Statamic\\View\\Antlers\\Parser->parseCallbackTags('            <tr...', Array)
#15 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(288): Statamic\\View\\Antlers\\Parser->parseLoopInstance('            <tr...', Array)
#16 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}(Array, 0)
#17 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(677): array_map(Object(Closure), Array, Array)
#18 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(289): Illuminate\\Support\\Collection->map(Object(Closure))
#19 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(223): Statamic\\View\\Antlers\\Parser->parseLoopVariables('<table class=\"w...', Array)
#20 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(175): Statamic\\View\\Antlers\\Parser->parseVariables('<table class=\"w...', Array)
#21 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<table class=\"w...', Array)
#22 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jm/Web/s...', '<table class=\"w...', Array)
#23 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jm/Web/s...', Array)
#24 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#25 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#26 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#27 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('page.item.featu...')
#28 /Users/jm/Web/some-project/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('page.item.featu...')
#29 [internal function]: Statamic\\Tags\\Tags->__call('page.item.featu...', Array)
#30 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(159): call_user_func(Array)
#31 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#32 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array(Array, Array)
#33 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<!-- Hero stage...', Array)
#34 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<!-- Hero stage...', Array)
#35 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/jm/Web/s...', '<!-- Hero stage...', Array)
#36 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/jm/Web/s...', Array)
#37 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#38 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#39 /Users/jm/Web/some-project/vendor/statamic/cms/src/View/View.php(94): Illuminate\\View\\View->render()
#40 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Responses/DataResponse.php(154): Statamic\\View\\View->render()
#41 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Responses/DataResponse.php(45): Statamic\\Http\\Responses\\DataResponse->contents()
#42 /Users/jm/Web/some-project/vendor/statamic/cms/src/Structures/Page.php(382): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#43 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#44 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#45 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#46 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/jm/Web/some-project/vendor/withcandour/aardvark-seo/src/Http/Middleware/RedirectsMiddleware.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): WithCandour\\AardvarkSeo\\Http\\Middleware\\RedirectsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/jm/Web/some-project/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#65 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#73 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#74 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#75 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#76 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/jm/Web/some-project/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/jm/Web/some-project/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/jm/Web/some-project/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /Users/jm/Web/some-project/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#100 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#103 /Users/jm/Web/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#104 /Users/jm/Web/some-project/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#105 /Users/jm/.composer/vendor/laravel/valet/server.php(234): require('/Users/jm/Web/s...')
#106 {main}
"}
```

### Versions

Statamic 3.2.31 Pro
Laravel 8.76.2
PHP 8.1.2
doublethreedigital/duplicator 2.1.0
rias/statamic-color-swatches 2.0.5
withcandour/aardvark-seo 2.0.21

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
I suspect (but haven't confirmed yet) that this is solved by the new parser.

**Comment by jasonvarga** [comment]
Confirmed.

**Comment by mynetx** [comment]
When will it be out? I had to build a custom modifier for now…

**Comment by jasonvarga** [comment]
It'll be in 3.3 but we don't have a date yet. Stick with your modifier for now.
