### ISSUE TITLE
3.3 - Entry fields broken in GraphQL 

### ISSUE THREAD

**Issue by DanielDarrenJones** [statamic/cms#5366]
### Bug description

After updating to v3.3 my GraphQL queries stopped working where I had an entry field, these are nested within a replicator, so I am unsure whether it's specifically the replicator causing the problem or rather entry fields in general.

<img width="1512" alt="Screenshot 2022-02-28 at 01 19 11" src="https://user-images.githubusercontent.com/8768709/155996910-8bad39c1-93ee-42b5-adfc-91619a63ff34.png">

### How to reproduce

Create a replicator with a set and add an entry field inside it, attempt to query the field using GraphQL.

### Logs

```shell
[2022-02-28 01:16:40] local.ERROR: User Error: expected iterable, but did not find one for field Set_Replicator_HeroWithSlider.case_studies. {"exception":"[object] (GraphQL\\Error\\InvariantViolation(code: 0): User Error: expected iterable, but did not find one for field Set_Replicator_HeroWithSlider.case_studies. at /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Utils/Utils.php:333)
[stacktrace]
#0 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(878): GraphQL\\Utils\\Utils::invariant(false, 'User Error: exp...')
#1 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(761): GraphQL\\Executor\\ReferenceExecutor->completeListValue(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Stache\\Query\\EntryQueryBuilder))
#2 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Stache\\Query\\EntryQueryBuilder))
#3 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Stache\\Query\\EntryQueryBuilder))
#4 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), Array, Object(ArrayObject), Array)
#5 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), Array, Array, Object(ArrayObject))
#6 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\\Executor\\ReferenceExecutor->collectAndExecuteSubfields(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Array, Array)
#7 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(974): GraphQL\\Executor\\ReferenceExecutor->completeObjectValue(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#8 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(789): GraphQL\\Executor\\ReferenceExecutor->completeAbstractValue(Object(GraphQL\\Type\\Definition\\UnionType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#9 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue(Object(GraphQL\\Type\\Definition\\UnionType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#10 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(887): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\UnionType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#11 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(761): GraphQL\\Executor\\ReferenceExecutor->completeListValue(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#12 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#13 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#14 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), Object(Statamic\\Entries\\Entry), Object(ArrayObject), Array)
#15 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), Object(Statamic\\Entries\\Entry), Array, Object(ArrayObject))
#16 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\\Executor\\ReferenceExecutor->collectAndExecuteSubfields(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Array, Object(Statamic\\Entries\\Entry))
#17 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(974): GraphQL\\Executor\\ReferenceExecutor->completeObjectValue(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Entries\\Entry))
#18 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(789): GraphQL\\Executor\\ReferenceExecutor->completeAbstractValue(Object(GraphQL\\Type\\Definition\\InterfaceType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Entries\\Entry))
#19 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue(Object(GraphQL\\Type\\Definition\\InterfaceType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Entries\\Entry))
#20 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\InterfaceType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Statamic\\Entries\\Entry))
#21 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#22 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(264): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Object(ArrayObject))
#23 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\\Executor\\ReferenceExecutor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#24 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#25 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, NULL, Array, 'Page', NULL)
#26 /Users/danieljones/Dev/modn-statamic/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, NULL, Array, 'Page', NULL, NULL)
#27 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/GraphqlExecutionMiddleware.php(32): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, NULL, Array, 'Page', NULL)
#28 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(34): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\GraphqlExecutionMiddleware->handle('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL, Object(Closure))
#29 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->resolve(Array, Object(Closure))
#30 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Array)
#31 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AddAuthUserContextValueMiddleware.php(28): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->Rebing\\GraphQL\\Support\\ExecutionMiddleware\\{closure}('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL)
#32 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(34): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AddAuthUserContextValueMiddleware->handle('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL, Object(Closure))
#33 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->resolve(Array, Object(Closure))
#34 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Array)
#35 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AutomaticPersistedQueriesMiddleware.php(42): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->Rebing\\GraphQL\\Support\\ExecutionMiddleware\\{closure}('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL)
#36 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(34): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AutomaticPersistedQueriesMiddleware->handle('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL, Object(Closure))
#37 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->resolve(Array, Object(Closure))
#38 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Array)
#39 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/ValidateOperationParamsMiddleware.php(39): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->Rebing\\GraphQL\\Support\\ExecutionMiddleware\\{closure}('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL)
#40 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Support/ExecutionMiddleware/AbstractExecutionMiddleware.php(34): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\ValidateOperationParamsMiddleware->handle('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL, Object(Closure))
#41 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Rebing\\GraphQL\\Support\\ExecutionMiddleware\\AbstractExecutionMiddleware->resolve(Array, Object(Closure))
#42 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Array)
#43 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(115): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#44 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/GraphQL.php(157): Illuminate\\Pipeline\\Pipeline->thenReturn()
#45 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/GraphQL.php(140): Rebing\\GraphQL\\GraphQL->executeViaMiddleware(Array, 'default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL)
#46 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/GraphQL.php(126): Rebing\\GraphQL\\GraphQL->executeAndReturnResult('default', Object(GraphQL\\Type\\Schema), Object(Rebing\\GraphQL\\Support\\OperationParams), NULL, NULL)
#47 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/GraphQLController.php(43): Rebing\\GraphQL\\GraphQL->execute('default', Object(Rebing\\GraphQL\\Support\\OperationParams))
#48 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/Helpers.php(24): Rebing\\GraphQL\\GraphQLController->Rebing\\GraphQL\\{closure}(Object(GraphQL\\Server\\OperationParams))
#49 /Users/danieljones/Dev/modn-statamic/vendor/rebing/graphql-laravel/src/GraphQLController.php(40): Rebing\\GraphQL\\Helpers::applyEach(Object(Closure), Object(GraphQL\\Server\\OperationParams))
#50 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Rebing\\GraphQL\\GraphQLController->query(Object(Illuminate\\Http\\Request), Object(Laragraph\\Utils\\RequestParser), Object(Illuminate\\Config\\Repository), Object(Rebing\\GraphQL\\GraphQL))
#51 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('query', Array)
#52 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Rebing\\GraphQL\\GraphQLController), 'query')
#53 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#54 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#55 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/RequireStatamicPro.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\RequireStatamicPro->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/GraphQL/Middleware/CacheResponse.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\GraphQL\\Middleware\\CacheResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#66 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#67 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#68 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#69 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#70 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/danieljones/Dev/modn-statamic/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/danieljones/Dev/modn-statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/danieljones/Dev/modn-statamic/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/danieljones/Dev/modn-statamic/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#97 /Users/danieljones/Dev/modn-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#98 /Users/danieljones/Dev/modn-statamic/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#99 /Users/danieljones/.composer/vendor/laravel/valet/server.php(234): require('/Users/danieljo...')
#100 {main}
"}
```

### Versions

Statamic 3.3 beta (3.3.2)

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
It looks specific to entry fields inside Replicator. Top level entry fields work fine.

Nice find.
