### ISSUE TITLE
500 error for asset with corrupt/bad metadata

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#5370]
### Bug description

I'm listing assets using:

```php
Asset::query()
  ->where('container', $this->config('container', 'assets'))
  ->whereNull('alt')
  ->orderBy('last_modified', 'desc')
  ->limit(100)
  ->get()
  ->toAugmentedArray();
```

And my current client is upload assets with bad metadata somehow. I don't know how he creates them but it happens :-).

This triggers an error: DivisionByZeroError:
<img width="1522" alt="Screen_Shot_2022-02-28_at_21 11 54" src="https://user-images.githubusercontent.com/69107412/156054153-34d2b861-9363-4652-a1a6-0b1cc939f2bc.png">

I think somehow it would be better if these functions were a little more robust so stuff doesn't come crashing down.

### How to reproduce

Use this corrupted image: https://www.icloud.com/iclouddrive/02a0dK6IeFu1WHiQYFsfSW6FQ#corrupt

### Logs

```shell
[2022-02-28 20:09:31] local.ERROR: Division by zero {"userId":"057d191c-2a92-4544-96b1-653d155af73e","exception":"[object] (DivisionByZeroError(code: 0): Division by zero at /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Assets/Asset.php:608)
[stacktrace]
#0 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Data/AbstractAugmented.php(55): Statamic\\Assets\\Asset->ratio()
#1 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Data/AbstractAugmented.php(38): Statamic\\Data\\AbstractAugmented->get('ratio')
#2 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(16): Statamic\\Data\\AbstractAugmented->select(Array)
#3 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(21): Statamic\\Assets\\Asset->toAugmentedCollection(NULL)
#4 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Providers/CollectionsServiceProvider.php(159): Statamic\\Assets\\Asset->toAugmentedArray(NULL)
#5 [internal function]: Statamic\\Assets\\AssetCollection->Statamic\\Providers\\{closure}(Object(Statamic\\Assets\\Asset))
#6 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Providers/CollectionsServiceProvider.php(163): array_map(Object(Closure), Array)
#7 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(124): Statamic\\Assets\\AssetCollection->Statamic\\Providers\\{closure}()
#8 /Users/robdekort/Sites/spottery/app/Widgets/ImagesMissingAlt.php(29): Illuminate\\Support\\Collection->__call('toAugmentedArra...', Array)
#9 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(391): App\\Widgets\\ImagesMissingAlt->App\\Widgets\\{closure}()
#10 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->remember('widgets::Images...', Object(Carbon\\Carbon), Object(Closure))
#11 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#12 /Users/robdekort/Sites/spottery/app/Widgets/ImagesMissingAlt.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#13 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Controllers/CP/DashboardController.php(50): App\\Widgets\\ImagesMissingAlt->html()
#14 [internal function]: Statamic\\Http\\Controllers\\CP\\DashboardController->Statamic\\Http\\Controllers\\CP\\{closure}(Array, 0)
#15 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#16 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Controllers/CP/DashboardController.php(52): Illuminate\\Support\\Collection->map(Object(Closure))
#17 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Controllers/CP/DashboardController.php(20): Statamic\\Http\\Controllers\\CP\\DashboardController->getDisplayableWidgets(Object(Statamic\\Widgets\\Loader))
#18 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\DashboardController->index(Object(Statamic\\Widgets\\Loader))
#19 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#20 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\DashboardController), 'index')
#21 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#22 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#23 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#44 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#54 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#55 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#56 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#57 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/robdekort/Sites/spottery/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/robdekort/Sites/spottery/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/robdekort/Sites/spottery/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/robdekort/Sites/spottery/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#84 /Users/robdekort/Sites/spottery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#85 /Users/robdekort/Sites/spottery/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#86 /Users/robdekort/.composer/vendor/laravel/valet/server.php(234): require('/Users/robdekor...')
#87 {main}
"}
```

### Versions

Statamic 3.2.33 Pro
Laravel 8.83.0
PHP 8.1.2
No addons installed

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
I uploaded this image and got this error

```
Unsupported image type image/heic. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.
```

![image](https://user-images.githubusercontent.com/105211/156055351-da8bb0a2-cb46-4b62-8610-b4732da293a3.png)

Of course, we should fix the division by zero error that you're experiencing, but maybe that's a hint as to why your clients images are being funky.

It seems like maybe they are actually `heic` files that have just been given a `png` extension.

**Comment by robdekort** [comment]
Ah awesome find Jason. I use Imagick and that one seems it doesn't trigger this error.

**Comment by robdekort** [comment]
Instructed the client not to rename heic to png ;-)

**Comment by sjclark** [comment]
> Instructed the client not to rename heic to png ;-)

I love this ❤️  (sometimes I wonder why we bother, hope you sent an invoice)
