### ISSUE TITLE
Error `array_flip(): Can only flip string and integer values, entry skipped` since `3.2.28`

### ISSUE THREAD

**Issue by LorensoD** [statamic/cms#5441]
### Bug description

Since upgrading to `3.2.28`, every page throws a `array_flip(): Can only flip string and integer values, entry skipped` exception. 

It originates from `src/Entries/Entry.php:order()` and is caused by the change in https://github.com/statamic/cms/pull/4883/commits/6ea2e2d2b096a0ad7a2107a8c8d8eb187ed5e999. If I revery this change everything works.

### How to reproduce

- Multi-Site with a 'pages' Collection
- Load any page

### Logs

```
[previous exception] [object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): array_flip(): Can only flip STRING and INTEGER values! at /Users/site/resources/views/parts/_main_header.antlers.html:0)
[stacktrace]
#0 /Users/site/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(394): ()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_flip(): C...', '/Users/site/...', 394, Array)
#2 /Users/site/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(394): array_flip(Array)
#3 /Users/site/vendor/statamic/cms/src/Entries/Entry.php(390): Illuminate\\Support\\Collection->flip()
#4 /Users/site/vendor/statamic/cms/src/Data/AbstractAugmented.php(54): Statamic\\Entries\\Entry->order()
#5 /Users/site/vendor/statamic/cms/src/Data/AbstractAugmented.php(37): Statamic\\Data\\AbstractAugmented->get('order')
#6 /Users/site/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(16): Statamic\\Data\\AbstractAugmented->select(Array)
#7 /Users/site/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(21): Statamic\\Entries\\Entry->toAugmentedCollection(NULL)
#8 /Users/site/vendor/statamic/cms/src/Tags/Locales.php(141): Statamic\\Entries\\Entry->toAugmentedArray()
#9 /Users/site/vendor/statamic/cms/src/Tags/Locales.php(105): Statamic\\Tags\\Locales->getLocalizedData('sitede')
#10 [internal function]: Statamic\\Tags\\Locales->Statamic\\Tags\\{closure}(Array, 'sitede')
#11 /Users/site/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(677): array_map(Object(Closure), Array, Array)
#12 /Users/site/vendor/statamic/cms/src/Tags/Locales.php(118): Illuminate\\Support\\Collection->map(Object(Closure))
#13 /Users/site/vendor/statamic/cms/src/Tags/Locales.php(74): Statamic\\Tags\\Locales->addData(Object(Illuminate\\Support\\Collection))
#14 /Users/site/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(710): Statamic\\Tags\\Locales->Statamic\\Tags\\{closure}(Object(Illuminate\\Support\\Collection))
#15 /Users/site/vendor/statamic/cms/src/Tags/Locales.php(75): Illuminate\\Support\\Collection->pipe(Object(Closure))
#16 /Users/site/vendor/statamic/cms/src/Tags/Locales.php(27): Statamic\\Tags\\Locales->getLocales()
#17 [internal function]: Statamic\\Tags\\Locales->index()
#18 /Users/site/vendor/statamic/cms/src/View/Antlers/Engine.php(159): call_user_func(Array)
#19 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'locales', Array, '\
              ...', Array)
#20 /Users/site/vendor/statamic/cms/src/View/Antlers/Parser.php(578): call_user_func_array(Array, Array)
#21 /Users/site/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<!-- header sta...', Array)
#22 /Users/site/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\\View\\Antlers\\Parser->parse('<!-- header sta...', Array)
#23 /Users/site/vendor/statamic/cms/src/View/Antlers/Engine.php(95): Statamic\\View\\Antlers\\Parser->parseView('/Users/site/...', '<!-- header sta...', Array)
#24 /Users/site/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/site/...', Array)
#25 /Users/site/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#26 /Users/site/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#27 /Users/site/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#28 /Users/site/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('parts/main_head...')
#29 /Users/site/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('parts/main_head...')
#30 [internal function]: Statamic\\Tags\\Tags->__call('parts/mainHeade...', Array)

```

### Versions

Statamic 3.2.28 Pro
Laravel 8.80.0
PHP 7.4.27
aryehraber/statamic-captcha 1.8.0
doublethreedigital/duplicator 2.1.1
octoper/statamic-inline-assets dev-master
rias/statamic-redirect 1.10.3
statamic/ssg 0.9.0
withcandour/aardvark-seo 2.0.21

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Can you provide your `content/trees/collections/pages.yaml`?

**Comment by LorensoD** [comment]
@jasonvarga 

`content/trees/collections/siteio/pages.yaml`
```
tree:
  -
    entry: home
  -
    entry: 6c299015-d010-46a9-8e33-ba65fa151a1d
  -
    entry: fdbf62ab-c628-4633-af2f-ec4889f23985
  -
    entry: 8b0c74f7-28c8-48db-8ca6-e447990f58d5
  -
    entry: 11d26b16-b442-49de-a25e-c957d42c529f
  -
    entry: a5a9ca1a-ccd6-4e38-8215-596a29502676
  -
    entry: 77dffc4f-0007-45bb-89ee-88b7f00476ac
  -
    entry: 956ebc68-a273-401c-b207-785c437edb55
  -
    entry: 5d05e68c-8737-4fe1-bc54-b21b0ad5b7c0
  -
    entry: 7d559c53-1fe0-49d7-9707-235215988b37
  -
    entry: c3712c22-8dbe-4d84-b86a-1505d1cea477
...

```

**Comment by jasonvarga** [comment]
You cut it off.

**Comment by jasonvarga** [comment]
Okay. Maybe one of those IDs doesn't exist.

Just for testing, can you remove everything from that file except the first (home) item and clear your cache? The order would obviously be incorrect but I wonder if that resolves the error.

**Comment by LorensoD** [comment]
I found the issue!

One of my `pages.yaml` (I have a multisite) contained the following:
```yaml
tree:
  -
    entry: 2f9440da-6f3d-4404-9064-c07e451259a1
  - {  }
  -
    entry: 5fd671fe-d709-49b8-8e71-255806118faf
  -
    entry: ec4696ed-5bfb-438f-bb97-bcd8e82bbef1
...
```

An empty object, this was causing the issue.

@jasonvarga Thanks for your help!
