### ISSUE TITLE
3.3.0 - runtime parser breaks option_list modifier

### ISSUE THREAD

**Issue by rustypaul** [statamic/cms#5537]
### Bug description

If you use the [option_list](https://statamic.dev/modifiers/option_list) modifier with the new runtime antlers parser it gives you the following error

```
Error
Object of class Statamic\Taxonomies\LocalizedTerm could not be converted to string
```

### How to reproduce

We have an array like

```
relate_the_topic:
          - branding
          - communication
          - user-journeys
```

And using the following produces the error

```
{{ relate_the_topic | option_list }}
```

### Logs

```shell
[previous exception] [object] (Error(code: 0): Object of class Statamic\\Taxonomies\\LocalizedTerm could not be converted to string at /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Modifiers/CoreModifiers.php:1581)
[stacktrace]
#0 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Modifiers/CoreModifiers.php(1581): implode('|', Array)
#1 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Modifiers/Modify.php(199): Statamic\\Modifiers\\CoreModifiers->optionList(Array, Array, Array)
#2 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Modifiers/Modify.php(156): Statamic\\Modifiers\\Modify->runModifier('option_list', Array)
#3 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Modifiers/Modify.php(133): Statamic\\Modifiers\\Modify->modify('option_list', Array)
#4 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/ModifierManager.php(111): Statamic\\Modifiers\\Modify->__call('option_list', Array)
#5 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1213): Statamic\\View\\Antlers\\Language\\Runtime\\ModifierManager::evaluate(Array, Object(Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment), Object(Statamic\\View\\Antlers\\Language\\Nodes\\Modifiers\\ModifierChainNode), Array)
#6 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1229): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->applyModifiers(Array, Object(Statamic\\View\\Antlers\\Language\\Nodes\\Modifiers\\ModifierChainNode))
#7 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1459): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->adjustValue(Array, Object(Statamic\\View\\Antlers\\Language\\Nodes\\VariableNode))
#8 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(891): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->getValue(Object(Statamic\\View\\Antlers\\Language\\Nodes\\VariableNode))
#9 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(294): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->process(Array)
#10 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(317): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->processStatements(Array)
#11 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1562): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluate(Array)
#12 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(666): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#13 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Nodes/AntlersNode.php(417): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#14 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Nodes/AntlersNode.php(381): Statamic\\View\\Antlers\\Language\\Nodes\\AntlersNode->reduceParameterInterpolations(Object(Statamic\\View\\Antlers\\Language\\Nodes\\Parameters\\ParameterNode), Object(Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor), 'int_574e76ab83f...', Array)
#15 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1263): Statamic\\View\\Antlers\\Language\\Nodes\\AntlersNode->getParameterValues(Object(Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor), Array)
#16 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(666): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#17 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(368): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#18 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(643): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{# This partia...', Array)
#19 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Volumes/sites/...', '{{# This partia...', Array)
#20 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Volumes/sites/...', Array)
#21 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#22 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#23 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#24 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('partials/conten...')
#25 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('index')
#26 [internal function]: Statamic\\Tags\\Tags->__call('index', Array)
#27 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1323): call_user_func(Array)
#28 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1927): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#29 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(666): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#30 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(368): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#31 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(643): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{ bard_content...', Array)
#32 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Volumes/sites/...', '{{ bard_content...', Array)
#33 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Volumes/sites/...', Array)
#34 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#35 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#36 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#37 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('bard_content')
#38 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('index')
#39 [internal function]: Statamic\\Tags\\Tags->__call('index', Array)
#40 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1323): call_user_func(Array)
#41 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(666): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#42 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(368): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#43 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(643): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('<div class=\"mx-...', Array)
#44 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Volumes/sites/...', '<div class=\"mx-...', Array)
#45 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Volumes/sites/...', Array)
#46 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#47 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#48 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/View/View.php(94): Illuminate\\View\\View->render()
#49 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Responses/DataResponse.php(155): Statamic\\View\\View->render()
#50 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Responses/DataResponse.php(46): Statamic\\Http\\Responses\\DataResponse->contents()
#51 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#52 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(802): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#53 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(789): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#54 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#55 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#74 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#81 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#82 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#83 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#84 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#85 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Volumes/sites/Sites/bunch2/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#93 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /Volumes/sites/Sites/bunch2/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Volumes/sites/Sites/bunch2/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#103 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#106 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#107 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#108 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#109 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#110 /Volumes/sites/Sites/bunch2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#111 /Volumes/sites/Sites/bunch2/public_html/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#112 /Users/paul/.composer/vendor/laravel/valet/server.php(234): require('/Volumes/sites/...')
#113 {main}
"}
```

### Versions

Statamic 3.3.0 Pro
Laravel 8.83.5
PHP 8.1.2
pecotamic/bard-hr 0.9.2
pecotamic/sitemap 1.2.8
spatie/statamic-responsive-images 2.10.0

### Installation

Starter Kit using via CLI

### Additional details

Running on laravel valet on my local mac

**Comment by jasonvarga** [comment]
This is not unique to the Runtime parser or 3.3. It happens on 3.2 too.

You should use the raw values:

```
{{ relate_the_topic | raw | option_list }}
```

**Comment by rustypaul** [comment]
Hmmm, it works perfectly well with the regex parser though!?

I think you might want to update your documentation if this is the intended use.

**Comment by rustypaul** [comment]
Hmm, you could be right there (You usually are). It isn't outputting quite what I'd expect whereas with raw it does.

Updating the docs would be great. Just something to point you to the raw option when using a terms field.
