### ISSUE TITLE
Can't save entries after enabling Publish Dates - Carbon Error "Trailing Data" 

### ISSUE THREAD

**Issue by code-schoenberger** [statamic/cms#5546]
### Bug description

Enabling "Publish Dates" on a collection and adding the "Time enabled" option on the date field causes error when trying to save. Throws "Trailing Data" error which seems to come from `Carbon->createFromFormat()` in `Statamic\Entries\Entry.php`.

### How to reproduce

- Create a Collection
- Enable "Publish Dates" on the Collection
- Edit the "Date" field in the Collections Blueprint and enable the Time Picker option ("Time enabled")

Now try to save an Entry in that Collection with a **custom Time**.

### Logs

```shell
Trailing data at /Users/schoenberger/01—dev/wine-partners/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:676)
[stacktrace]
#0 /Users/schoenberger/01—dev/wine-partners/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(699): Carbon\\Carbon::rawCreateFromFormat('Y-m-d-Hi', '2022-03-16-1330...', NULL)
#1 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Entries/Entry.php(446): Carbon\\Carbon::createFromFormat('Y-m-d-Hi', '2022-03-16-1330...')
#2 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Support/FluentGetterSetter.php(130): Statamic\\Entries\\Entry->Statamic\\Entries\\{closure}('2022-03-16-1330...')
#3 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Support/FluentGetterSetter.php(97): Statamic\\Support\\FluentGetterSetter->runSetterLogic('2022-03-16-1330...')
#4 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Entries/Entry.php(448): Statamic\\Support\\FluentGetterSetter->args(Array)
#5 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(344): Statamic\\Entries\\Entry->date('2022-03-16-1330...')
#6 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->store(Object(Illuminate\\Http\\Request), Object(Statamic\\Entries\\Collection), Object(Statamic\\Sites\\Site))
#7 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#8 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController), 'store')
#9 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#10 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#11 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#32 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#42 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#43 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#44 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#45 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/schoenberger/01—dev/wine-partners/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/schoenberger/01—dev/wine-partners/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/schoenberger/01—dev/wine-partners/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 /Users/schoenberger/01—dev/wine-partners/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#73 /Users/schoenberger/01—dev/wine-partners/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#74 /Users/schoenberger/01—dev/wine-partners/server.php(21): require_once('/Users/schoenbe...')
#75 {main}
"}
```

### Versions

 Statamic 3.3.1 Pro
Laravel 8.83.5
PHP 8.0.16
edalzell/variable 1.0.4
jacksleight/statamic-bard-mutator 1.0.3
jacksleight/statamic-bard-texstyle 0.2.0
rias/statamic-button-box 2.0.3

_(also tested it on a fresh installation via Statamic CLI without any addons -> same error)_

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Can you show the yaml for that field in your blueprint?

**Comment by code-schoenberger** [comment]
Hi! 
This is the Date field in my .yaml blueprint file:
```
-
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
          instructions_position: above
          listable: hidden
          read_only: false
          mode: single
          time_enabled: true
          time_seconds_enabled: false
          full_width: false
          inline: false
          columns: 1
          rows: 1
```

**Comment by duncanmcclean** [comment]
Just copied that field into one of my blueprints and I wasn't able to run into the issue. 

Are you seeing this on all entries? Would you be able to provide an example of an entry you're facing the issue on - I reckon it's got to do with how the date is saved.

**Comment by code-schoenberger** [comment]
Hey! @duncanmcclean 

Was that a blueprint of a collection that has "Publish Dates" enabled though? 

Since the issue seems to be the only related to the "Publish Date" option as I just found out. Because if I disable the "Publish Dates" option on the collection and leave the "Date" field in my blueprint as it is (with "Time enabled" on), the entry will successfully save.

I do have this issue on all entries & collections, yes.
I can't share an example of a saved entry since it never let's me save with "Publish Dates" on.

The issue seems to be how the date is formatted when "Publish Dates" is enabled. 
The `Statamic\Entries\Entry.php(446)` (= `return Carbon::createFromFormat('Y-m-d-Hi', $date);`) expects the date to be formatted as 'Y-m-d-Hi' but gets / 'Y-m-d-Hi**s**':
<img width="1904" alt="Screenshot 2022-03-19 at 11 25 55 AM" src="https://user-images.githubusercontent.com/71724388/159117380-b23489aa-17d7-4c1a-8590-ef97106115ca.png">

**Comment by duncanmcclean** [comment]
Oh, I see it. It only seems to happen if you set a time. If you just have a date, then it'll work fine.

**Comment by code-schoenberger** [comment]
Exactly. 
And I do need the “Publish Dates” to work with the time as well.

**Comment by fordster78** [comment]
The date trailing error comes up when the time option is enabled but also when the "show seconds" is turned on as well

Been playing around and I think adding the following changes to the Entry.php file around line 446 will fix the issue.

`if (strlen($date) === 15) {
    return Carbon::createFromFormat('Y-m-d-Hi', $date);
}

return Carbon::createFromFormat('Y-m-d-His', $date);`

**Comment by code-schoenberger** [comment]
Exactly @fordster78 . As soon as there’s more than just the date it throws the error unfortunately.

I added the exact same fix to my `Entry.php`! Works like a charm. 

Hope they get to implement a fix themselves soon as well since it seems to be an easy one.

**Comment by fordster78** [comment]
@code-schoenberger I'll look at pulling the cms down  separately and submit a PR for this. Not done a PR before for Statamic so I'll need to work out on getting it working for local dev before I can do that.

Won't be until later tonight so if you or the statamic guys want to fix it with a PR before i submit my own feel free to. 😀

**Comment by aerni** [comment]
Running into the same issue.

Statamic 3.3.7 Pro
Laravel 9.8.1
PHP 8.0.14
No addons installed

**Comment by edalzell** [comment]
Pulling this PR into 3.3.10 works for me.

**Comment by Pixney-William** [comment]
I use v3.3.10 and have this issue.

**Comment by Pixney-William** [comment]
```
[2022-05-04 11:27:44] production.ERROR: Trailing data {"userId":"e8ca6774-96c6-4df3-9627-03d1f6a23d9c","exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Trailing data at /.../vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:676)
[stacktrace]
#0 /home/ploi/SOMETHING/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(699): Carbon\\Carbon::rawCreateFromFormat()
#1 /home/ploi/SOMETHING/vendor/statamic/cms/src/Entries/Entry.php(446): Carbon\\Carbon::createFromFormat()
#2 /home/ploi/SOMETHING/vendor/statamic/cms/src/Support/FluentGetterSetter.php(130): Statamic\\Entries\\Entry->Statamic\\Entries\\{closure}()
#3 /home/ploi/SOMETHING/vendor/statamic/cms/src/Support/FluentGetterSetter.php(97): Statamic\\Support\\FluentGetterSetter->runSetterLogic()
#4 /home/ploi/SOMETHING/vendor/statamic/cms/src/Entries/Entry.php(448): Statamic\\Support\\FluentGetterSetter->args()
#5 /home/ploi/SOMETHING/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(202): Statamic\\Entries\\Entry->date()
#6 /home/ploi/SOMETHING/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->update()
#7 /home/ploi/SOMETHING/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#8 /home/ploi/SOMETHING/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /home/ploi/SOMETHING/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#10 /home/ploi/SOMETHING/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
``

**Comment by martyf** [comment]
This has cropped up for a site for me in 3.3.12. 

Jason's #5870 PR corrects the issue (at line 461 - the return of the format date function).
