### ISSUE TITLE
Comment inside partial tags breaks runtime parser

### ISSUE THREAD

**Issue by potentweb** [statamic/cms#5646]
### Bug description

If you include a comment inside a partial tag you get the following exception:

ErrorException: Attempt to read property "name" on null

### How to reproduce

1. Install Statamic.
2. Switch to the runtime parser.
3. Create a partial.
4. Include something like this in your antlers view:
```
    {{ partial src="wrap" }}
        {{# comment #}}
        {{ content }}
    {{ /partial }}
```

### Logs

```shell
[2022-03-25 04:57:32] local.ERROR: Attempt to read property "name" on null {"userId":"db72bf72-6798-4fdc-89b8-240fb9e3ba9d","exception":"[object] (ErrorException(code: 0): Attempt to read property \"name\" on null at /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php:955)
[stacktrace]
#0 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(955): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1272): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->checkPartialForNamedSlots()
#3 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(666): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#4 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(368): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#5 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(643): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#6 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#7 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get()
#8 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#9 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#10 /mnt/c/working/runtime-test/vendor/statamic/cms/src/View/View.php(94): Illuminate\\View\\View->render()
#11 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Responses/DataResponse.php(155): Statamic\\View\\View->render()
#12 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Responses/DataResponse.php(46): Statamic\\Http\\Responses\\DataResponse->contents()
#13 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse()
#14 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(816): Statamic\\Structures\\Page->toResponse()
#15 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(803): Illuminate\\Routing\\Router::toResponse()
#16 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Router->prepareResponse()
#17 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#18 /mnt/c/working/runtime-test/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#20 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle()
#22 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle()
#24 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle()
#26 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle()
#28 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#32 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Pipeline\\Pipeline->then()
#43 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\\Routing\\Router->runRoute()
#45 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#47 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#50 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#52 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#54 /mnt/c/working/runtime-test/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#56 /mnt/c/working/runtime-test/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#58 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#61 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#63 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#64 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#66 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#68 /mnt/c/working/runtime-test/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#70 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#72 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#74 /mnt/c/working/runtime-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#75 /mnt/c/working/runtime-test/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#76 /home/linz/.config/composer/vendor/valeryan/valet-wsl/server.php(232): require('...')
#77 {main}
"}
```

### Versions

Statamic 3.3.3 Solo
Laravel 9.5.1
PHP 8.0.17
No addons installed

### Installation

Other (please explain)

### Antlers Parser

runtime (new)

### Additional details

Installed via composer create-project

**Comment by sjclark** [comment]
Can't reproduce that on my end - have you tried this on other partials / a fresh install?
