### ISSUE TITLE
Error w/ new static cache invalidation on non-multi-site

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6144]
### Bug description

Saving an entry on a page entry on a non-multi-site, throws an error.

### How to reproduce

1. Standard Statamic site,
2. turn on 1/2 measure static caching
3. try to save the home page

### Logs

```shell
[2022-06-02 23:12:35] staging.ERROR: Call to undefined method Statamic\Entries\Collection::absoluteUrl() {"userId":"eaa22a40-f78c-49a7-9cfb-424fd92fce80","exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Statamic\\Entries\\Collection::absoluteUrl() at /home/forge/staging.ltcconsulting.com/vendor/statamic/cms/src/Data/HasAugmentedInstance.php:109)
[stacktrace]
#0 /home/forge/staging.ltcconsulting.com/vendor/statamic/cms/src/StaticCaching/DefaultInvalidator.php(86): Statamic\\Entries\\Collection->__call()
#1 /home/forge/staging.ltcconsulting.com/vendor/statamic/cms/src/StaticCaching/DefaultInvalidator.php(38): Statamic\\StaticCaching\\DefaultInvalidator->invalidateCollectionUrls()
#2 /home/forge/staging.ltcconsulting.com/vendor/statamic/cms/src/StaticCaching/Invalidate.php(72): Statamic\\StaticCaching\\DefaultInvalidator->invalidate()
```

### Versions

```
Statamic 3.3.13 Solo
Laravel 9.16.0
PHP 8.1.6
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by hgrimelid** [comment]
I noticed the same error. The error disappeared after downgrading to Statamic 3.3.12
