### ISSUE TITLE
Filtering collection by taxonomy throws: Call to a member function collections() on null

### ISSUE THREAD

**Issue by yxyx-github** [statamic/cms#6162]
### Bug description

I created a fresh statamic project using the cli. I followed the Quick Start Guide and created a collection called Blog.
I have also added a taxonomy called "category" and added an item called "News". Of course, I also added this taxonomy to the Blog collection.
In my blog/index template I try to filter for those blog entries by taxonomy. Both with Antlers and Blade I receive the following error:
_"Call to a member function collections() on null"_
_vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php:141_

My blog/index.antlers.html looks like this:
`
{{ collection:blog taxonomy:category="News" }}
    <a href="{{ url }}" class="flex items-center justify-between p-5 border-t border-green-400 text-green-400 hover:text-green-900 hover:bg-green-400">
        <span>{{ title }}</span>
        <span class="text-green-900 text-sm">{{ date }}</span>
    </a>
{{ /collection:blog }}
`

I expect a list of blog entries as I receive it if I remove the "taxonomy:category" argument, filtered by my taxonomy.

### How to reproduce

You can find the whole repository here: https://github.com/yxyx-github/statamic-test

### Logs

```shell
[2022-06-06 19:16:01] local.ERROR: Call to a member function collections() on null {"userId":"a89f29cb-5bf3-40f8-b9df-cca07612dc06","exception":"[object] (Error(code: 0): Call to a member function collections() on null at /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Stores/TaxonomyTermsStore.php:141)
[stacktrace]
#0 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Stores/Store.php(43): Statamic\\Stache\\Stores\\TaxonomyTermsStore->handleFileChanges()
#1 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Query/QueriesTaxonomizedEntries.php(107): Statamic\\Stache\\Stores\\Store->index('associations')
#2 [internal function]: Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}(Object(Illuminate\\Support\\Collection), 'category')
#3 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map(Object(Closure), Array, Array)
#4 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(723): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#5 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(393): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Query/QueriesTaxonomizedEntries.php(110): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#7 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Query/QueriesTaxonomizedEntries.php(53): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysForTaxonomyWhereIn(Array)
#8 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(775): Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}(NULL, Array, 0)
#9 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Query/QueriesTaxonomizedEntries.php(56): Illuminate\\Support\\Collection->reduce(Object(Closure))
#10 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(63): Statamic\\Stache\\Query\\EntryQueryBuilder->addTaxonomyWheres()
#11 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Stache/Query/Builder.php(26): Statamic\\Stache\\Query\\EntryQueryBuilder->getFilteredKeys()
#12 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Tags/Concerns/GetsQueryResults.php(25): Statamic\\Stache\\Query\\Builder->get()
#13 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Tags/Collection/Entries.php(51): Statamic\\Tags\\Collection\\Entries->results(Object(Statamic\\Stache\\Query\\EntryQueryBuilder))
#14 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Tags/Collection/Collection.php(23): Statamic\\Tags\\Collection\\Entries->get()
#15 [internal function]: Statamic\\Tags\\Collection\\Collection->__call('blog', Array)
#16 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/View/Antlers/Engine.php(161): call_user_func(Array)
#17 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'collection', Array, '\
    <a href=\"{...', Array)
#18 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/View/Antlers/Parser.php(586): call_user_func_array(Array, Array)
#19 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/View/Antlers/Parser.php(179): Statamic\\View\\Antlers\\Parser->parseCallbackTags('antlers\
<sectio...', Array)
#20 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/View/Antlers/Parser.php(134): Statamic\\View\\Antlers\\Parser->parse('antlers\
<sectio...', Array)
#21 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Parser->parseView('/home/marvin/la...', 'antlers\
<sectio...', Array)
#22 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/home/marvin/la...', Array)
#23 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#24 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#25 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/View/View.php(100): Illuminate\\View\\View->render()
#26 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Responses/DataResponse.php(155): Statamic\\View\\View->render()
#27 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Responses/DataResponse.php(46): Statamic\\Http\\Responses\\DataResponse->contents()
#28 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#29 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(815): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#30 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(802): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#31 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#32 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#51 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#59 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#60 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#61 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#62 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /home/marvin/lampp/htdocs/statamic-test/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/marvin/lampp/htdocs/statamic-test/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /home/marvin/lampp/htdocs/statamic-test/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#89 /home/marvin/lampp/htdocs/statamic-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#90 /home/marvin/lampp/htdocs/statamic-test/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#91 {main}
"}
```

### Versions

Statamic 3.3.13 Solo
Laravel 9.16.0
PHP 8.1.0
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by ryanmitchell** [comment]
The issue is that your taxonomy slug is actually `news`, not `category`. Although you have a title of `category`, you'll notice the slug you set up for it its `news`.

`{{ collection:blog taxonomy:news="News" }} <a href="{{ url }}" class="flex items-center justify-between p-5 border-t border-green-400 text-green-400 hover:text-green-900 hover:bg-green-400"> <span>{{ title }}</span> <span class="text-green-900 text-sm">{{ date }}</span> </a> {{ /collection:blog }}` works for me

**Comment by yxyx-github** [comment]
Hello @ryanmitchell,
thank you so much for taking the time to help me with this simple beginner's mistake, I completely missed that up.
Now it works fine!
