### ISSUE TITLE
Live Preview throwing error if new entry (unsaved)

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6262]
### Bug description

If we create an entry, don't save it, then try to use Live Preview, we get an error.

The error is coming from the `locales` tag, it seems (see error).

### How to reproduce

Create an Articles entry, don't save, use Live Preview

See attachment in comment below

### Logs

```shell
[2022-06-28 15:20:34] local.ERROR: array_key_exists(): Argument #1 ($key) must be a valid array offset type {"userId":"cba0aed3-26f9-4ca9-a67f-8261a605d37b","exception":"[object] (TypeError(code: 0): array_key_exists(): Argument #1 ($key) must be a valid array offset type at /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:439)
[stacktrace]
#0 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(439): array_key_exists(Object(Statamic\\Fields\\Value), Array)
#1 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(65): Illuminate\\Support\\Collection->get(Object(Statamic\\Fields\\Value))
#2 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(22): Statamic\\Stache\\Stores\\BasicStore->getPath(Object(Statamic\\Fields\\Value))
#3 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(37): Statamic\\Stache\\Stores\\BasicStore->getItem(Object(Statamic\\Fields\\Value))
#4 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(32): Statamic\\Stache\\Repositories\\CollectionRepository->findByHandle(Object(Statamic\\Fields\\Value))
#5 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Data/DataRepository.php(49): Statamic\\Stache\\Repositories\\CollectionRepository->find(Object(Statamic\\Fields\\Value))
#6 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Data/DataRepository.php(27): Statamic\\Data\\DataRepository->attemptAllRepositories('find', Object(Statamic\\Fields\\Value))
#7 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Statamic\\Data\\DataRepository->find(Object(Statamic\\Fields\\Value))
#8 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Tags/Locales.php(162): Illuminate\\Support\\Facades\\Facade::__callStatic('find', Array)
#9 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Tags/Locales.php(26): Statamic\\Tags\\Locales->getData()
#10 [internal function]: Statamic\\Tags\\Locales->index()
#11 /Users/erin/Sites/zakat/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1428): call_user_func(Array)
#12 /Users/erin/Sites/zakat/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(702): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#13 /Users/erin/Sites/zakat/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(382): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#14 /Users/erin/Sites/zakat/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(760): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('<!DOCTYPE html>...', Array)
#15 /Users/erin/Sites/zakat/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/erin/Sit...', '<!DOCTYPE html>...', Array)
#16 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/erin/Sit...', Array)
#17 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#18 /Users/erin/Sites/zakat/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#19 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Tags/Partial.php(25): Illuminate\\View\\View->render()
#20 /Users/erin/Sites/zakat/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('simple::layouts...')
```

### Versions

```
Statamic 3.3.16 Pro
Laravel 9.19.0
PHP 8.1.7
aryehraber/statamic-captcha 1.8.0
aryehraber/statamic-uuid 2.1.0
doublethreedigital/duplicator 2.3.1
doublethreedigital/runway 2.3.9
edalzell/forma 1.2
jacksleight/statamic-bard-mutator 1.1.1
jacksleight/statamic-bard-texstyle 1.0.3
jonassiewertsen/statamic-livewire 2.9.0
statamic/seo-pro 3.1.0
swiftmade/statamic-clear-assets 1.1.0
transformstudios/events 4.0.6
transformstudios/front 1.10
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-main
transformstudios/review 3.3.2
transformstudios/simple dev-main
transformstudios/takeover-redirects dev-main
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by edalzell** [comment]
Working on a site that shows the error.

**Comment by edalzell** [comment]
To replicate, run the site attached and create a new Articles Entry, but don't save and hit the Live Preview button.

[live-preview.zip](https://github.com/statamic/cms/files/9005903/live-preview.zip)
