### ISSUE TITLE
single image Assets field is not displayed in the control panel

### ISSUE THREAD

**Issue by lukrate** [statamic/cms#6827]
### Bug description

When you set "Max Files" to 1 for the "Assets field" the preview of the image does not appear in the control panel. If "Max Files" is set to more than 1 no problem.

A Vue error is displayed in the console.

### How to reproduce

Set "Max Files" to 1 for the "Assets field"

### Logs

```shell
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'type')
    at a.isInLinkField (AssetsFieldtype.vue:327:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.isInLinkField (vue.common.prod.js:6:29650)
    at a.showPicker (AssetsFieldtype.vue:346:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.showPicker (vue.common.prod.js:6:29650)
    at fn (AssetsFieldtype.vue?d862:3:446)
    at Object.r [as default] (vue.common.prod.js:6:15520)
qe @ vue.common.prod.js:6
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'type')
    at a.isInLinkField (AssetsFieldtype.vue:327:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.isInLinkField (vue.common.prod.js:6:29650)
    at a.showPicker (AssetsFieldtype.vue:346:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.showPicker (vue.common.prod.js:6:29650)
    at fn (AssetsFieldtype.vue?d862:3:446)
    at Object.r [as default] (vue.common.prod.js:6:15520)
qe @ vue.common.prod.js:6
```

### Environment

```yaml
PHP 8.1
Statamic 3.3.42
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by arthurperton** [comment]
Thanks for the report @lukrate. I am not able to reproduce this by just setting Max Files to 1 for an Assets field. Could you share your blueprint yaml and maybe post a screenshot of the issue?
