### ISSUE TITLE
Statamic control panel crash when clicking on template or layout dropdown

### ISSUE THREAD

**Issue by somedude5001** [statamic/cms#6833]
### Bug description

Statamic control panel freezes and then crashes on the Configure Collection page when clicking on either the Template or Layout dropdown.

Also when trying to view a post after creating it with Statamic it always returns the error 'view [layout] not found'.

### How to reproduce

Install Statamic in to an existing laravel project, create a collection and then try to change the collection template.

### Logs

```shell
[2022-10-04 21:44:12] local.ERROR: View [layout] not found. {"userId":2,"exception":"[object] (InvalidArgumentException(code: 0): View [layout] not found. at /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
[stacktrace]
#0 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('layout', Array)
#1 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/View/Factory.php(138): Illuminate\\View\\FileViewFinder->find('layout')
#2 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(932): Illuminate\\View\\Factory->make('layout', Array, Array)
#3 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/View/View.php(174): view('layout')
#4 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/View/View.php(164): Statamic\\View\\View->layoutViewPath()
#5 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/View/View.php(143): Statamic\\View\\View->isUsingXmlLayout()
#6 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Controllers/FrontendController.php(51): Statamic\\View\\View->wantsXmlResponse()
#7 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\FrontendController->route(Object(Illuminate\\Http\\Request), 'articles/show', Array)
#8 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('route', Array)
#9 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\FrontendController), 'route')
#10 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#11 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#12 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/Localize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Spatie\\Permission\\Middlewares\\RoleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin|tester')
#27 /Users/admin/www/jamtoast1/jamtoastWebSite/app/Http/Middleware/SetDefaultLocaleForUrls.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SetDefaultLocaleForUrls->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#33 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'ipAddress', Object(Closure))
#34 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'ipAddress')
#35 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#41 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#49 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#50 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#51 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#52 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#79 /Users/admin/www/jamtoast1/jamtoastWebSite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#80 /Users/admin/www/jamtoast1/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#81 /Users/admin/.composer/vendor/laravel/valet/server.php(234): require('/Users/admin...')
#82 {main}
"}
```

### Environment

```yaml
Environment: local
Statamic: 3.3.42
PHP: 8.1.6
Composer: 2.4.2
Laravel: 9.34.0
Livewire: 2.10.7
spatie/laravel-permission: 5.5.5
User Database: mysql
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

### Additional details

When installing a fresh statamic project there are no issues. It just seems to be when installing statamic in to this project that it has a problem with templates.  Not sure if this is relevant but the projects public folder is outside of the laravel projects folder. So the folder structure is...

- Laravel Project Files
- public

**Comment by duncanmcclean** [comment]
Possibly related to #6643

**Comment by jasonvarga** [comment]
Can you provide your `config/view.php` file?

**Comment by somedude5001** [comment]
> Can you provide your `config/view.php` file?

Sorry for the late reply

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | View Storage Paths
    |--------------------------------------------------------------------------
    |
    | Most templating systems load templates from disk. Here you may specify
    | an array of paths that should be checked for your views. Of course
    | the usual Laravel view path has already been registered for you.
    |
    */

    'paths' => [
        resource_path('views'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled View Path
    |--------------------------------------------------------------------------
    |
    | This option determines where all the compiled Blade templates will be
    | stored for your application. Typically, this is within the storage
    | directory. However, as usual, you are free to change this value.
    |
    */

    'compiled' => env(
        'VIEW_COMPILED_PATH',
        realpath(storage_path('framework/views'))
    ),

];`

**Comment by somedude5001** [comment]
@jasonvarga I have finally found the issue. We have tens of thousands of blade files in a folder within the views directory (views/static). When clicking the Template dropdown whilst configuring collections it would hang because its trying to load all thousands of blade files in to the Template dropdown. 

I presumed that the template dropdown would only be interested in Antler files. Its my first time using Statamic so a noob mistake.

Is it possible to have Statamic only search within a specific folder (views/templates) as opposed to the whole views folder?

Thanks

**Comment by jasonvarga** [comment]
Ah!

You can add `folder: templates` to the fieldtype config.

**Comment by somedude5001** [comment]
Got it, thanks

**Comment by arthurperton** [comment]
Is this issue solved?
