### ISSUE TITLE
3.3.45 Column not found: 1054 Unknown column 'id' in 'where clause'

### ISSUE THREAD

**Issue by jhhazelaar** [statamic/cms#6917]
### Bug description

When trying to Link to Entry in navigation and we see an error at the bottom that says:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `users` where `id` in (1))
```

We use statamic in a existing laravel applicatie and we use a databse to authenticate users. The laravel application has a shared data model with other applications. In this data model the primary key of the user tabel is `ID_USER`. Statamic assumes that the primary key is `id`.

### How to reproduce

- Install Laravel and change the primary key of user to something different then `id`
- Install Statamic and setup authenticatie with a database
- Create collection with an Users field. For example a Author field with default current authenticated user
- Create navigation with created collection in 'Collections ' and add entry. See logs for error

### Logs

```shell
[2022-10-19 10:41:36] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `users` where `id` in (1)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `users` where `id` in (1)) at /vendor/laravel/framework/src/Illuminate/Database/Connection.php:759)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(421): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2636): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2624): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3160): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2625): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(699): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(683): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /vendor/statamic/cms/src/Query/EloquentQueryBuilder.php(56): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 /vendor/statamic/cms/src/Query/EloquentQueryBuilder.php(69): Statamic\\Query\\EloquentQueryBuilder->get()
#10 /vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Statamic\\Query\\EloquentQueryBuilder->first()
#11 /vendor/statamic/cms/src/Query/OrderedQueryBuilder.php(47): Statamic\\Query\\OrderedQueryBuilder->forwardCallTo(Object(Statamic\\Auth\\Eloquent\\UserQueryBuilder), 'first', Array)
#12 /vendor/statamic/cms/src/Fieldtypes/Users.php(141): Statamic\\Query\\OrderedQueryBuilder->__call('first', Array)
#13 /vendor/statamic/cms/src/Fieldtypes/Users.php(128): Statamic\\Fieldtypes\\Users->augment(1)
#14 /vendor/statamic/cms/src/Fieldtypes/Users.php(116): Statamic\\Fieldtypes\\Users->getItemsForPreProcessIndex(1)
#15 /vendor/statamic/cms/src/Fields/Field.php(322): Statamic\\Fieldtypes\\Users->preProcessIndex(1)
#16 /vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(67): Statamic\\Fields\\Field->preProcessIndex()
#17 /vendor/laravel/framework/src/Illuminate/Collections/Collection.php(770): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->Statamic\\Http\\Resources\\CP\\Entries\\{closure}(Object(Statamic\\CP\\Column), 2)
#18 /vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(71): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#19 /vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(41): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->values(Array)
#20 /vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->toArray(Object(Illuminate\\Http\\Request))
#21 /vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(241): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#22 /vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(883): Illuminate\\Http\\Resources\\Json\\JsonResource->jsonSerialize()
#23 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}(Object(Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry))
#24 /vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(891): array_map(Object(Closure), Array)
#25 [internal function]: Illuminate\\Support\\Collection->jsonSerialize()
#26 /vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(87): json_encode(Array, 0)
#27 /vendor/symfony/http-foundation/JsonResponse.php(51): Illuminate\\Http\\JsonResponse->setData(Array)
#28 /vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(32): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array, false)
#29 /vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(101): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)
#30 /vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(28): Illuminate\\Routing\\ResponseFactory->json(Array, 200, Array, 0)
#31 /vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(133): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#32 /vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(113): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse(Object(Illuminate\\Http\\Request))
#33 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(815): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#34 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(802): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#35 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#36 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#59 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#68 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#69 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#70 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#71 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#72 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#73 /vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#99 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#100 /public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#101 /Users/janhenk/.composer/vendor/laravel/valet/server.php(234): require('/Users/janhenk/...')
#102 {main}
```

### Environment

```yaml
Environment
Application Name: Laravel Statamic
Laravel Version: 9.36.2
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: laravel-statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendinblue
Queue: sync
Session: database

Localization
Installed: en, nl
LaravelLang\Attributes\Plugin: v2.0.6
LaravelLang\Lang\Plugin: 12.1.0
Protected Locales: en
Publisher Version: v14.3.3

Filament
Packages: filament, forms, notifications, support, tables
Version: v2.16.34
Views: NOT PUBLISHED

Statamic
Addons: 0
Antlers: regex
Version: 3.3.45 Solo
```

### Installation

Existing Laravel app

### Additional details

Repository for reproducing: https://github.com/jhhazelaar/laravel-statamic-user-primary-key

**Comment by jhhazelaar** [comment]
Updated 'How to reproduce':
- Added user field to collection.

**Comment by jhhazelaar** [comment]
Added repo with project with the error: https://github.com/jhhazelaar/laravel-statamic-user-primary-key

**Comment by ryanmitchell** [comment]
I think you'd need to add something like

```
    protected function column($column)
    {
        if ($column == 'id') {
            // do something to get the user model key  
        }   
        
        return parent::column($column);  
    }
```

to Statamic\Auth\Eloquent\UserQueryBuilder

Do you want to have a go at a PR for it?

**Comment by jhhazelaar** [comment]
@ryanmitchell nevermind. Your idea is way beter:
```php
protected function column($column)
    {
        return match ($column) {
            'id' => User::make()->model()->getKeyName(),
            default => $column,
        };
    }
```

**Comment by jhhazelaar** [comment]
New PR: https://github.com/statamic/cms/pull/6919

**Comment by robdekort** [comment]
Completely irrelevant to this issue but a bug report from Onderdendam? That is about 5 kilometers away from me. What are the odds! 👍

**Comment by jhhazelaar** [comment]
@robdekort LOL, I need to update my location. We moved to South of Spain this year, lived there for almost 5 years :-D

**Comment by robdekort** [comment]
That's definitely a coincidence. I'm delighted to read Concept7 is using Statamic. And what a lovely site. Great work. Make sure to [join all the fun people](https://discord.com/invite/j4aQmZv) on Discord.

**Comment by jasonvarga** [comment]
This was a lovely interaction.
