### ISSUE TITLE
Undefined array key "listener" when using Event::listen callback

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#7295]
### Bug description

I am seeing these errors in the server logs:
`[2023-01-04 12:03:13] production.ERROR: Undefined array key "listener" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"listener\" at /home/forge/website.ie/vendor/statamic/cms/src/Events/Subscriber.php:86)`

When this happens updates to asset references fail. This may be related to https://github.com/statamic/cms/issues/6431.

### How to reproduce

This seems to happen anytime I define a simple event listener with a callback:

**EventServiceProvider@boot**
```
Event::listen(function (EntrySaved $event) {

}
```

It doesn't happen if I define a Listener class.

### Logs

```shell
[2023-01-04 12:03:13] production.ERROR: Undefined array key "listener" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"listener\" at /home/forge/website.ie/vendor/statamic/cms/src/Events/Subscriber.php:86)
[stacktrace]
#0 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/forge/website.ie/vendor/statamic/cms/src/Events/Subscriber.php(86): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/forge/website.ie/vendor/statamic/cms/src/Providers/EventServiceProvider.php(47): Statamic\\Events\\Subscriber::normalizeRegisteredListener()
#3 [internal function]: Illuminate\\Events\\Dispatcher->Statamic\\Providers\\{closure}()
#4 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(795): array_filter()
#5 /home/forge/website.ie/vendor/statamic/cms/src/Providers/EventServiceProvider.php(48): Illuminate\\Support\\Arr::where()
#6 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(124): Illuminate\\Events\\Dispatcher->Statamic\\Providers\\{closure}()
#7 /home/forge/website.ie/vendor/statamic/cms/src/Events/Subscriber.php(49): Illuminate\\Events\\Dispatcher->__call()
#8 /home/forge/website.ie/vendor/statamic/cms/src/Events/Subscriber.php(68): Statamic\\Events\\Subscriber::disable()
#9 /home/forge/website.ie/vendor/statamic/cms/src/Data/DataReferenceUpdater.php(287): Statamic\\Events\\Subscriber::withoutListeners()
#10 /home/forge/website.ie/vendor/statamic/cms/src/Data/DataReferenceUpdater.php(66): Statamic\\Data\\DataReferenceUpdater->saveItem()
#11 /home/forge/website.ie/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(99): Statamic\\Data\\DataReferenceUpdater->updateReferences()
#12 [internal function]: Statamic\\Listeners\\UpdateAssetReferences->Statamic\\Listeners\\{closure}()
#13 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#14 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(739): Illuminate\\Support\\Arr::map()
#15 /home/forge/website.ie/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(100): Illuminate\\Support\\Collection->map()
#16 /home/forge/website.ie/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(48): Statamic\\Listeners\\UpdateAssetReferences->replaceReferences()
#17 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): Statamic\\Listeners\\UpdateAssetReferences->handleSaved()
#18 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle()
#19 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#23 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#24 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#25 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#27 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#28 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#29 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#31 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#32 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#33 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()
#34 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#35 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(326): Illuminate\\Queue\\Worker->runJob()
#36 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(146): Illuminate\\Queue\\Worker->runNextJob()
#37 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#38 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#39 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#40 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#41 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#42 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#43 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call()
#44 /home/forge/website.ie/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#45 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#46 /home/forge/website.ie/vendor/symfony/console/Application.php(1020): Illuminate\\Console\\Command->run()
#47 /home/forge/website.ie/vendor/symfony/console/Application.php(312): Symfony\\Component\\Console\\Application->doRunCommand()
#48 /home/forge/website.ie/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#49 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#50 /home/forge/website.ie/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#51 /home/forge/website.ie/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#52 {main}
"}
```

### Environment

```yaml
Environment
Laravel Version: 9.43.0
PHP Version: 8.1.12
Composer Version: 2.5.1
Environment: production
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single, slack
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 7
Antlers: regex
Version: 3.3.60 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 1.5.1
jonassiewertsen/statamic-livewire: 2.9.0
justbetter/statamic-image-optimize: 1.1.4
rias/statamic-redirect: 2.5.0
spatie/statamic-responsive-images: 2.14.4
statamic/seo-pro: 3.1.3
stuartcusackie/statamic-cache-requester: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by stuartcusackie** [comment]
Closing this and opening a new issue with a repo to demonstrate:
https://github.com/statamic/cms/issues/7352
