### ISSUE TITLE
Cannot visit any utilities pages

### ISSUE THREAD

**Issue by maxsolomon14** [statamic/cms#7396]
### Bug description

Anytime I visit a utilities page eg Git or PHPinfo it throws this error. I imagine it's probably me doing something wrong however I couldn't find any help in the discord so throwing it on here incase it is more widespread. Thanks for any help that may follow.
![Screenshot 2023-01-23 at 15 00 18](https://user-images.githubusercontent.com/45201764/214072508-fac0eda6-8e02-4f1e-abe4-4cfe0a007fd6.png)

### How to reproduce

Visit a utilities page on the CP eg /cp/utilities/git. It happens on all pages. Doesn't seem to happen on any other types of pages apart from the utilities pages.

### Logs

```shell
2023-01-23 14:59:06] local.ERROR: Target class [can] does not exist.
```

### Environment

```yaml
Statamic 3.3.65 Pro
Laravel 8.83.27
PHP 7.4.32
Stache Watcher Enabled
Static Caching half
4rn0/statamic-v3-image-optimizer 1.0.20
aryehraber/statamic-impersonator 2.4.1
aryehraber/statamic-logbook 2.1.0
rias/statamic-button-box 2.0.3
sortarad/extraextra 1.0.1
statamic/seo-pro 3.1.3
stoffelio/statamic-live-preview-tag 1.0.0
visuellverstehen/statamic-classify 2.4.0
webographen/statamic-admin-log 1.0.6
withcandour/aardvark-seo 2.0.30
xndbogdan/statamic-bard-text-color 2.4.1
```

### Installation

Existing Laravel app

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Can you provide the stack trace rather than just a screenshot of it? It'll be in your log file in `storage/logs`

**Comment by maxsolomon14** [comment]
> Can you provide the stack trace rather than just a screenshot of it? It'll be in your log file in `storage/logs`

Sorry sure
```
[2023-01-23 14:59:06] local.ERROR: Target class [can] does not exist. {"userId":"827e342c-0e26-493a-8582-aef48a66a0a9","exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [can] does not exist. at /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php:879)
[stacktrace]
#0 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('can')
#1 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('can', Array, true)
#2 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('can', Array)
#3 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('can', Array)
#4 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(206): Illuminate\\Foundation\\Application->make('can')
#5 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(180): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#6 /Users/max.solomon/Documents/Sites/businesscomparison/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 /Users/max.solomon/.composer/vendor/laravel/valet/server.php(234): require('/Users/max.solo...')
#8 {main}

[previous exception] [object] (ReflectionException(code: -1): Class can does not exist at /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php:877)
[stacktrace]
#0 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct('can')
#1 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('can')
#2 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('can', Array, true)
#3 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('can', Array)
#4 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('can', Array)
#5 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(206): Illuminate\\Foundation\\Application->make('can')
#6 /Users/max.solomon/Documents/Sites/businesscomparison/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(180): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 /Users/max.solomon/Documents/Sites/businesscomparison/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#8 /Users/max.solomon/.composer/vendor/laravel/valet/server.php(234): require('/Users/max.solo...')
#9 {main}
"} 

```

**Comment by jasonvarga** [comment]
Can you show your `app/Http/Kernel.php` file?

**Comment by maxsolomon14** [comment]
Ah thanks so much @jasonvarga, we had the can middleware commented out. Uncommenting fixes the issue, weird though as that has been like that for over a year but this error has only just been showing up.

**Comment by jasonvarga** [comment]
We recently started using it on some routes. Didn't consider that people would have removed it. Was there a reason for it?

**Comment by maxsolomon14** [comment]
To be honest I'm not entirely sure, I inherited this project a few months ago. I imagine they just weren't using the middleware but if I encounter any issues I'll put another comment up. Thanks for all your help, really appreciated.
