### ISSUE TITLE
Form validation empty required field throw error

### ISSUE THREAD

**Issue by mathamel** [statamic/cms#7682]
### Bug description

I have created a simple form, based on the example in the documentation

I have a text field required. If it is filled form submits and does as expected.

But if field is empty, it throws this error :

```
Statamic  \  Modifiers  \  ModifierNotFoundException
Modifier [value] not found
```

### How to reproduce

Maybe it is something it my stack

- Statamic 3.4
- Eloquent Driver
- Multisite
- antlers: runtime

Create a new form, add 2 fields 
email - validation: required + email
first_name - validation: required

use code from documentation to create the view

on frontend go to your form, enter an email and leave first_name emplty

error appears

Note: changing antlers engine to regex, I now have frontend validation and cannot submit the form.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/12539609/224372098-c426d01c-0e9d-4f3f-8a65-8e2191e27e96.png">

### Logs

```shell
[2023-03-10 16:28:11] local.ERROR: Modifier [value] not found {"userId":"7e703152-01fc-47e4-bf85-885c5deece62","exception":"[object] (Statamic\\Modifiers\\ModifierNotFoundException(code: 0): Modifier [value] not found at /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php:2018)
[stacktrace]
#0 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(691): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#1 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(379): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#2 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(757): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('<input\\n    clas...', Array)
#3 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/var/www/resour...', '<input\\n    clas...', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Statamic\\View\\Antlers\\Engine->get('/var/www/resour...', Array)
#5 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#6 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#7 /var/www/vendor/statamic/cms/src/Tags/Concerns/RendersForms.php(146): Illuminate\\View\\View->render()
#8 /var/www/vendor/statamic/cms/src/Forms/Tags.php(223): Statamic\\Forms\\Tags->getRenderableField(Object(Statamic\\Fields\\Field), 'form.contact_fo...', Object(Closure))
#9 [internal function]: Statamic\\Forms\\Tags->Statamic\\Forms\\{closure}(Object(Statamic\\Fields\\Field), 'email')
#10 /var/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#11 /var/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(768): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#12 /var/www/vendor/statamic/cms/src/Forms/Tags.php(222): Illuminate\\Support\\Collection->map(Object(Closure))
#13 /var/www/vendor/statamic/cms/src/Forms/Tags.php(66): Statamic\\Forms\\Tags->getFields('form.contact_fo...', false)
#14 /var/www/vendor/statamic/cms/src/Forms/Tags.php(35): Statamic\\Forms\\Tags->create()
#15 [internal function]: Statamic\\Forms\\Tags->__call('contactForm', Array)
#16 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1466): call_user_func(Array)
#17 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(691): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#18 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(379): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#19 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(757): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('\\n\\n{{ form:conta...', Array)
#20 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/var/www/resour...', '\\n\\n{{ form:conta...', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Statamic\\View\\Antlers\\Engine->get('/var/www/resour...', Array)
#22 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#23 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#24 /var/www/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\\View\\View->render()
#25 /var/www/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('forms/contact')
#26 /var/www/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\\Tags\\Partial->wildcard('forms/contact')
#27 [internal function]: Statamic\\Tags\\Tags->__call('forms/contact', Array)
#28 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1466): call_user_func(Array)
#29 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(691): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#30 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(379): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#31 /var/www/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(757): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{ if custom_pa...', Array)
#32 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(97): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/var/www/resour...', '{{ if custom_pa...', Array)
#33 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Statamic\\View\\Antlers\\Engine->get('/var/www/resour...', Array)
#34 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#35 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#36 /var/www/vendor/statamic/cms/src/View/View.php(98): Illuminate\\View\\View->render()
#37 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(151): Statamic\\View\\View->render()
#38 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(44): Statamic\\Http\\Responses\\DataResponse->contents()
#39 /var/www/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(888): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/www/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#64 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#71 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#72 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#73 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#74 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#75 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /var/www/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /var/www/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /var/www/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /var/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#93 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /var/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#102 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#103 /var/www/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#104 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Redbourne
Laravel Version: 9.52.4
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: redbourne.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
cnj/seotamic: 2.1.0
nfragkos/eloquenty: 1.3.1
phpsa/statamic-analytics: 1.4.0
statamic/eloquent-driver: 1.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

Can be noted that I have an issue related to another already reported bug with cache / multisite.

Also I will open another bug because I creating new collection throw error. I don't know if it is related or not.

**Comment by mathamel** [comment]
I have a little bit more info, when running regex the input with the required validation are like this : 

`<input class="w-full px-4 py-3  rounded border focus-visible:ring focus-visible:ring-primary-900 focus-visible:ring-opacity-60 bg-gray-100 text-gray-800 placeholder-gray-800 border-transparent" id="last_name" name="last_name" type="text" placeholder="Last Name" required>`

and when using 'runtime' it is wrong with a 1 instead:

`<input class="w-full px-4 py-3  rounded border focus-visible:ring focus-visible:ring-primary-900 focus-visible:ring-opacity-60 bg-gray-100 text-gray-800 placeholder-gray-800 border-transparent" id="last_name" name="last_name" type="text" placeholder="Last Name" 1="">`

**Comment by ryanmitchell** [comment]
Is this still an issue on the latest version of Statamic? If so, could you share the entire form template please?

**Comment by duncanmcclean** [comment]
I'm going to close this issue now.

If you're still experiencing this issue on the latest version of Statamic, please provide the Antlers template for your form and we'll re-open this issue and take another look. Thanks!
