### ISSUE TITLE
HasAugmentData::offsetGet($key) must be compatible with Model::offsetGet($offset)

### ISSUE THREAD

**Issue by Camaendir** [statamic/cms#8078]
### Bug description

I have a simple Statamic setup with two auth guards (as described in https://github.com/statamic/cms/pull/3143#issuecomment-793101991). My User Model is standard and extends `Illuminate\Foundation\Auth\User`. I wanted to create a custom antlers tag (similar to the existing `user` tag) which implements all `user` tag methods but for my `User` class. For that i want my `User` class to be augmentable. I added `implements Augmentable` and `use HasAugmentedData` to the User method. This results in the following error:
```
Declaration of Statamic\Data\HasAugmentedData::offsetGet($key) must be compatible with Illuminate\Database\Eloquent\Model::offsetGet($offset): mixed
```
Full error log: https://flareapp.io/share/v5pa9bkm#F1

I've tried fixing it by adding the return type to the methods in `Statamic\Data\HasAugmentedInstance` such that they are compatible with the Eloquent Model methods.

I then get a 500 error without any error page with the following error in the `laravel.log` (see full log below):
```
[2023-04-05 16:46:01] local.ERROR: Call to a member function fields() on null {"exception":"[object] (Error(code: 0): Call to a member function fields() on null at /somepath/my_statamic_site/vendor/statamic/cms/src/Structures/AugmentedPage.php:65)
```

### How to reproduce

- Create a blank Statamic site
- Use two auth guards (as described in https://github.com/statamic/cms/pull/3143#issuecomment-793101991)
- Install Laravel Breeze
- Have a User model which extends the `Illuminate\Foundation\Auth\User`
- Add a custom antlers Tag, which is a copy of the statamic `UserTag` replacing the `Statamic\Facades\User` with my User Model
- Try to make it augmentable by implementing `Augmentable` and using `HasAugmentedData` 
- Now the first error occurs, when accessing a site using the custom tag
- To try to fix the first error edit the `Statamic/cms/Data/HasAugmentedInstance.php` file and add return types to the following methods:
  - `offsetGet($key)` -> `offsetGet($key) :mixed`
  - `offsetSet($key, $value)` -> `offsetSet($key, $value) :void`
  - `offsetExists($key)` -> `offsetExists($key) :bool`
  - `offsetUnset($key)` -> `offsetUnset($key) :void`
- now the second error occurs (see logs)

### Logs

```shell
[2023-04-05 16:46:01] local.ERROR: Call to a member function fields() on null {"exception":"[object] (Error(code: 0): Call to a member function fields() on null at /somepath/my_statamic_site/vendor/statamic/cms/src/Structures/AugmentedPage.php:65)
[stacktrace]
#0 /somepath/my_statamic_site/vendor/statamic/cms/src/Entries/AugmentedEntry.php(16): Statamic\\Structures\\AugmentedPage->blueprintFields()
#1 /somepath/my_statamic_site/vendor/statamic/cms/src/Structures/AugmentedPage.php(28): Statamic\\Entries\\AugmentedEntry->keys()
#2 /somepath/my_statamic_site/vendor/statamic/cms/src/Data/AbstractAugmented.php(36): Statamic\\Structures\\AugmentedPage->keys()
#3 /somepath/my_statamic_site/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(21): Statamic\\Data\\AbstractAugmented->select(NULL)
#4 /somepath/my_statamic_site/vendor/statamic/cms/src/Data/HasAugmentedInstance.php(26): Statamic\\Structures\\Page->toAugmentedCollection(NULL)
#5 /somepath/my_statamic_site/vendor/statamic/cms/src/View/Cascade.php(166): Statamic\\Structures\\Page->toAugmentedArray()
#6 /somepath/my_statamic_site/vendor/statamic/cms/src/View/Cascade.php(98): Statamic\\View\\Cascade->hydrateContent()
#7 /somepath/my_statamic_site/vendor/statamic/cms/src/View/View.php(182): Statamic\\View\\Cascade->hydrate()
#8 /somepath/my_statamic_site/vendor/statamic/cms/src/View/View.php(58): Statamic\\View\\View->cascade()
#9 /somepath/my_statamic_site/vendor/statamic/cms/src/View/View.php(88): Statamic\\View\\View->gatherData()
#10 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Responses/DataResponse.php(151): Statamic\\View\\View->render()
#11 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Responses/DataResponse.php(44): Statamic\\Http\\Responses\\DataResponse->contents()
#12 /somepath/my_statamic_site/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#13 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(888): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#14 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#15 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#16 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /somepath/my_statamic_site/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#37 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#44 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#45 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#46 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#47 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#48 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#49 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /somepath/my_statamic_site/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /somepath/my_statamic_site/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /somepath/my_statamic_site/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#75 /somepath/my_statamic_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#76 /somepath/my_statamic_site/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#77 /myhomedirectory/.composer/vendor/laravel/valet/server.php(110): require('/myhomedirectory...')
#78 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.7
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: my_statamic_site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.11 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
If you want to add the `HasAugmentedInstance` trait to your Eloquent model, you'll need to make a copy of the class, and remove the `offset...` methods, like I have [in Runway](https://github.com/duncanmcclean/runway/blob/5.x/src/Data/HasAugmentedInstance.php#L11).
