### ISSUE TITLE
Users not searchable

### ISSUE THREAD

**Issue by schwemmer** [statamic/cms#8454]
### Bug description

When I add `users` to the searchables in my `config/statamic/search.php` config – as described in the docs here: https://statamic.dev/search – I get an error: `Searchable Statamic\Auth\File\User must implement Statamic\Contracts\Query\ContainsQueryableValues` when searching (even though the data gets added correctly to the search index). 

```php
 'indexes' => [
        'default' => [
            'driver' => 'local',
            'searchables' => [
                'users',
                ...
            ],
            'fields' => [
                'name',
                ...
            ],
        ],
```

### How to reproduce

- Install Statamic
- Create a user
- Open `config/statamic/search.php` and add "users" to the `searchables[]` array
- Create a simple search form and search results page
- The error appears on the search results page

### Logs

```shell
[2023-07-17 11:27:17] local.ERROR: Searchable Statamic\Auth\File\User must implement Statamic\Contracts\Query\ContainsQueryableValues {"userId":"489e3e3a-d95a-4922-947e-d0310d1ecb4e","exception":"[object] (Exception(code: 0): Searchable Statamic\\Auth\\File\\User must implement Statamic\\Contracts\\Query\\ContainsQueryableValues at /var/www/html/vendor/statamic/cms/src/Search/Result.php:98)
[stacktrace]
#0 /var/www/html/vendor/statamic/cms/src/Query/ResolveValue.php(52): Statamic\\Search\\Result->getQueryableValue()
#1 /var/www/html/vendor/statamic/cms/src/Query/ResolveValue.php(34): Statamic\\Query\\ResolveValue->getItemPartValue()
#2 /var/www/html/vendor/statamic/cms/src/Query/ResolveValue.php(22): Statamic\\Query\\ResolveValue->resolveItemPartValue()
#3 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(289): Statamic\\Query\\ResolveValue->__invoke()
#4 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(130): Statamic\\Query\\IteratorBuilder->getFilterItemValue()
#5 [internal function]: Statamic\\Query\\IteratorBuilder->Statamic\\Query\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(830): array_filter()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(382): Illuminate\\Support\\Arr::where()
#8 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(129): Illuminate\\Support\\Collection->filter()
#9 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(73): Statamic\\Query\\IteratorBuilder->filterWhereBasic()
#10 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(63): Statamic\\Query\\IteratorBuilder->filterWhere()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(734): Statamic\\Query\\IteratorBuilder->Statamic\\Query\\{closure}()
#12 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(60): Illuminate\\Support\\Collection->reduce()
#13 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(37): Statamic\\Query\\IteratorBuilder->filterWheres()
#14 /var/www/html/vendor/statamic/cms/src/Query/IteratorBuilder.php(21): Statamic\\Query\\IteratorBuilder->getFilteredItems()
#15 /var/www/html/vendor/statamic/cms/src/Tags/Concerns/GetsQueryResults.php(25): Statamic\\Query\\IteratorBuilder->get()
#16 /var/www/html/vendor/statamic/cms/src/Search/Tags.php(41): Statamic\\Search\\Tags->getQueryResults()
#17 [internal function]: Statamic\\Search\\Tags->results()
#18 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1549): call_user_func()
#19 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(747): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce()
#20 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render()
#21 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(768): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText()
#22 /var/www/html/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(195): Statamic\\View\\Antlers\\Engine->get()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#26 /var/www/html/vendor/statamic/cms/src/View/View.php(99): Illuminate\\View\\View->render()
#27 /var/www/html/vendor/statamic/cms/src/Http/Controllers/FrontendController.php(57): Statamic\\View\\View->render()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\FrontendController->route()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#34 /var/www/html/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#36 /var/www/html/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle()
#38 /var/www/html/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#40 /var/www/html/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle()
#42 /var/www/html/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle()
#44 /var/www/html/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle()
#46 /var/www/html/vendor/aryehraber/statamic-impersonator/src/ImpersonatorMiddleware.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): AryehRaber\\Impersonator\\ImpersonatorMiddleware->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#68 /var/www/html/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#70 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#72 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#74 /var/www/html/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#93 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#94 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#95 {main}
"}
```

### Environment

```yaml
Environment
Application Name: ...
Laravel Version: 9.52.10
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost:8003
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.1 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.6.0
jacksleight/statamic-bard-texstyle: 3.1.3
textandbytes/cp-assets: dev-main
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Can you paste your search:results tag?

> Create a simple search form and search results page

A simple results page looks like this:

```antlers
{{ search:results }}
    <li>{{ title }}</li>
{{ /search:results }}
```

This doesn't trigger an error. What else do you have on there?
