### ISSUE TITLE
Problem with setting entry links in a Bard field without allowed collections

### ISSUE THREAD

**Issue by jensolafkoch** [statamic/cms#8463]
### Bug description

In a Bard field I want to set a link to an entry. If there are NO collections assigned to the field which you can chose from, I get the following error message:

![Parser-Error](https://github.com/statamic/cms/assets/47628003/40bb2fe8-c3ec-4563-ba75-32662fdf9e6f)

`Statamic\Markdown\Parser::parse(): Argument #1 ($markdown) must be of type string, array given, called in D:\dev\apps\kb-blomstein-statamic\vendor\statamic\cms\src\Markdown\Manager.php on line 15
`
Instead a message would be better indicating that there are no collections assigned to chose entries from. 

[EDIT:] I found out that I had a problem in app/Http/Kernel.php due to a Laravel downgrade 10 -> 9 and had to change $middlewareAliases back to $routeMiddleware. This doesn't change the error message in itself though but a least an empty window for entry selection is shown now so that one can guess what's hapening here.

### How to reproduce

As above.

### Logs

```shell
[2023-07-18 14:35:33] local.ERROR: Statamic\Markdown\Parser::parse(): Argument #1 ($markdown) must be of type string, array given, called in D:\dev\apps\kb-blomstein-statamic\vendor\statamic\cms\src\Markdown\Manager.php on line 15 {"userId":"758d8f4c-15f2-431d-9a5f-bb9f73d474a0","exception":"[object] (TypeError(code: 0): Statamic\\Markdown\\Parser::parse(): Argument #1 ($markdown) must be of type string, array given, called in D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Markdown\\Manager.php on line 15 at D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Markdown\\Parser.php:25)
[stacktrace]
#0 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Markdown\\Manager.php(15): Statamic\\Markdown\\Parser->parse(Array)
#1 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(338): Statamic\\Markdown\\Manager->__call('parse', Array)
#2 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Support\\Html.php(312): Illuminate\\Support\\Facades\\Facade::__callStatic('parse', Array)
#3 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Fieldtypes\\Markdown.php(172): Statamic\\Support\\Html::markdown(Array)
#4 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Fields\\Field.php(309): Statamic\\Fieldtypes\\Markdown->preProcessIndex(Array)
#5 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Resources\\CP\\Entries\\ListedEntry.php(72): Statamic\\Fields\\Field->preProcessIndex()
#6 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(819): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->Statamic\\Http\\Resources\\CP\\Entries\\{closure}(Object(Statamic\\CP\\Column), 12)
#7 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Resources\\CP\\Entries\\ListedEntry.php(76): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#8 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Resources\\CP\\Entries\\ListedEntry.php(42): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->values(Array)
#9 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Resources\\Json\\JsonResource.php(95): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->toArray(Object(Illuminate\\Http\\Request))
#10 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Resources\\Json\\JsonResource.php(241): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#11 [internal function]: Illuminate\\Http\\Resources\\Json\\JsonResource->jsonSerialize()
#12 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\JsonResponse.php(87): json_encode(Array, 0)
#13 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\symfony\\http-foundation\\JsonResponse.php(49): Illuminate\\Http\\JsonResponse->setData(Array)
#14 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\JsonResponse.php(32): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array, false)
#15 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ResponseFactory.php(101): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)
#16 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse.php(28): Illuminate\\Routing\\ResponseFactory->json(Array, 200, Array, 0)
#17 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Resources\\Json\\ResourceCollection.php(133): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#18 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Resources\\Json\\ResourceCollection.php(113): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse(Object(Illuminate\\Http\\Request))
#19 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(888): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#20 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(875): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#21 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(798): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#22 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CP\\ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#51 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(799): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#61 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#62 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#63 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#64 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#65 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\statamic\\cms\\src\\Http\\Middleware\\PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#91 D:\\dev\\apps\\kb-blomstein-statamic\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#92 D:\\dev\\apps\\kb-blomstein-statamic\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#93 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.10
PHP Version: 8.1.5
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: kb-blomstein-statamic.local
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
teamnovu/statamic-unused-assets: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
Just done a quick search and found this error message in previous issues. See https://github.com/statamic/cms/issues/4961#issuecomment-1000037732
