### ISSUE TITLE
Call to a member function route() on null  

### ISSUE THREAD

**Issue by scottmetoyer** [statamic/cms#8519]
### Bug description

Updated my site from 3 to 4, now seeing this error.

It occurs after saving an entry and then attempting to edit another entry or browse to a different collection in the CP. Refreshing the page usually resolves the error.

### How to reproduce

Edit an entry, save it, click on another entry in the list or collection in the sidebar.

### Logs

```shell
[2023-08-01 03:22:03] production.ERROR: Call to a member function route() on null {"userId":"f6c9c3da-fc69-4b19-a009-a5a6cadcc4e1","exception":"[object] (Error(code: 0): Call to a member function route() on null at /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Entries/Entry.php:737)
[stacktrace]
#0 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Entries/Entry.php(763): Statamic\\Entries\\Entry->route()
#1 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Entries/Entry.php(893): Statamic\\Entries\\Entry->uri()
#2 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Query/ResolveValue.php(52): Statamic\\Entries\\Entry->getQueryableValue()
#3 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Query/ResolveValue.php(34): Statamic\\Query\\ResolveValue->getItemPartValue()
#4 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Query/ResolveValue.php(22): Statamic\\Query\\ResolveValue->resolveItemPartValue()
#5 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Indexes/Value.php(18): Statamic\\Query\\ResolveValue->__invoke()
#6 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Indexes/Value.php(12): Statamic\\Stache\\Indexes\\Value->getItemValue()
#7 [internal function]: Statamic\\Stache\\Indexes\\Value->Statamic\\Stache\\Indexes\\{closure}()
#8 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#9 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#10 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Indexes/Value.php(13): Illuminate\\Support\\Collection->map()
#11 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Indexes/Index.php(95): Statamic\\Stache\\Indexes\\Value->getItems()
#12 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Stores/CollectionsStore.php(87): Statamic\\Stache\\Indexes\\Index->update()
#13 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(87): Statamic\\Stache\\Stores\\CollectionsStore->updateEntryUris()
#14 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Statamic\\Stache\\Repositories\\CollectionRepository->updateEntryUris()
#15 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Entries/Collection.php(451): Illuminate\\Support\\Facades\\Facade::__callStatic()
#16 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Stores/CollectionsStore.php(107): Statamic\\Entries\\Collection->updateEntryUris()
#17 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Stores/BasicStore.php(20): Statamic\\Stache\\Stores\\CollectionsStore->handleFileChanges()
#18 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(40): Statamic\\Stache\\Stores\\BasicStore->getItem()
#19 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Statamic\\Stache\\Repositories\\CollectionRepository->findByHandle()
#20 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Providers/RouteServiceProvider.php(54): Illuminate\\Support\\Facades\\Facade::__callStatic()
#21 [internal function]: Statamic\\Providers\\RouteServiceProvider->Statamic\\Providers\\{closure}()
#22 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): call_user_func()
#23 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\\Routing\\Router->performBinding()
#24 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(39): Illuminate\\Routing\\Router->substituteBindings()
#25 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#26 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#28 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#32 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#33 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#35 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#37 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#39 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#41 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#43 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#44 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#45 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#48 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#50 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#52 /home/forge/docs.cherryaudio.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#54 /home/forge/docs.cherryaudio.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#56 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#58 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#59 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#61 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#62 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#64 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#66 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#68 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#70 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#72 /home/forge/docs.cherryaudio.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#73 /home/forge/docs.cherryaudio.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#74 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Cherry Audio Docs
Laravel Version: 10.16.1
PHP Version: 8.1.21
Composer Version: 2.5.8
Environment: production
Debug Mode: OFF
URL: docs.cherryaudio.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.2 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by scottmetoyer** [comment]
I disabled the stache watcher and that appears to have resolved the issue.
