### ISSUE TITLE
{{ nocache }} tag throws error since 4.34.0

### ISSUE THREAD

**Issue by atomicjam** [statamic/cms#9001]
### Bug description

since upgrading to 4.34.0 using {{ nocache }} tags in antlers templates throws "Call to a member function isTag() on null" 

### How to reproduce

{{ collection:news }}
        {{ nocache }} {{ title }} {{ /nocache }}
{{ /collection:news }}

### Logs

```shell
[2023-11-15 15:32:56] local.ERROR: Call to a member function isTag() on null {"userId":"718fefb8-3710-42b5-accd-e3e3d00daffe","exception":"[object] (Error(code: 0): Call to a member function isTag() on null at /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Analyzers/NodeTypeAnalyzer.php:45)
[stacktrace]
#0 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Parser/AntlersNodeParser.php(209): Statamic\\View\\Antlers\\Language\\Analyzers\\NodeTypeAnalyzer::analyzeNode()
#1 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Parser/DocumentParser.php(1167): Statamic\\View\\Antlers\\Language\\Parser\\AntlersNodeParser->parseNode()
#2 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Parser/DocumentParser.php(1025): Statamic\\View\\Antlers\\Language\\Parser\\DocumentParser->makeAntlersTagNode()
#3 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Parser/DocumentParser.php(268): Statamic\\View\\Antlers\\Language\\Parser\\DocumentParser->scanToEndOfAntlersRegion()
#4 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Parser/DocumentParser.php(440): Statamic\\View\\Antlers\\Language\\Parser\\DocumentParser->parseIntermediateText()
#5 /var/www/html/vendor/statamic/cms/src/View/Antlers/Language/Parser/IdentifierFinder.php(23): Statamic\\View\\Antlers\\Language\\Parser\\DocumentParser->parse()
#6 /var/www/html/vendor/statamic/cms/src/View/Antlers/Antlers.php(50): Statamic\\View\\Antlers\\Language\\Parser\\IdentifierFinder->getIdentifiers()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Statamic\\View\\Antlers\\Antlers->identifiers()
#8 /var/www/html/vendor/statamic/cms/src/StaticCaching/NoCache/Tags.php(27): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 [internal function]: Statamic\\StaticCaching\\NoCache\\Tags->index()
#10 /var/www/html/vendor/statamic/cms/src/View/Antlers/Engine.php(157): call_user_func()
#11 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag()
#12 /var/www/html/vendor/statamic/cms/src/View/Antlers/Parser.php(588): call_user_func_array()
#13 /var/www/html/vendor/statamic/cms/src/View/Antlers/Parser.php(180): Statamic\\View\\Antlers\\Parser->parseCallbackTags()
#14 /var/www/html/vendor/statamic/cms/src/View/Antlers/AntlersLoop.php(41): Statamic\\View\\Antlers\\Parser->parse()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(783): Statamic\\View\\Antlers\\AntlersLoop->Statamic\\View\\Antlers\\{closure}()
#16 /var/www/html/vendor/statamic/cms/src/View/Antlers/AntlersLoop.php(27): Illuminate\\Support\\Collection->reduce()
#17 /var/www/html/vendor/statamic/cms/src/View/Antlers/Parser.php(654): Statamic\\View\\Antlers\\AntlersLoop->__toString()
#18 /var/www/html/vendor/statamic/cms/src/View/Antlers/Parser.php(180): Statamic\\View\\Antlers\\Parser->parseCallbackTags()
#19 /var/www/html/vendor/statamic/cms/src/View/Antlers/Parser.php(135): Statamic\\View\\Antlers\\Parser->parse()
#20 /var/www/html/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Parser->parseView()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\\View\\Antlers\\Engine->get()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\\View\\View->getContents()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#24 /var/www/html/vendor/statamic/cms/src/View/View.php(115): Illuminate\\View\\View->render()
#25 /var/www/html/vendor/statamic/cms/src/Http/Responses/DataResponse.php(136): Statamic\\View\\View->render()
#26 /var/www/html/vendor/statamic/cms/src/Http/Responses/DataResponse.php(41): Statamic\\Http\\Responses\\DataResponse->contents()
#27 /var/www/html/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(893): Statamic\\Structures\\Page->toResponse()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(878): Illuminate\\Routing\\Router::toResponse()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Router->prepareResponse()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#32 /var/www/html/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#34 /var/www/html/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle()
#36 /var/www/html/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#38 /var/www/html/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle()
#40 /var/www/html/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle()
#42 /var/www/html/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle()
#44 /var/www/html/vendor/spatie/laravel-csp/src/AddCspHeaders.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spatie\\Csp\\AddCspHeaders->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#59 /var/www/html/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#68 /var/www/html/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#70 /var/www/html/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#72 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#74 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#76 /var/www/html/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#93 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#94 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#95 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#96 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#97 {main}
"}
```

### Environment

```yaml
Application Name: Laravel
Laravel Version: 10.32.1
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.34.0 PRO

Statamic Addons
mitydigital/feedamic: 2.2.9
mitydigital/sitemapamic: 2.3.8
rias/statamic-redirect: 3.3.0
teamnovu/statamic-images-missing-alt: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by atomicjam** [comment]
works fine on  4.33.0

**Comment by atomicjam** [comment]
nope I can put a more detailed template but it also throws with that exact example. I will attach a more detailed template.

**Comment by atomicjam** [comment]
```
{{ if type == "related_tagged" }}
{{ nocache }}
<section class="related_tagged">
    <div class="p-8 md:p-16 flex place-content-center {{ partial:partials/colourways/colourway_fill }}">
        <div class="max-w-6xl w-full grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {{ if title }}
            <div class="text-4xl col-span-full uppercase my-0 {{ partial:partials/colourways/colourway_accent }}">
                {{ title }}
            </div>
            {{ /if }}
   
            {{ taxonomy_term }}
                {{ entries limit="3" sort="date:desc" }}
                <a href="{{ url }}">
                    <div class="relative aspect-video">
                        <picture>
                            {{ if hero }}
                            {{ hero }}
                            <img src="{{ glide:url width='640' quality='75' }}" alt="{{ alt }}" class="h-52 w-full object-cover hover:scale-105 transition-all duration-1000" style="object-position: {{ focus_css }}" loading="lazy" fetchpriority="low" decoding="async">
                            {{ /hero }}
                            {{ else }}
                            {{ if link_hero }}
                            {{ link_hero }}
                            <img src="{{ glide:url width='640' quality='75' }}" alt="{{ alt }}" class="h-52 w-full object-cover hover:scale-105 transition-all duration-1000" style="object-position: {{ focus_css }}" loading="lazy" fetchpriority="low" decoding="async">
                            {{ /link_hero }}
                            {{ /if }}
                            {{ /if }}
                        </picture>
                    </div>
                    <div class="uppercase mt-4 {{ partial:partials/colourways/colourway_text }}">
                        {{ title }}
                    </div>
                </a>
                {{ /entries }}
            {{ /taxonomy_term }}
      
        </div>
    </div>
</section>
{{ /nocache }}
{{ /if }}
```

**Comment by atomicjam** [comment]
removing the nocache tags and the page renders else throws the error. the above template is a bard set

**Comment by atomicjam** [comment]
another example that if {{ nocache }} is removed works fine, all of these templates worked pre 4.33

```
{{ if type == "flockler" }}
{{ nocache }}
<div class="p-8 md:p-16 flex place-content-center">
  <div class=" w-full">
    <div id="flockler_container"></div>
  </div>
</div>
<script>
  var _flockler = _flockler || {};
  _flockler.count = {{ flockler_count }};
  _flockler.refresh = 0;
  _flockler.site = {{ flockler_siteid }};
  _flockler.section = {{ flockler_sectionid }};
  _flockler.style = 'wall';
  _flockler.extra = { wall_timestamps: true, open_in_current_tab: ['feed'] };
  _flockler.infiniteScroll = {{ infinite_scroll ? '1' : '0' }};
  (function (d) { var f = d.createElement('script'); f.async = 1; f.src = 'https://embed-cdn.flockler.com/embed-v2.js'; s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s); })(document);
</script>


{{ /nocache }}
{{ /if }}
```

**Comment by atomicjam** [comment]
third example
```
{{ if type == "news_highlight" }}
{{ nocache }}
<section class="news_highlight">
    {{ if !article }}

    {{ collection:news status:is="published" limit="1" as="highlight" sort="date:desc"}}
    {{ highlight }}
    <div class="{{ partial:partials/colourways/colourway_fill }}">
        <div class="grid lg:grid-cols-2 gap-x-4">
            <div class="text-center px-12 flex flex-col place-content-center content-center">
                <div class="uppercase text-4xl my-4 {{ partial:partials/colourways/colourway_text }}">{{ title }}</div>
                <div class="my-4">
                    <a href="{{ url }}" class="border-[1px] px-4 py-2 my-1 inline-block w-auto {{ partial:partials/colourways/colourway_text }}{{ partial:partials/colourways/colourway_boarder }}">Read More</a>
                </div>
            </div>
            <div class="order-first ml-16 lg:ml-0 lg:mb-16 lg:order-none">
                <picture>
                    {{ hero }}
                    <source type="image/webp" media="(min-width: 1919px)" srcset="{{ glide:url width='1919' quality='75' format='webp' }} 1x, {{ glide:url width='1919' quality='75' dpr='2' format='webp' }} 2x">
                    <source type="image/webp" media="(max-width: 1600px)" srcset="{{ glide:url width='1600' quality='75' format='webp' }} 1x">
                    <source type="image/webp" media="(max-width: 1366px)" srcset="{{ glide:url width='1366' quality='75' format='webp' }} 1x, {{ glide:url width='1366' quality='75' dpr='2' format='webp' }} 2x">
                    <source type="image/webp" media="(max-width: 640px)" srcset="{{ glide:url width='640' quality='75' format='webp' }}, {{ glide:url width='640' quality='75' dpr='2' format='webp' }} 2x">
                    <source type="image/jpg" media="(min-width: 1919px)" srcset="{{ glide:url width='1919' quality='75' }} 1x, {{ glide:url width='1919' quality='75' dpr='2' }} 2x">
                    <source type="image/jpg" media="(max-width: 1600px)" srcset="{{ glide:url width='1600' quality='75' }} 1x">
                    <source type="image/jpg" media="(max-width: 1366px)" srcset="{{ glide:url width='1366' quality='75' }} 1x, {{ glide:url width='1366' quality='75' dpr='2' }} 2x">
                    <source type="image/jpg" media="(max-width: 640px)" srcset="{{ glide:url width='640' quality='75' }}, {{ glide:url width='640' quality='75' dpr='2' }} 2x">
                    <img src="{{ glide:url width='1366' quality='75' }}" alt="{{ image:alt }}" class="w-auto h-auto aspect-video object-cover" style="object-position: {{ focus_css }}" loading="lazy" fetchpriority="high" decoding="async">
                    {{ /hero }}
                </picture>
            </div>
        </div>
    </div>
    {{ /highlight }}
    {{ /collection:news }}
   {{ /if }}
</section>
{{ /nocache }}
{{ /if }}
```

**Comment by atomicjam** [comment]
further info fyi:

.env
```
STATAMIC_STATIC_CACHING_STRATEGY=half
```

static_caching.php unchanged from defaults 
```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Active Static Caching Strategy
    |--------------------------------------------------------------------------
    |
    | To enable Static Caching, you should choose a strategy from the ones
    | you have defined below. Leave this null to disable static caching.
    |
    */

    'strategy' => env('STATAMIC_STATIC_CACHING_STRATEGY', null),

    /*
    |--------------------------------------------------------------------------
    | Caching Strategies
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the static caching strategies for your
    | application as well as their drivers.
    |
    | Supported drivers: "application", "file"
    |
    */

    'strategies' => [

        'half' => [
            'driver' => 'application',
            'expiry' => null,
        ],

        'full' => [
            'driver' => 'file',
            'path' => public_path('static'),
            'lock_hold_length' => 0,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Exclusions
    |--------------------------------------------------------------------------
    |
    | Here you may define a list of URLs to be excluded from static
    | caching. You may want to exclude URLs containing dynamic
    | elements like contact forms, or shopping carts.
    |
    */

    'exclude' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Invalidation Rules
    |--------------------------------------------------------------------------
    |
    | Here you may define the rules that trigger when and how content would be
    | flushed from the static cache. See the documentation for more details.
    | If a custom class is not defined, the default invalidator is used.
    |
    | https://statamic.dev/static-caching
    |
    */

    'invalidation' => [

        'class' => null,

        'rules' => [
            //
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Ignoring Query Strings
    |--------------------------------------------------------------------------
    |
    | Statamic will cache pages of the same URL but with different query
    | parameters separately. This is useful for pages with pagination.
    | If you'd like to ignore the query strings, you may do so.
    |
    */

    'ignore_query_strings' => false,

];
```

**Comment by atomicjam** [comment]
layout.antlers has template content loaded and then the sets templates above loaded 
```
{{ content }}
    {{ partial src="partials/sets/{type}" }}
{{ /content }}
```

any sets that use {{ nocache }} tag throw error, if I edit layout and add a {{ nocache }} error Is thrown, removing {{ nocache }} tags and pages all load fine.

**Comment by atomicjam** [comment]
Yes!, setting to runtime instead of regex & everything working corretly again. 
Just waiting for our unit tests to complete to ensure its not broken something else.

Out of interest, im assuming this has resulted because we have an old statamic 3 site that has been upgraded over time. Im usually good at reading the patch notes and upgrade guides would this have been in one of them? as it looks like we should have upgraded the runtime when we switched to v4?

**Comment by jasonvarga** [comment]
Nope it wasn't a required change. I just noticed you're using the regex version and I have never got that error before because I've been using runtime.

If nothing else seems to be broken, I'd suggest using runtime anyway. We're gonna remove regex in v5.

**Comment by patrickomeara** [comment]
I'm having the same issue with the runtime version, when using the variable within a PHP antler tag.

Removing the nocache tag fixes the issues, so does moving the nocache tag outside the current loop.

```html

{{ nocache }}
      <div>
          {{$ App\Support\Paddle::priceForMonthlyPlan($plan_type) $}}
      </div>
      <div>
          {{$ App\Support\Paddle::priceForYearlyPlan($plan_type) $}}
      </div>
{{ /nocache }}
```

**Comment by duncanmcclean** [comment]
Can you try manually specifying the fields you're using inside the `priceForYearlyPlan` method?

```antlers
{{ nocache select="url|title|description" }}
```

**Comment by patrickomeara** [comment]
Hi @duncanmcclean that works. I had tried using select with comma separated values, I should've tried pipes!

FYI This was working correctly in `4.13.2` I've only had the issue since upgrading to `4.38.0`

**Comment by patrickomeara** [comment]
I would also add that the [documentation](https://statamic.dev/tags/nocache) of the `{{ nocache }}` tag doesn't include anything about the `select` param.
