### ISSUE TITLE
4.39.0 breaks some antlers with collection vars

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9161]
### Bug description

```
{{ elseif seo:change_page_title | where('collection', {collection}) }}
```

This piece of code doesn't work anymore and throws the following error:

str_contains(): Argument #1 ($haystack) must be of type string, array given

Possibly related to: https://github.com/statamic/cms/pull/9106

Changing to this fixes the issue:

```
{{ elseif seo:change_page_title | where('collection', collection) }}
```

### How to reproduce

1. Install Peak
2. Go to globals -> SEO
3. Under Manipulate collection title click Add collection default
4. Set a custom text for the pages collection
5. Visit the homepage

### Logs

```shell
[2023-12-08 11:44:59] local.ERROR: str_contains(): Argument #1 ($haystack) must be of type string, array given {"userId":"b40458fa-e73a-4f88-bfa1-570cd54b72e0","exception":"[object] (TypeError(code: 0): str_contains(): Argument #1 ($haystack) must be of type string, array given at /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Support/Str.php:268)
[stacktrace]
#0 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Support/Str.php(268): str_contains(Array, 'int_65fa3739')
#1 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Support/Str.php(314): Illuminate\\Support\\Str::contains(Array, Array)
#2 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1357): Statamic\\Support\\Str::__callStatic('contains', Array)
#3 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(1655): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->adjustValue(Array, Object(Statamic\\View\\Antlers\\Language\\Nodes\\Structures\\SemanticGroup))
#4 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(947): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->getValue(Object(Statamic\\View\\Antlers\\Language\\Nodes\\Structures\\SemanticGroup))
#5 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(295): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->process(Array)
#6 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(318): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->processStatements(Array)
#7 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/Sandbox/Environment.php(352): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluate(Array)
#8 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/ConditionProcessor.php(100): Statamic\\View\\Antlers\\Language\\Runtime\\Sandbox\\Environment->evaluateBool(Array)
#9 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1305): Statamic\\View\\Antlers\\Language\\Runtime\\ConditionProcessor->process(Object(Statamic\\View\\Antlers\\Language\\Nodes\\Conditions\\ConditionNode), Array)
#10 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#11 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#12 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{#\\n\\t@name SEO\\n...', Array)
#13 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/robdekor...', '{{#\\n\\t@name SEO\\n...', Array)
#14 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\\View\\Antlers\\Engine->get('/Users/robdekor...', Array)
#15 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\\View\\View->getContents()
#16 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#17 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\\View\\View->render()
#18 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('statamic-peak-s...')
#19 [internal function]: Statamic\\Tags\\Partial->wildcard('statamic-peak-s...')
#20 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array, 'statamic-peak-s...')
#21 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#22 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#23 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{#\\n\\t@name Layo...', Array)
#24 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/robdekor...', '{{#\\n\\t@name Layo...', Array)
#25 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\\View\\Antlers\\Engine->get('/Users/robdekor...', Array)
#26 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\\View\\View->getContents()
#27 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#28 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/View/View.php(115): Illuminate\\View\\View->render()
#29 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Responses/DataResponse.php(146): Statamic\\View\\View->render()
#30 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Responses/DataResponse.php(42): Statamic\\Http\\Responses\\DataResponse->contents()
#31 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#32 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(900): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#33 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#34 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#35 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#54 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/robdekort/Sites/1902/vendor/torchlight/torchlight-laravel/src/Middleware/RenderTorchlight.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Torchlight\\Middleware\\RenderTorchlight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#65 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#66 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#67 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#68 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#69 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/robdekort/Sites/1902/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/robdekort/Sites/1902/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/robdekort/Sites/1902/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/robdekort/Sites/1902/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
... (7 lines left)
```

### Environment

```yaml
Environment
Application Name: Studio 1902
Laravel Version: 10.35.0
PHP Version: 8.2.10
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: 1902.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Attributes\Plugin: 2.5.1
LaravelLang\HttpStatuses\Plugin: 3.6.3
LaravelLang\Lang\Plugin: 13.11.0
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Livewire
Livewire: v3.2.6

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.39.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.0.0
ryanmitchell/statamic-translation-manager: 1.2.2
studio1902/statamic-peak-browser-appearance: 3.3.2
studio1902/statamic-peak-commands: 3.1.0
studio1902/statamic-peak-seo: 7.3.1
studio1902/statamic-peak-tools: 4.0.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by robdekort** [comment]
Note: please rollback the SEO addon to v7.3.1 to see the issue.
