### ISSUE TITLE
Blueprint with empty section throws an error on the fieldsets listing page

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#9173]
### Bug description

Since v4.39.0 the `/cp/fields/fieldsets` route throws an error when there are fieldsets and one of the blueprints has an empty section.

`Statamic\Fields\Fieldset::fieldImportsFieldset(): Argument #1 ($field) must be of type array, null given, called in /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php on line 132`

### How to reproduce

Clone the repo: https://github.com/marcorieser/statamic-fieldset-error

Or:
- Setup a new Statamic instance
- Create a Fieldset "Test" without a field
- Add an empty section to the pages blueprint
- Visit the `/cp/fields/fieldsets` route

### Logs

```shell
[2023-12-11 10:09:07] local.ERROR: Statamic\Fields\Fieldset::fieldImportsFieldset(): Argument #1 ($field) must be of type array, null given, called in /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php on line 132 {"userId":"1355341d-c859-4de5-b0ea-2c97286de141","exception":"[object] (TypeError(code: 0): Statamic\\Fields\\Fieldset::fieldImportsFieldset(): Argument #1 ($field) must be of type array, null given, called in /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php on line 132 at /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php:148)
[stacktrace]
#0 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php(132): Statamic\\Fields\\Fieldset->fieldImportsFieldset(NULL)
#1 [internal function]: Statamic\\Fields\\Fieldset->Statamic\\Fields\\{closure}(NULL, 4)
#2 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(871): array_filter(Array, Object(Closure), 1)
#3 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#4 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php(132): Illuminate\\Support\\Collection->filter(Object(Closure))
#5 [internal function]: Statamic\\Fields\\Fieldset->Statamic\\Fields\\{closure}(Object(Statamic\\Fields\\Blueprint), 0)
#6 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(871): array_filter(Array, Object(Closure), 1)
#7 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#8 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Fields/Fieldset.php(126): Illuminate\\Support\\Collection->filter(Object(Closure))
#9 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Controllers/CP/Fields/FieldsetController.php(33): Statamic\\Fields\\Fieldset->importedBy()
#10 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(796): Statamic\\Http\\Controllers\\CP\\Fields\\FieldsetController->Statamic\\Http\\Controllers\\CP\\Fields\\{closure}(Object(Statamic\\Fields\\Fieldset), 'test')
#11 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(388): Illuminate\\Support\\Collection->mapToDictionary(Object(Closure))
#12 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Controllers/CP/Fields/FieldsetController.php(25): Illuminate\\Support\\Collection->mapToGroups(Object(Closure))
#13 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Fields\\FieldsetController->index(Object(Illuminate\\Http\\Request))
#14 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('index', Array)
#15 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Fields\\FieldsetController), 'index')
#16 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#17 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#18 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'configure field...')
#21 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/SelectedSite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\SelectedSite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#51 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#61 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#62 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#63 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#64 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/marco/localweb/statamic-fieldset-error/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/marco/localweb/statamic-fieldset-error/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#93 /Users/marco/localweb/statamic-fieldset-error/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#94 /Users/marco/localweb/statamic-fieldset-error/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#95 /Users/marco/.composer/vendor/laravel/valet/server.php(110): require('/Users/marco/lo...')
#96 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.35.0
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: statamic-fieldset-error.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.39.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by j3ll3yfi5h** [comment]
Same here: Had one empty sidebar in a blueprint which caused the same error
