### ISSUE TITLE
Deleting an Asset triggers error

### ISSUE THREAD

**Issue by webdevanthonyg** [statamic/cms#9192]
### Bug description

Whenever I try to delete an Asset in list view or grid view I get an error: 
[2023-12-12 21:37:24] local.ERROR: foreach() argument must be of type array|object, string given {"userId":"a442a9ba-dc0a-463c-baa0-f9e56ea3a2eb","exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, string given at /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:114).

The Asset is deleted, but the page doesn't refresh/redirect and I can still see the modal and asset in the control panel.
![asset-deletion-bug](https://github.com/statamic/cms/assets/106164168/9e881a8b-e095-4a1f-b1a7-1e00d40dfbfd)

### How to reproduce

Create an Asset and try to delete it as a Super Admin.

### Logs

```shell
[2023-12-12 21:37:24] local.ERROR: foreach() argument must be of type array|object, string given {"userId":"a442a9ba-dc0a-463c-baa0-f9e56ea3a2eb","exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, string given at /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:114)
[stacktrace]
#0 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(114): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Support/Arr.php(323): Illuminate\\Support\\Arr::dot()
#3 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(259): Statamic\\Support\\Arr::__callStatic()
#4 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(237): Statamic\\Assets\\AssetReferenceUpdater->updateStatamicUrlsInImageNodes()
#5 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(105): Statamic\\Assets\\AssetReferenceUpdater->updateStatamicUrlsInArrayValue()
#6 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Statamic\\Assets\\AssetReferenceUpdater->Statamic\\Assets\\{closure}()
#7 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(102): Illuminate\\Support\\Collection->each()
#8 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(39): Statamic\\Assets\\AssetReferenceUpdater->updateBardFieldValues()
#9 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Data/DataReferenceUpdater.php(63): Statamic\\Assets\\AssetReferenceUpdater->recursivelyUpdateFields()
#10 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(93): Statamic\\Data\\DataReferenceUpdater->updateReferences()
#11 [internal function]: Statamic\\Listeners\\UpdateAssetReferences->Statamic\\Listeners\\{closure}()
#12 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#13 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#14 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(90): Illuminate\\Support\\Collection->map()
#15 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(70): Statamic\\Listeners\\UpdateAssetReferences->replaceReferences()
#16 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): Statamic\\Listeners\\UpdateAssetReferences->handleDeleted()
#17 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle()
#18 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#22 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#23 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#24 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#26 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
#27 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#28 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#30 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#31 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#32 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#33 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push()
#34 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(594): Illuminate\\Queue\\Queue->pushOn()
#35 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(515): Illuminate\\Events\\Dispatcher->queueHandler()
#36 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#37 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#38 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(433): Illuminate\\Events\\Dispatcher->dispatch()
#39 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event()
#40 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Assets/Asset.php(628): Statamic\\Events\\Event::dispatch()
#41 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Statamic\\Assets\\Asset->delete()
#42 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
#43 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(59): Illuminate\\Support\\Collection->each()
#44 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Actions/Delete.php(57): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
#45 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Controllers/CP/ActionController.php(38): Statamic\\Actions\\Delete->run()
#46 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\ActionController->run()
#47 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#48 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#49 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#50 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#51 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#52 /srv/web/mydomain.com/html/vendor/mitydigital/statamic-two-factor/src/Http/Middleware/EnforceTwoFactor.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): MityDigital\\StatamicTwoFactor\\Http\\Middleware\\EnforceTwoFactor->handle()
#54 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle()
#56 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#58 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle()
#60 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle()
#62 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle()
#64 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/SelectedSite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\SelectedSite->handle()
#66 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#68 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#70 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle()
#72 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle()
#74 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#76 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#78 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#80 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#82 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#84 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#85 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#87 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#89 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#91 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#93 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#94 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#95 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#96 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#97 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#98 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#99 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#100 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#101 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#102 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#103 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#104 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#105 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#106 /srv/web/mydomain.com/html/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#107 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#108 /srv/web/mydomain.com/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#109 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#110 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#111 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#112 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#113 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#114 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#115 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#116 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#117 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#118 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#119 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#120 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#121 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#122 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#123 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#124 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#125 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#126 /srv/web/mydomain.com/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#127 /srv/web/mydomain.com/html/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#128 {main}
"}
```

### Environment

```yaml
Environment
Application Name: My Application
Laravel Version: 10.20.0
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: mydomain.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.26.1 PRO

Statamic Addons
doublethreedigital/runway: 5.2.0
jacksleight/statamic-bard-texstyle: 3.1.3
mitydigital/statamic-tinymce-cloud: 2.1.2
mitydigital/statamic-two-factor: 1.1.4
withcandour/aardvark-seo: 3.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
This error seems to be coming from the code which updates references to assets in content when they're deleted, specifically when you're using images in Bard fields.

Are you able to share the blueprint used by the entry that referenced the now-deleted asset?

**Comment by webdevanthonyg** [comment]
@duncanmcclean The Asset isn't referenced in any Bard field, I just upload a new file and attempt to delete it. It's not associated with any content, it's just a fresh Asset/file.

**Comment by ryanmitchell** [comment]
Do you have any bard fields in your blueprints that are set to `save_html` ?

**Comment by webdevanthonyg** [comment]
@ryanmitchell All of my Bard fields have save_html: false set on them.

**Comment by webdevanthonyg** [comment]
I migrated a bunch of WordPress Blog data into a Bard field. For some reason this caused a lot of errors, even when converted to ProseMirror. I ended up deleting all of the data, swapping the field for a TinyMCE field, and reimporting all of the data, and everything is working out fine now.

**Comment by freshjones** [comment]
I am getting this bug as well. no save_html fields... just straight asset upload and attempt to delete

<img width="1356" alt="Screenshot 2024-02-29 at 10 23 29 AM" src="https://github.com/statamic/cms/assets/158955/2776e566-ef0f-48c1-a612-aca979c32d51">
