### ISSUE TITLE
Unable to create new entries in Control Panel

### ISSUE THREAD

**Issue by skoontastic** [statamic/cms#931]
Steps to reproduce:

1. Install Statamic v3 via Composer
2. Create user account via make:user
3. Log in and try to create a new Page via Collections > Pages

Exception pops up on the bottom of the screen. Here is what DebugBar shows:

```

Object of class Statamic\Sites\Site could not be converted to string
/Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Stache/Repositories/EntryRepository.php#121
ErrorException
#0 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Stache/Repositories/EntryRepository.php(121): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Object of class...', '/Users/jeremysc...', 121, Array)
#1 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(245): Statamic\Stache\Repositories\EntryRepository->createRules(Object(Statamic\Entries\Collection), Object(Statamic\Sites\Site))
#2 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(287): Illuminate\Support\Facades\Facade::__callStatic('createRules', Array)
#3 [internal function]: Statamic\Http\Controllers\CP\Collections\EntriesController->store(Object(Illuminate\Http\Request), Object(Statamic\Entries\Collection), Object(Statamic\Sites\Site))
#4 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store', Array)
#6 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Statamic\Http\Controllers\CP\Collections\EntriesController), 'store')
#7 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#8 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Route->run()
#9 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\CP\Authorize->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#32 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Http/Middleware/VanityRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\VanityRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/useraccount/Sites/laravel/statamic3/vendor/statamic/cms/src/Http/Middleware/PermanentRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PermanentRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/useraccount/Sites/laravel/statamic3/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/useraccount/Sites/laravel/statamic3/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /Users/useraccount/Sites/laravel/statamic3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 /Users/useraccount/Sites/laravel/statamic3/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 /Users/useraccount/.composer/vendor/laravel/valet/server.php(151): require('/Users/jeremysc...')
#58 {main}

```

This also happens after creating a new Collection type and attempting to create an entry.

**Comment by jackmcdade** [comment]
How exactly did you install? Did you composer require or follow the docs with:

```
composer create-project statamic/statamic my-site --prefer-dist --stability=dev
```

**Comment by jasonvarga** [comment]
Fixed by #922

**Comment by jackmcdade** [comment]
Well there you go. Update and try again! 😊

**Comment by skoontastic** [comment]
Ha! I hesitated to even file this since I figured it wasn't just me. Glad it's fixed.
