### ISSUE TITLE
FR: Throw error when `content` handle is used for non-string fieldtypes

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#942]
Users will often try to name their Bard or Replicator fields `content` but it is not allowed for non-string fields. An error should be thrown when the handle `content` is used for the wrong field type.

**Comment by jasonvarga** [comment]
It is allowed in v3. If you’re running into a specific issue let us know.

**Comment by mikemartin** [comment]
```
[2019-11-22 05:32:33] production.ERROR: Illegal string offset 'type' {"userId":"8475d0b9-ec1a-4846-b64d-732ce3406dd2","exception":"[object] (ErrorException(code: 0): Illegal string offset 'type' at /Users/mike/Sites/szc2/vendor/statamic/cms/src/Fieldtypes/Bard.php:185)
[stacktrace]
#0 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Fieldtypes/Bard.php(185): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Illegal string ...', '/Users/mike/Sit...', 185, Array)
#1 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(640): Statamic\\Fieldtypes\\Bard->Statamic\\Fieldtypes\\{closure}('', 0)
#2 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}('', 0)
#3 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Arr.php(611): array_filter(Array, Object(Closure), 1)
#4 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(352): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#5 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(642): Illuminate\\Support\\Collection->filter(Object(Closure))
#6 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Fieldtypes/Bard.php(186): Illuminate\\Support\\Collection->reject(Object(Closure))
#7 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Fields/Field.php(214): Statamic\\Fieldtypes\\Bard->preProcessIndex('')
#8 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(59): Statamic\\Fields\\Field->preProcessIndex()
#9 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(685): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->Statamic\\Http\\Resources\\CP\\Entries\\{closure}(Object(Statamic\\CP\\Column), 2)
#10 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(63): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#11 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(41): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->values(Array)
#12 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(94): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->toArray(Object(Illuminate\\Http\\Request))
#13 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(211): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#14 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(709): Illuminate\\Http\\Resources\\Json\\JsonResource->jsonSerialize()
#15 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}(Object(Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry))
#16 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(717): array_map(Object(Closure), Array)
#17 [internal function]: Illuminate\\Support\\Collection->jsonSerialize()
#18 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(71): json_encode(Array, 0)
#19 /Users/mike/Sites/szc2/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#20 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array)
#21 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(95): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)
#22 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(26): Illuminate\\Routing\\ResponseFactory->json(Array, 200)
#23 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(71): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#24 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(733): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#25 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#26 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#27 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/mike/Sites/szc2/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\StaticCaching\\Middleware\\Retrieve->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#49 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#50 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#51 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#52 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Middleware/VanityRedirects.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\VanityRedirects->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/mike/Sites/szc2/vendor/statamic/cms/src/Http/Middleware/PermanentRedirects.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PermanentRedirects->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/mike/Sites/szc2/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/mike/Sites/szc2/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#73 /Users/mike/Sites/szc2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#74 /Users/mike/Sites/szc2/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#75 /Users/mike/.composer/vendor/laravel/valet/server.php(158): require('/Users/mike/Sit...')
#76 {main}
"} 
```

**Comment by mikemartin** [comment]
Fieldset:

```
title: Page
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          character_limit: 0
          type: text
          localizable: false
          width: 50
          display: Title
      -
        handle: slug
        field:
          generate: true
          type: slug
          localizable: false
          width: 50
          display: Slug
      -
        handle: content
        field:
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          type: bard
          localizable: false
          display: Content
```

**Comment by jasonvarga** [comment]
Dupe of #941 then 👌

**Comment by curtisblackwell** [comment]
I'm still seeing this problem on beta.43 when I name a replicator `content`

**Comment by jasonvarga** [comment]
Show the stack trace? (You can click `share` on the flare exception)

What's the replicator field in the blueprint look like?

What's in the content's md file?
