### ISSUE TITLE
renderException method is deprecated

### ISSUE THREAD

**Issue by psren** [statamic/cms#973]
```php
php artisan package:discover
```

```php
PHP Fatal error:  Uncaught ErrorException: The "Symfony\Component\Console\Application::renderException()" method is deprecated since Symfony 4.4, use "renderThrowable()" instead. in vendor\symfony\console\Application.php:796
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'The "Symfony\\Co...', '', 796, Array)
#1 vendor\symfony\console\Application.php(796): trigger_error('The "Symfony\\Co...', 16384)
#2 vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(479): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(112): Illuminate\Foundation\Exceptions\Handler->renderForConsole(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Error in vendor\symfony\console\Application.php on line 796
PHP Fatal error:  Uncaught ErrorException: The "Symfony\Component\Debug\Exception\FatalErrorException" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\Error\FatalError" instead. in vendor\symfony\debug\Exception\F
atalErrorException.php:14
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'The "Symfony\\Co...', 'C:\\Users\\HellPa...', 14, Array)
#1 vendor\symfony\debug\Exception\FatalErrorException.php(14): trigger_error('The "Symfony\\Co...', 16384)
#2 vendor\composer\ClassLoader.php(444): include('C:\\Users\\HellPa...')
#3 vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\Users\\HellPa...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(147): spl in vendor\symfony\debug\Exception\FatalErrorException.php on line 14
```

**Comment by jasonvarga** [comment]
How did you install Statamic and/or Laravel?

**Comment by kylesean** [comment]
I guess your laravel or lumen version was lower。find the file like  vendor/laravel/lumen-framework/src/Exceptions/Hanlder.php:
```
public function renderForConsole($output, Exception $e)
    {
        (new ConsoleApplication)->renderException($e, $output); // replace with renderThrowable
    }
```

**Comment by psren** [comment]
Hey there,

I installed statamic via
```
composer create-project statamic/statamic cms_b --prefer-dist --stability=dev
``` 

If I downgrade this two to symfony `~4.2` it works like expected.
```
"symfony/console": "~4.2.0",
"symfony/debug": "~4.2.0",
```

The error I get is a "Symfony-Deprecation" via `E_USER_DEPRECATED`; this one _should_ (?) get muted but didn't.
```
@trigger_error(sprintf('The "%s::renderException()" method is deprecated since Symfony 4.4, use "renderThrowable()" instead.', __CLASS__), E_USER_DEPRECATED);
```

**Comment by psren** [comment]
It indeed works now with `@beta` and I cannot repuce it anymore
