### ISSUE TITLE
Error when uploading images with eloquent-driver and stache file watcher disabled.

### ISSUE THREAD

**Issue by vluijkx** [statamic/cms#9802]
### Bug description

PR https://github.com/statamic/cms/pull/9378 might have introduced a bug. We have been getting the following error whenever we upload images with `STATAMIC_STACHE_WATCHER` disabled:

```
Image [img_df2ee67b55a8-1-1711712458.jpg] does not actually appear to be a valid image.
```

![CleanShot 2024-03-29 at 14 07 38@2x](https://github.com/statamic/cms/assets/22601927/17dd71c0-974f-47b0-b02c-e834526a410c)

The issue seems to be caused by this line of code:
https://github.com/statamic/cms/blob/c2c5fe7d619c286fa8d6fe073fef018a22861fee/src/Assets/Asset.php#L606

The error does not appear after temporary changing the line to:

```php
$isNew = true;
```

I have put this issue in the `statamic/cms` repo as the issue seems to be caused by a change in here. Just let me know if I have to move it to `eloquent-driver`.

### How to reproduce

1. Set `STATAMIC_STACHE_WATCHER=false` in your `.env` file.
3. Install `eloquent-driver` and set the asset driver to `eloquent`. 
3. Upload an image.

### Logs

```shell
[2024-03-29 13:11:13] local.ERROR: Image [cleanshot-2024-03-28-at-21.13.41@2x-1711717873.png] does not actually appear to be a valid image. {"userId":2,"exception":"[object] (Exception(code: 0): Image [cleanshot-2024-03-28-at-21.13.41@2x-1711717873.png] does not actually appear to be a valid image. at /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/ImageGenerator.php:309)
[stacktrace]
#0 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/ImageGenerator.php(255): Statamic\\Imaging\\ImageGenerator->validateImage()
#1 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/ImageGenerator.php(167): Statamic\\Imaging\\ImageGenerator->generate('cleanshot-2024-...')
#2 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/ImageGenerator.php(150): Statamic\\Imaging\\ImageGenerator->doGenerateByAsset(Object(Statamic\\Eloquent\\Assets\\Asset), Array)
#3 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(437): Statamic\\Imaging\\ImageGenerator->Statamic\\Imaging\\{closure}()
#4 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/ImageGenerator.php(148): Illuminate\\Cache\\Repository->rememberForever('asset::images::...', Object(Closure))
#5 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/PresetGenerator.php(31): Statamic\\Imaging\\ImageGenerator->generateByAsset(Object(Statamic\\Eloquent\\Assets\\Asset), Array)
#6 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Statamic\\Imaging\\PresetGenerator->Statamic\\Imaging\\{closure}('cp_thumbnail_sm...', 0)
#7 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Imaging/PresetGenerator.php(30): Illuminate\\Support\\Collection->each(Object(Closure))
#8 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Listeners/GeneratePresetImageManipulations.php(50): Statamic\\Imaging\\PresetGenerator->generate(Object(Statamic\\Eloquent\\Assets\\Asset))
#9 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(114): Statamic\\Listeners\\GeneratePresetImageManipulations->handle(Object(Statamic\\Events\\AssetUploaded))
#10 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle(Object(Illuminate\\Foundation\\Application))
#11 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#13 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#16 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#17 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#18 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Events\\CallQueuedListener), false)
#20 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#21 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#22 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Illuminate\\Events\\CallQueuedListener))
#24 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#25 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#26 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(59): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Events\\CallQueuedListener), '', NULL)
#27 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(633): Illuminate\\Queue\\Queue->pushOn(NULL, Object(Illuminate\\Events\\CallQueuedListener))
#28 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(552): Illuminate\\Events\\Dispatcher->queueHandler('Statamic\\\\Listen...', 'handle', Array)
#29 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(Statamic\\Events\\AssetUploaded))
#30 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Statamic\\\\Events...', Array)
#31 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('Statamic\\\\Events...', Array, false)
#32 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(433): Illuminate\\Events\\Dispatcher->dispatch('Statamic\\\\Events...')
#33 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Events/Event.php(21): event(Object(Statamic\\Events\\AssetUploaded))
#34 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Assets/Asset.php(897): Statamic\\Events\\Event::dispatch(Object(Statamic\\Eloquent\\Assets\\Asset))
#35 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Controllers/CP/Assets/AssetsController.php(84): Statamic\\Assets\\Asset->upload(Object(Illuminate\\Http\\UploadedFile))
#36 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Assets\\AssetsController->store(Object(Illuminate\\Http\\Request))
#37 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('store', Array)
#38 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Assets\\AssetsController), 'store')
#39 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#40 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#41 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/SelectedSite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\SelectedSite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#72 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#81 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#82 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#83 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#84 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#85 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#93 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /Users/vicluijkx/Repositories/hior-website/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/vicluijkx/Repositories/hior-website/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#101 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#102 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#103 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#106 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#107 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#108 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#109 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#110 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#111 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#112 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#113 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#114 /Users/vicluijkx/Repositories/hior-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#115 /Users/vicluijkx/Repositories/hior-website/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#116 /Applications/Herd.app/Contents/Resources/valet/server.php(151): require('/Users/vicluijk...')
#117 {main}
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.53.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: eloquent
Global Variables: file
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```

### Installation

Existing Laravel app

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
I'm not able to reproduce this issue myself - I've tested both with and without the Eloquent Driver.

It looks like you're running an old version of the Eloquent Driver though - the latest is v3.3.3. It might be worth upgrading in case that resolves the issue.

If that doesn't help, leave a comment on statamic/eloquent-driver#246 (which is related to the same issue) and we can re-open. Thanks!
