### ISSUE TITLE
[5.x] Uncaught Error: Class `App\Console\Kernel` not found when running `pls support:details`

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#9949]
### Bug description

If I understand correctly that Kernel thingy isn't there anymore when using Laravel's 11 new app skeleton. However it is still required by Please it seems.

### How to reproduce

Install V5 alpha 5 with the L11 new app skeleton
Run `pls support:details`

### Logs

```shell
Fatal error: Uncaught Error: Class "App\Console\Kernel" not found in /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Console/Please/Kernel.php:11
Stack trace:
#0 /Users/robdekort/Sites/connect2id/vendor/composer/ClassLoader.php(576): include()
#1 /Users/robdekort/Sites/connect2id/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/robdekor...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Statamic\\Consol...')
#3 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Container/Container.php(904): ReflectionClass->__construct('Statamic\\Consol...')
#4 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\Container\Container->build('Statamic\\Consol...')
#5 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1026): Illuminate\Container\Container->resolve('Statamic\\Consol...', Array, true)
#6 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Container/Container.php(723): Illuminate\Foundation\Application->resolve('Statamic\\Consol...', Array)
#7 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\Container\Container->make('Statamic\\Consol...', Array)
#8 /Users/robdekort/Sites/connect2id/please(33): Illuminate\Foundation\Application->make('Statamic\\Consol...')
#9 {main}
  thrown in /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Console/Please/Kernel.php on line 11
```

### Environment

```yaml
.
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by robdekort** [comment]
Oh darn, I missed that one! Sorry about this.

**Comment by duncanmcclean** [comment]
No worries!
